# UdaciHeadline: LLM Inference Optimization Project

## Project Introduction
Large Language Models (LLMs) are transforming content creation, but deploying them efficiently remains a major hurdle. Imagine you're an ML Engineer at a bustling online news portal. Your key task? Automatically generating catchy headlines from article summaries using an LLM. The problem? The current inference process is sluggish, causing publication delays and driving up operational costs. In this project, UdaciHeadline, you'll step into this role and tackle this critical challenge head-on. Your mission is to accelerate the headline generation pipeline significantly by applying state-of-the-art LLM inference optimization techniques. Get ready to dive deep into practical optimization and deployment!

## Project Summary
This project provides hands-on experience in optimizing the inference performance of a pre-trained Large Language Model (like Llama-3.2-1B) for news headline generation. You will bring together concepts of LLM architecture, optimization techniques, and deployment frameworks. Specifically, you will:

1.  **Establish a baseline** inference pipeline and profile its performance.
2.  Implement and evaluate architectural optimizations like **KV-caching**.
3.  Apply model compression techniques like **quantization** and **pruning**.
4.  Configure and benchmark **distributed inference** using Tensor and Pipeline Parallelism.
5.  Apply advanced decoding mechanisms like **speculative decoding**.
6.  Perform comprehensive **benchmarking and analysis** across all stages.
7.  Produce a **final report** summarizing findings and trade-offs.

## Imports and Global Configuration

Let's import the libraries we'll use throughout the project and define some constants like the model name and the prompt template.

In [1]:
!pip install peft

Collecting peft
  Downloading peft-0.18.1-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: numpy>=1.17 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from peft) (1.26.4)
Requirement already satisfied: packaging>=20.0 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from peft) (24.2)
Requirement already satisfied: psutil in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from peft) (7.2.2)
Requirement already satisfied: pyyaml in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from peft) (6.0.3)
Requirement already satisfied: torch>=1.13.0 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from peft) (2.6.0+cu124)
Collecting transformers (from peft)
  Downloading transformers-5.5.0-py3-none-any.whl.metadata (32 kB)
Requirement already satisfied: tqdm in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from peft) (4.67.3)
Collecting accelerate>=0.21.0 (from peft)
  Downloading accelerate-1.13.0-py3-none-any.whl.metadata (19 kB)
Collecting safetensors (from peft)
  Downloading safetensors-0.7.0-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.1 kB)
Collecting huggingface_hub>=0.25.0 (from peft)
  Downloading huggingface_hub-1.9.0-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: filelock>=3.10.0 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from huggingface_hub>=0.25.0->peft) (3.25.2)
Requirement already satisfied: fsspec>=2023.5.0 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from huggingface_hub>=0.25.0->peft) (2026.2.0)
Collecting hf-xet<2.0.0,>=1.4.3 (from huggingface_hub>=0.25.0->peft)
  Downloading hf_xet-1.4.3-cp37-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Collecting httpx<1,>=0.23.0 (from huggingface_hub>=0.25.0->peft)
  Using cached httpx-0.28.1-py3-none-any.whl.metadata (7.1 kB)
Requirement already satisfied: typer in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from huggingface_hub>=0.25.0->peft) (0.24.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from huggingface_hub>=0.25.0->peft) (4.15.0)
Requirement already satisfied: anyio in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.25.0->peft) (4.13.0)
Requirement already satisfied: certifi in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.25.0->peft) (2026.2.25)
Collecting httpcore==1.* (from httpx<1,>=0.23.0->huggingface_hub>=0.25.0->peft)
  Using cached httpcore-1.0.9-py3-none-any.whl.metadata (21 kB)
Requirement already satisfied: idna in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.25.0->peft) (3.11)
Requirement already satisfied: h11>=0.16 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface_hub>=0.25.0->peft) (0.16.0)
Requirement already satisfied: networkx in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from torch>=1.13.0->peft) (3.4.2)
Requirement already satisfied: jinja2 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from torch>=1.13.0->peft) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.4.127 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from torch>=1.13.0->peft) (12.4.127)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.4.127 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from torch>=1.13.0->peft) (12.4.127)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.4.127 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from torch>=1.13.0->peft) (12.4.127)
Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from torch>=1.13.0->peft) (9.1.0.70)
Requirement already satisfied: nvidia-cublas-cu12==12.4.5.8 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from torch>=1.13.0->peft) (12.4.5.8)
Requirement already satisfied: nvidia-cufft-cu12==11.2.1.3 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from torch>=1.13.0->peft) (11.2.1.3)
Requirement already satisfied: nvidia-curand-cu12==10.3.5.147 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from torch>=1.13.0->peft) (10.3.5.147)
Requirement already satisfied: nvidia-cusolver-cu12==11.6.1.9 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from torch>=1.13.0->peft) (11.6.1.9)
Requirement already satisfied: nvidia-cusparse-cu12==12.3.1.170 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from torch>=1.13.0->peft) (12.3.1.170)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.2 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from torch>=1.13.0->peft) (0.6.2)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from torch>=1.13.0->peft) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from torch>=1.13.0->peft) (12.4.127)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.4.127 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from torch>=1.13.0->peft) (12.4.127)
Requirement already satisfied: triton==3.2.0 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from torch>=1.13.0->peft) (3.2.0)
Requirement already satisfied: sympy==1.13.1 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from torch>=1.13.0->peft) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from sympy==1.13.1->torch>=1.13.0->peft) (1.3.0)
Requirement already satisfied: exceptiongroup>=1.0.2 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from anyio->httpx<1,>=0.23.0->huggingface_hub>=0.25.0->peft) (1.3.1)
Requirement already satisfied: MarkupSafe>=2.0 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from jinja2->torch>=1.13.0->peft) (3.0.3)
Requirement already satisfied: regex>=2025.10.22 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from transformers->peft) (2026.2.28)
Collecting tokenizers<=0.23.0,>=0.22.0 (from transformers->peft)
  Downloading tokenizers-0.22.2-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.3 kB)
Requirement already satisfied: click>=8.2.1 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from typer->huggingface_hub>=0.25.0->peft) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from typer->huggingface_hub>=0.25.0->peft) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from typer->huggingface_hub>=0.25.0->peft) (14.3.3)
Requirement already satisfied: annotated-doc>=0.0.2 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from typer->huggingface_hub>=0.25.0->peft) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from rich>=12.3.0->typer->huggingface_hub>=0.25.0->peft) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from rich>=12.3.0->typer->huggingface_hub>=0.25.0->peft) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface_hub>=0.25.0->peft) (0.1.2)
Downloading peft-0.18.1-py3-none-any.whl (556 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 557.0/557.0 kB 19.8 MB/s  0:00:00
Downloading accelerate-1.13.0-py3-none-any.whl (383 kB)
Downloading huggingface_hub-1.9.0-py3-none-any.whl (637 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 637.4/637.4 kB 46.7 MB/s  0:00:00
Downloading hf_xet-1.4.3-cp37-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 181.3 MB/s  0:00:00
Using cached httpx-0.28.1-py3-none-any.whl (73 kB)
Using cached httpcore-1.0.9-py3-none-any.whl (78 kB)
Downloading safetensors-0.7.0-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (507 kB)
Downloading transformers-5.5.0-py3-none-any.whl (10.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.2/10.2 MB 121.9 MB/s  0:00:00
Downloading tokenizers-0.22.2-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 165.8 MB/s  0:00:00
Installing collected packages: safetensors, httpcore, hf-xet, httpx, huggingface_hub, tokenizers, accelerate, transformers, peft
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9/9 [peft][32m8/9 [peft]formers]ub]
Successfully installed accelerate-1.13.0 hf-xet-1.4.3 httpcore-1.0.9 httpx-0.28.1 huggingface_hub-1.9.0 peft-0.18.1 safetensors-0.7.0 tokenizers-0.22.2 transformers-5.5.0

In [2]:
!pip install datasets==3.3.0

Collecting datasets==3.3.0
  Downloading datasets-3.3.0-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: filelock in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from datasets==3.3.0) (3.25.2)
Requirement already satisfied: numpy>=1.17 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from datasets==3.3.0) (1.26.4)
Requirement already satisfied: pyarrow>=15.0.0 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from datasets==3.3.0) (20.0.0)
Collecting dill<0.3.9,>=0.3.0 (from datasets==3.3.0)
  Downloading dill-0.3.8-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: pandas in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from datasets==3.3.0) (2.3.3)
Requirement already satisfied: requests>=2.32.2 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from datasets==3.3.0) (2.32.5)
Requirement already satisfied: tqdm>=4.66.3 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from datasets==3.3.0) (4.67.3)
Collecting xxhash (from datasets==3.3.0)
  Downloading xxhash-3.6.0-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (13 kB)
Collecting multiprocess<0.70.17 (from datasets==3.3.0)
  Downloading multiprocess-0.70.16-py310-none-any.whl.metadata (7.2 kB)
Collecting fsspec<=2024.12.0,>=2023.1.0 (from fsspec[http]<=2024.12.0,>=2023.1.0->datasets==3.3.0)
  Downloading fsspec-2024.12.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: aiohttp in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from datasets==3.3.0) (3.13.3)
Requirement already satisfied: huggingface-hub>=0.24.0 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from datasets==3.3.0) (1.9.0)
Requirement already satisfied: packaging in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from datasets==3.3.0) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from datasets==3.3.0) (6.0.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from aiohttp->datasets==3.3.0) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from aiohttp->datasets==3.3.0) (1.4.0)
Requirement already satisfied: async-timeout<6.0,>=4.0 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from aiohttp->datasets==3.3.0) (5.0.1)
Requirement already satisfied: attrs>=17.3.0 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from aiohttp->datasets==3.3.0) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from aiohttp->datasets==3.3.0) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from aiohttp->datasets==3.3.0) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from aiohttp->datasets==3.3.0) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from aiohttp->datasets==3.3.0) (1.23.0)
Requirement already satisfied: typing-extensions>=4.1.0 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from multidict<7.0,>=4.5->aiohttp->datasets==3.3.0) (4.15.0)
Requirement already satisfied: idna>=2.0 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from yarl<2.0,>=1.17.0->aiohttp->datasets==3.3.0) (3.11)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from huggingface-hub>=0.24.0->datasets==3.3.0) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from huggingface-hub>=0.24.0->datasets==3.3.0) (0.28.1)
Requirement already satisfied: typer in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from huggingface-hub>=0.24.0->datasets==3.3.0) (0.24.1)
Requirement already satisfied: anyio in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.24.0->datasets==3.3.0) (4.13.0)
Requirement already satisfied: certifi in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.24.0->datasets==3.3.0) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.24.0->datasets==3.3.0) (1.0.9)
Requirement already satisfied: h11>=0.16 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.24.0->datasets==3.3.0) (0.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from requests>=2.32.2->datasets==3.3.0) (3.4.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from requests>=2.32.2->datasets==3.3.0) (2.6.3)
Requirement already satisfied: exceptiongroup>=1.0.2 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from anyio->httpx<1,>=0.23.0->huggingface-hub>=0.24.0->datasets==3.3.0) (1.3.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from pandas->datasets==3.3.0) (2.9.0)
Requirement already satisfied: pytz>=2020.1 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from pandas->datasets==3.3.0) (2026.1.post1)
Requirement already satisfied: tzdata>=2022.7 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from pandas->datasets==3.3.0) (2025.3)
Requirement already satisfied: six>=1.5 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas->datasets==3.3.0) (1.17.0)
Requirement already satisfied: click>=8.2.1 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from typer->huggingface-hub>=0.24.0->datasets==3.3.0) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from typer->huggingface-hub>=0.24.0->datasets==3.3.0) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from typer->huggingface-hub>=0.24.0->datasets==3.3.0) (14.3.3)
Requirement already satisfied: annotated-doc>=0.0.2 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from typer->huggingface-hub>=0.24.0->datasets==3.3.0) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from rich>=12.3.0->typer->huggingface-hub>=0.24.0->datasets==3.3.0) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from rich>=12.3.0->typer->huggingface-hub>=0.24.0->datasets==3.3.0) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub>=0.24.0->datasets==3.3.0) (0.1.2)
Downloading datasets-3.3.0-py3-none-any.whl (484 kB)
Downloading dill-0.3.8-py3-none-any.whl (116 kB)
Downloading fsspec-2024.12.0-py3-none-any.whl (183 kB)
Downloading multiprocess-0.70.16-py310-none-any.whl (134 kB)
Downloading xxhash-3.6.0-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (193 kB)
Installing collected packages: xxhash, fsspec, dill, multiprocess, datasets
  Attempting uninstall: fsspec
    Found existing installation: fsspec 2026.2.0
    Uninstalling fsspec-2026.2.0:
      Successfully uninstalled fsspec-2026.2.0
  Attempting uninstall: dill0m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1/5 [fsspec]
    Found existing installation: dill 0.4.1━━━━━━━━━━━━━━━━━━━ 1/5 [fsspec]
    Uninstalling dill-0.4.1:90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1/5 [fsspec]
      Successfully uninstalled dill-0.4.10m━━━━━━━━━━━━━━━━━━━━━━━ 2/5 [dill]
  Attempting uninstall: multiprocess90m━━━━━━━━━━━━━━━━━━━━━━━ 2/5 [dill]
    Found existing installation: multiprocess 0.70.19━━━━━━━━━ 2/5 [dill]
    Uninstalling multiprocess-0.70.19:90m╺━━━━━━━━━━━━━━━ 3/5 [multiprocess]
      Successfully uninstalled multiprocess-0.70.19━━━━━━━━━━━ 3/5 [multiprocess]
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5/5 [datasets]4/5 [datasets]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pathos 0.3.5 requires dill>=0.4.1, but you have dill 0.3.8 which is incompatible.
pathos 0.3.5 requires multiprocess>=0.70.19, but you have multiprocess 0.70.16 which is incompatible.
Successfully installed datasets-3.3.0 dill-0.3.8 fsspec-2024.12.0 multiprocess-0.70.16 xxhash-3.6.0

In [3]:
!pip install evaluate

Collecting evaluate
  Downloading evaluate-0.4.6-py3-none-any.whl.metadata (9.5 kB)
Requirement already satisfied: datasets>=2.0.0 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from evaluate) (3.3.0)
Requirement already satisfied: numpy>=1.17 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from evaluate) (1.26.4)
Requirement already satisfied: dill in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from evaluate) (0.3.8)
Requirement already satisfied: pandas in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from evaluate) (2.3.3)
Requirement already satisfied: requests>=2.19.0 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from evaluate) (2.32.5)
Requirement already satisfied: tqdm>=4.62.1 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from evaluate) (4.67.3)
Requirement already satisfied: xxhash in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from evaluate) (3.6.0)
Requirement already satisfied: multiprocess in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from evaluate) (0.70.16)
Requirement already satisfied: fsspec>=2021.05.0 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from fsspec[http]>=2021.05.0->evaluate) (2024.12.0)
Requirement already satisfied: huggingface-hub>=0.7.0 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from evaluate) (1.9.0)
Requirement already satisfied: packaging in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from evaluate) (24.2)
Requirement already satisfied: filelock in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from datasets>=2.0.0->evaluate) (3.25.2)
Requirement already satisfied: pyarrow>=15.0.0 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from datasets>=2.0.0->evaluate) (20.0.0)
Requirement already satisfied: aiohttp in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from datasets>=2.0.0->evaluate) (3.13.3)
Requirement already satisfied: pyyaml>=5.1 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from datasets>=2.0.0->evaluate) (6.0.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from aiohttp->datasets>=2.0.0->evaluate) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.4.0)
Requirement already satisfied: async-timeout<6.0,>=4.0 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from aiohttp->datasets>=2.0.0->evaluate) (5.0.1)
Requirement already satisfied: attrs>=17.3.0 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from aiohttp->datasets>=2.0.0->evaluate) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from aiohttp->datasets>=2.0.0->evaluate) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from aiohttp->datasets>=2.0.0->evaluate) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.23.0)
Requirement already satisfied: typing-extensions>=4.1.0 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from multidict<7.0,>=4.5->aiohttp->datasets>=2.0.0->evaluate) (4.15.0)
Requirement already satisfied: idna>=2.0 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from yarl<2.0,>=1.17.0->aiohttp->datasets>=2.0.0->evaluate) (3.11)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from huggingface-hub>=0.7.0->evaluate) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from huggingface-hub>=0.7.0->evaluate) (0.28.1)
Requirement already satisfied: typer in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from huggingface-hub>=0.7.0->evaluate) (0.24.1)
Requirement already satisfied: anyio in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.7.0->evaluate) (4.13.0)
Requirement already satisfied: certifi in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.7.0->evaluate) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.7.0->evaluate) (1.0.9)
Requirement already satisfied: h11>=0.16 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.7.0->evaluate) (0.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from requests>=2.19.0->evaluate) (3.4.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from requests>=2.19.0->evaluate) (2.6.3)
Requirement already satisfied: exceptiongroup>=1.0.2 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from anyio->httpx<1,>=0.23.0->huggingface-hub>=0.7.0->evaluate) (1.3.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from pandas->evaluate) (2.9.0)
Requirement already satisfied: pytz>=2020.1 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from pandas->evaluate) (2026.1.post1)
Requirement already satisfied: tzdata>=2022.7 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from pandas->evaluate) (2025.3)
Requirement already satisfied: six>=1.5 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas->evaluate) (1.17.0)
Requirement already satisfied: click>=8.2.1 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from typer->huggingface-hub>=0.7.0->evaluate) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from typer->huggingface-hub>=0.7.0->evaluate) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from typer->huggingface-hub>=0.7.0->evaluate) (14.3.3)
Requirement already satisfied: annotated-doc>=0.0.2 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from typer->huggingface-hub>=0.7.0->evaluate) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from rich>=12.3.0->typer->huggingface-hub>=0.7.0->evaluate) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from rich>=12.3.0->typer->huggingface-hub>=0.7.0->evaluate) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub>=0.7.0->evaluate) (0.1.2)
Downloading evaluate-0.4.6-py3-none-any.whl (84 kB)
Installing collected packages: evaluate
Successfully installed evaluate-0.4.6

In [4]:
!pip install kagglehub

Collecting kagglehub
  Downloading kagglehub-1.0.0-py3-none-any.whl.metadata (40 kB)
Collecting kagglesdk<1.0,>=0.1.14 (from kagglehub)
  Downloading kagglesdk-0.1.16-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: packaging in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from kagglehub) (24.2)
Requirement already satisfied: pyyaml in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from kagglehub) (6.0.3)
Requirement already satisfied: requests in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from kagglehub) (2.32.5)
Requirement already satisfied: tqdm in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from kagglehub) (4.67.3)
Requirement already satisfied: protobuf in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from kagglesdk<1.0,>=0.1.14->kagglehub) (6.33.5)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from requests->kagglehub) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from requests->kagglehub) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from requests->kagglehub) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from requests->kagglehub) (2026.2.25)
Downloading kagglehub-1.0.0-py3-none-any.whl (70 kB)
Downloading kagglesdk-0.1.16-py3-none-any.whl (160 kB)
Installing collected packages: kagglesdk, kagglehub
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [kagglehub]
Successfully installed kagglehub-1.0.0 kagglesdk-0.1.16

In [5]:
!pip install -U Pillow

Requirement already satisfied: Pillow in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (12.1.1)
Collecting Pillow
  Downloading pillow-12.2.0-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (8.8 kB)
Downloading pillow-12.2.0-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (8.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.1/8.1 MB 71.0 MB/s  0:00:00
Installing collected packages: Pillow
  Attempting uninstall: Pillow
    Found existing installation: pillow 12.1.1
    Uninstalling pillow-12.1.1:
      Successfully uninstalled pillow-12.1.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
sagemaker-serve 1.6.0 requires sagemaker-core>=2.6.0, but you have sagemaker-core 1.0.77 which is incompatible.
sagemaker-train 1.6.0 requires sagemaker-core>=2.6.0, but you have sagemaker-core 1.0.77 which is incompatible.
Successfully installed Pillow-12.2.0

In [6]:
!pip install -U jinja2

Requirement already satisfied: jinja2 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (3.1.6)
Requirement already satisfied: MarkupSafe>=2.0 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from jinja2) (3.0.3)

In [7]:
!pip install nltk rouge_score

Requirement already satisfied: nltk in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (3.9.4)
Collecting rouge_score
  Downloading rouge_score-0.1.2.tar.gz (17 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: click in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from nltk) (8.3.1)
Requirement already satisfied: joblib in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from nltk) (2026.2.28)
Requirement already satisfied: tqdm in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from nltk) (4.67.3)
Collecting absl-py (from rouge_score)
  Downloading absl_py-2.4.0-py3-none-any.whl.metadata (3.3 kB)
Requirement already satisfied: numpy in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from rouge_score) (1.26.4)
Requirement already satisfied: six>=1.14.0 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from rouge_score) (1.17.0)
Downloading absl_py-2.4.0-py3-none-any.whl (135 kB)
Building wheels for collected packages: rouge_score
  Building wheel for rouge_score (pyproject.toml) ... done
  Created wheel for rouge_score: filename=rouge_score-0.1.2-py3-none-any.whl size=24988 sha256=7aa98ac7527a7d75ba7dde5ab84fac72f3fb36d85feec3525bd68e7aff044027
  Stored in directory: /home/ec2-user/.cache/pip/wheels/5f/dd/89/461065a73be61a532ff8599a28e9beef17985c9e9c31e541b4
Successfully built rouge_score
Installing collected packages: absl-py, rouge_score
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [rouge_score]
Successfully installed absl-py-2.4.0 rouge_score-0.1.2

In [8]:
!pip install -U bitsandbytes

Collecting bitsandbytes
  Downloading bitsandbytes-0.49.2-py3-none-manylinux_2_24_x86_64.whl.metadata (10 kB)
Requirement already satisfied: torch<3,>=2.3 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from bitsandbytes) (2.6.0+cu124)
Requirement already satisfied: numpy>=1.17 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from bitsandbytes) (1.26.4)
Requirement already satisfied: packaging>=20.9 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from bitsandbytes) (24.2)
Requirement already satisfied: filelock in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from torch<3,>=2.3->bitsandbytes) (3.25.2)
Requirement already satisfied: typing-extensions>=4.10.0 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from torch<3,>=2.3->bitsandbytes) (4.15.0)
Requirement already satisfied: networkx in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from torch<3,>=2.3->bitsandbytes) (3.4.2)
Requirement already satisfied: jinja2 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from torch<3,>=2.3->bitsandbytes) (3.1.6)
Requirement already satisfied: fsspec in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from torch<3,>=2.3->bitsandbytes) (2024.12.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.4.127 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from torch<3,>=2.3->bitsandbytes) (12.4.127)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.4.127 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from torch<3,>=2.3->bitsandbytes) (12.4.127)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.4.127 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from torch<3,>=2.3->bitsandbytes) (12.4.127)
Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from torch<3,>=2.3->bitsandbytes) (9.1.0.70)
Requirement already satisfied: nvidia-cublas-cu12==12.4.5.8 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from torch<3,>=2.3->bitsandbytes) (12.4.5.8)
Requirement already satisfied: nvidia-cufft-cu12==11.2.1.3 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from torch<3,>=2.3->bitsandbytes) (11.2.1.3)
Requirement already satisfied: nvidia-curand-cu12==10.3.5.147 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from torch<3,>=2.3->bitsandbytes) (10.3.5.147)
Requirement already satisfied: nvidia-cusolver-cu12==11.6.1.9 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from torch<3,>=2.3->bitsandbytes) (11.6.1.9)
Requirement already satisfied: nvidia-cusparse-cu12==12.3.1.170 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from torch<3,>=2.3->bitsandbytes) (12.3.1.170)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.2 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from torch<3,>=2.3->bitsandbytes) (0.6.2)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from torch<3,>=2.3->bitsandbytes) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from torch<3,>=2.3->bitsandbytes) (12.4.127)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.4.127 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from torch<3,>=2.3->bitsandbytes) (12.4.127)
Requirement already satisfied: triton==3.2.0 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from torch<3,>=2.3->bitsandbytes) (3.2.0)
Requirement already satisfied: sympy==1.13.1 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from torch<3,>=2.3->bitsandbytes) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from sympy==1.13.1->torch<3,>=2.3->bitsandbytes) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from jinja2->torch<3,>=2.3->bitsandbytes) (3.0.3)
Downloading bitsandbytes-0.49.2-py3-none-manylinux_2_24_x86_64.whl (60.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.7/60.7 MB 60.5 MB/s  0:00:01m0:00:0100:01m
Installing collected packages: bitsandbytes
Successfully installed bitsandbytes-0.49.2

In [1]:
import os
import torch
import pandas as pd
import numpy as np
from datasets import load_dataset, Dataset
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig
from evaluate import load as load_metric
import time
from pprint import pprint
import torch.nn.utils.prune as prune
from transformers import pipeline
import accelerate

/home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/torch/cuda/__init__.py:61: FutureWarning: The pynvml package is deprecated. Please install nvidia-ml-py instead. If you did not install pynvml directly, please report this to the maintainers of the package that installed pynvml for you.
  import pynvml  # type: ignore[import]

In [2]:
MODEL_NAME = "meta-llama/Llama-3.2-1B-Instruct"
BIG_MODEL_ID = "meta-llama/Llama-3.2-3B-Instruct"
MAX_NEW_TOKENS = 40 # Max length for the generated headline
DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'
print(DEVICE)

cuda

In [3]:
import numpy
numpy.__version__

'1.26.4'

## Data Loading

We will use the "News Category Dataset" from Kaggle. The `kagglehub` library makes it easy to download and access. Your task is to implement the function to load and preprocess the data according to the docstring.

In [4]:
def load_news_dataset():
    """TODO: Implement the data loading and preprocessing logic here."""
    import kagglehub
    # Download latest version
    path = kagglehub.dataset_download("rmisra/news-category-dataset")
    print("Path to dataset files:", path)
    import pandas as pd
    df = pd.read_json(path+'/News_Category_Dataset_v3.json', lines = True)
    print(f'Number of news items in each category\n####################################\n{df["category"].value_counts()}')
    print(f'###########################################################')
    print(f'Total number of news categories in dataset: {len(pd.DataFrame(df["category"].value_counts()))}')
    print(f'###########################################################')
    df_1 = df[['headline', 'category', 'short_description']].copy()
    news_ds = Dataset.from_pandas(df_1)
    print(news_ds)
    return news_ds

In [5]:
news_ds = load_news_dataset()

Downloading to /home/ec2-user/.cache/kagglehub/datasets/rmisra/news-category-dataset/3.archive...

100%|██████████| 26.5M/26.5M [00:00<00:00, 111MB/s]

Extracting files...

Path to dataset files: /home/ec2-user/.cache/kagglehub/datasets/rmisra/news-category-dataset/versions/3
Number of news items in each category
####################################
category
POLITICS          35602
WELLNESS          17945
ENTERTAINMENT     17362
TRAVEL             9900
STYLE & BEAUTY     9814
PARENTING          8791
HEALTHY LIVING     6694
QUEER VOICES       6347
FOOD & DRINK       6340
BUSINESS           5992
COMEDY             5400
SPORTS             5077
BLACK VOICES       4583
HOME & LIVING      4320
PARENTS            3955
THE WORLDPOST      3664
WEDDINGS           3653
WOMEN              3572
CRIME              3562
IMPACT             3484
DIVORCE            3426
WORLD NEWS         3299
MEDIA              2944
WEIRD NEWS         2777
GREEN              2622
WORLDPOST          2579
RELIGION           2577
STYLE              2254
SCIENCE            2206
TECH               2104
TASTE              2096
MONEY              1756
ARTS               1509
ENVIRONMENT        1444
FIFTY              1401
GOOD NEWS          1398
U.S. NEWS          1377
ARTS & CULTURE     1339
COLLEGE            1144
LATINO VOICES      1130
CULTURE & ARTS     1074
EDUCATION          1014
Name: count, dtype: int64
###########################################################
Total number of news categories in dataset: 42
###########################################################
Dataset({
    features: ['headline', 'category', 'short_description'],
    num_rows: 209527
})

In [6]:
news_ds

Dataset({
    features: ['headline', 'category', 'short_description'],
    num_rows: 209527
})

# 2. Baseline Performance

Before we can optimize, we need a starting point. Here, you'll establish the baseline performance of the `Llama-3.2-1B` model without any specific optimizations. We will measure latency, throughput, and the quality of the generated headlines using the ROUGE score.

### Your Task: Implement the Evaluation Pipeline
You need to implement the core functions for loading a model, generating a headline, and evaluating performance. These functions will be reused for every optimization technique.

In [7]:
from huggingface_hub import login
login("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")

In [8]:
def get_model_memory_footprint(model):
    """Calculates and returns the model's memory footprint in MB."""
    mem_params = sum(param.nelement() * param.element_size() for param in model.parameters())
    mem_bufs = sum(buf.nelement() * buf.element_size() for buf in model.buffers())
    total_mem_bytes = mem_params + mem_bufs
    return total_mem_bytes / (1024 ** 2) # Convert bytes to MB

In [9]:
def load_model(MODEL_NAME, DEVICE, quantization_config=None):
    """TODO: Implement the logic for loading a tokenizer and model."""
    print("Loading tokenizer...")
    tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME,
                                              padding_side="left", 
                                              trust_remote_code= True
                                             )
    print("Tokenizer loaded successfully.")
    print("\nLoading model...")
    if quantization_config is None:
        model = AutoModelForCausalLM.from_pretrained(
            MODEL_NAME,
            torch_dtype=torch.float16,
            device_map= "balanced",
            trust_remote_code =True
            ).to(DEVICE)
    else:
        model = AutoModelForCausalLM.from_pretrained(
            MODEL_NAME,
            quantization_config=quantization_config,
            device_map= "auto",
            trust_remote_code =True
            ).to(DEVICE)
    print("Model loaded successfully and moved to device.")
    memory_mb = get_model_memory_footprint(model)
    print(f"Memory Footprint: {memory_mb:.2f} MB")
  
    model.config.eos_token_id = tokenizer.eos_token_id
    tokenizer.pad_token = tokenizer.eos_token
    tokenizer.pad_token_id = tokenizer.eos_token_id
    model.config.pad_token_id = model.config.eos_token_id
    model.eval()
    return tokenizer, model

In [10]:
tokenizer, model = load_model(MODEL_NAME, DEVICE, quantization_config=None)
model = model.to(DEVICE)

Loading tokenizer...

config.json:   0%|          | 0.00/877 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/296 [00:00<?, ?B/s]

`torch_dtype` is deprecated! Use `dtype` instead!

Tokenizer loaded successfully.

Loading model...

model.safetensors:   0%|          | 0.00/2.47G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/146 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/189 [00:00<?, ?B/s]

You shouldn't move a model that is dispatched using accelerate hooks.
You shouldn't move a model that is dispatched using accelerate hooks.

Model loaded successfully and moved to device.
Memory Footprint: 2357.13 MB

In [11]:
def convert_chat_form_tokenize(tokenizer, ds):

    def base_format(sample):
        system_message = f'You are a news headline generator who generates catchy news headline from given news summary.\nGenerate a headline for following news summary of type: {sample["category"]}'
        messages = [
            {"role": 'system','content': system_message},
            {"role": 'user','content': sample["short_description"]},
            ]
        if generate_text:
            text_dict = {'text_gen': messages}
        else:
            messages.append({"role": 'assistant','content': sample["headline"]})
            text_dict = {'text': messages}
        return text_dict

    def apply_chat_temp(example):
        if generate_text:
            toks = tokenizer.apply_chat_template(example['text_gen'],tokenize=True, add_generation_prompt=True)
        else:
            toks = tokenizer.apply_chat_template(example['text'],tokenize=True)
        return toks

    generate_text = False
    ds = ds.map(base_format)
    #print(ds[0])

    generate_text = True
    ds = ds.map(base_format)
    #print(ds[0])

    tok_ds = ds.train_test_split(test_size=0.01, seed=42)
    print(tok_ds)
    
    generate_text = False
    tok_ds['train'] = tok_ds['train'].map(apply_chat_temp)
    #print(ds[0])

    #tok_ds = ds.train_test_split(test_size=0.01, seed=42)

    generate_text = True
    tok_ds['test'] = tok_ds['test'].map(apply_chat_temp)
    #print(tok_ds['test'][0])
    #print(tok_ds['train'][0], tok_ds['test'][0])
    return tok_ds

In [12]:
tok_ds = convert_chat_form_tokenize(tokenizer, news_ds)

Map:   0%|          | 0/209527 [00:00<?, ? examples/s]

Map:   0%|          | 0/209527 [00:00<?, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['headline', 'category', 'short_description', 'text', 'text_gen'],
        num_rows: 207431
    })
    test: Dataset({
        features: ['headline', 'category', 'short_description', 'text', 'text_gen'],
        num_rows: 2096
    })
})

Map:   0%|          | 0/207431 [00:00<?, ? examples/s]

Map:   0%|          | 0/2096 [00:00<?, ? examples/s]

In [13]:
tok_ds

DatasetDict({
    train: Dataset({
        features: ['headline', 'category', 'short_description', 'text', 'text_gen', 'input_ids', 'attention_mask'],
        num_rows: 207431
    })
    test: Dataset({
        features: ['headline', 'category', 'short_description', 'text', 'text_gen', 'input_ids', 'attention_mask'],
        num_rows: 2096
    })
})

In [14]:
tok_ds['train'][1]

{'headline': "Trump's Approach To The Opioid Epidemic: Neglect Treatment, Ignore The Experts",
 'category': 'POLITICS',
 'short_description': "Trump's budget cuts are baffling drug policy advocates and former government officials.",
 'text': [{'content': 'You are a news headline generator who generates catchy news headline from given news summary.\nGenerate a headline for following news summary of type: POLITICS',
   'role': 'system'},
  {'content': "Trump's budget cuts are baffling drug policy advocates and former government officials.",
   'role': 'user'},
  {'content': "Trump's Approach To The Opioid Epidemic: Neglect Treatment, Ignore The Experts",
   'role': 'assistant'}],
 'text_gen': [{'content': 'You are a news headline generator who generates catchy news headline from given news summary.\nGenerate a headline for following news summary of type: POLITICS',
   'role': 'system'},
  {'content': "Trump's budget cuts are baffling drug policy advocates and former government officials.",
   'role': 'user'}],
 'input_ids': [128000,
  128006,
  9125,
  128007,
  271,
  38766,
  1303,
  33025,
  2696,
  25,
  6790,
  220,
  2366,
  18,
  198,
  15724,
  2696,
  25,
  220,
  2589,
  5186,
  220,
  2366,
  21,
  271,
  2675,
  527,
  264,
  3754,
  32263,
  14143,
  889,
  27983,
  86605,
  3754,
  32263,
  505,
  2728,
  3754,
  12399,
  627,
  32215,
  264,
  32263,
  369,
  2768,
  3754,
  12399,
  315,
  955,
  25,
  84320,
  19645,
  128009,
  128006,
  882,
  128007,
  271,
  16509,
  596,
  8199,
  15455,
  527,
  65516,
  2785,
  5623,
  4947,
  28424,
  323,
  4846,
  3109,
  7510,
  13,
  128009,
  128006,
  78191,
  128007,
  271,
  16509,
  596,
  54184,
  2057,
  578,
  507,
  2554,
  590,
  69280,
  8274,
  25,
  24952,
  772,
  31969,
  11,
  40071,
  578,
  51859,
  128009],
 'attention_mask': [1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1]}

In [15]:
tokenizer.decode(tok_ds['train'][1]['input_ids'], skip_special_tokens=True), tok_ds['train'][1]['text']

("system\n\nCutting Knowledge Date: December 2023\nToday Date: 07 Apr 2026\n\nYou are a news headline generator who generates catchy news headline from given news summary.\nGenerate a headline for following news summary of type: POLITICSuser\n\nTrump's budget cuts are baffling drug policy advocates and former government officials.assistant\n\nTrump's Approach To The Opioid Epidemic: Neglect Treatment, Ignore The Experts",
 [{'content': 'You are a news headline generator who generates catchy news headline from given news summary.\nGenerate a headline for following news summary of type: POLITICS',
   'role': 'system'},
  {'content': "Trump's budget cuts are baffling drug policy advocates and former government officials.",
   'role': 'user'},
  {'content': "Trump's Approach To The Opioid Epidemic: Neglect Treatment, Ignore The Experts",
   'role': 'assistant'}])

In [16]:
tokenizer.decode(tok_ds['test'][1]['input_ids']), tok_ds['test'][1]['text_gen'], tok_ds['test'][1]['text']

('<|begin_of_text|><|start_header_id|>system<|end_header_id|>\n\nCutting Knowledge Date: December 2023\nToday Date: 07 Apr 2026\n\nYou are a news headline generator who generates catchy news headline from given news summary.\nGenerate a headline for following news summary of type: HEALTHY LIVING<|eot_id|><|start_header_id|>user<|end_header_id|>\n\nWhen we challenge ourselves to not "fat talk," we give an incredible gift to our daughters, our family members and our friends. Casually engaging in fat talk with our friends actually reinforces painful body shame and the dieting mind, despite our best intentions.<|eot_id|><|start_header_id|>assistant<|end_header_id|>\n\n',
 [{'content': 'You are a news headline generator who generates catchy news headline from given news summary.\nGenerate a headline for following news summary of type: HEALTHY LIVING',
   'role': 'system'},
  {'content': 'When we challenge ourselves to not "fat talk," we give an incredible gift to our daughters, our family members and our friends. Casually engaging in fat talk with our friends actually reinforces painful body shame and the dieting mind, despite our best intentions.',
   'role': 'user'}],
 [{'content': 'You are a news headline generator who generates catchy news headline from given news summary.\nGenerate a headline for following news summary of type: HEALTHY LIVING',
   'role': 'system'},
  {'content': 'When we challenge ourselves to not "fat talk," we give an incredible gift to our daughters, our family members and our friends. Casually engaging in fat talk with our friends actually reinforces painful body shame and the dieting mind, despite our best intentions.',
   'role': 'user'},
  {'content': 'The End of Fat Talk', 'role': 'assistant'}])

In [17]:
tokenizer.decode(tok_ds['test'][1]['input_ids'])

'<|begin_of_text|><|start_header_id|>system<|end_header_id|>\n\nCutting Knowledge Date: December 2023\nToday Date: 07 Apr 2026\n\nYou are a news headline generator who generates catchy news headline from given news summary.\nGenerate a headline for following news summary of type: HEALTHY LIVING<|eot_id|><|start_header_id|>user<|end_header_id|>\n\nWhen we challenge ourselves to not "fat talk," we give an incredible gift to our daughters, our family members and our friends. Casually engaging in fat talk with our friends actually reinforces painful body shame and the dieting mind, despite our best intentions.<|eot_id|><|start_header_id|>assistant<|end_header_id|>\n\n'

In [18]:
MAX_NEW_TOKENS = 40

In [19]:
def generate_config(MAX_NEW_TOKENS, temperature=0.6, top_p=0.5, top_k=3, do_sample=True, use_cache=False):
    generation_config = {
        "max_new_tokens": MAX_NEW_TOKENS,
        "temperature": temperature,           # Controls randomness (lower = more deterministic)
        "top_p": top_p,                 # Nucleus sampling for diversity
        "top_k": top_k,                  # Limits candidates per step
        "do_sample": do_sample,            # Enables stochastic sampling
        # Repetition control
        "repetition_penalty": 1.2,    # Penalizes repeated tokens
        # Efficiency / inference tuning
        "use_cache": use_cache,            # Cache KV states for faster decoding
        # Optional advanced knobs
        "min_new_tokens": 10,         # Guarantees some output
        "eos_token_id": tokenizer.eos_token_id,
        "pad_token_id": tokenizer.pad_token_id,

        }
    return generation_config

In [20]:
generation_args = generate_config(MAX_NEW_TOKENS)
generation_args

{'max_new_tokens': 40,
 'temperature': 0.6,
 'top_p': 0.5,
 'top_k': 3,
 'do_sample': True,
 'repetition_penalty': 1.2,
 'use_cache': False,
 'min_new_tokens': 10,
 'eos_token_id': 128009,
 'pad_token_id': 128009}

In [21]:
def base_format(sample):
    system_message = f'You are a news headline generator who generates catchy news headline from given news summary.\nGenerate a headline for following news summary of type: {sample["category"]}'
    messages = [
        {"role": 'system','content': system_message},
        {"role": 'user','content': sample["short_description"]},
        ]
    if generate_text:
        text_dict = {'text_gen': messages}
    else:
        messages.append({"role": 'assistant','content': sample["headline"]})
        text_dict = {'text': messages}
    return text_dict

In [22]:
def apply_chat_temp(example, generate_text=False):
    if generate_text:
        toks = tokenizer.apply_chat_template(example['text_gen'],tokenize=True, add_generation_prompt=True)
    else:
        toks = tokenizer.apply_chat_template(example['text'],tokenize=True)
    return toks

In [67]:
def cuda_warmup(model, toks, device, num_runs=5):
    for runs in range(num_runs):
        with torch.inference_mode():
            _ = model.generate(input_ids=toks, max_new_tokens=15)
        if device == "cuda":
            torch.cuda.synchronize()
    print("WarmUp runs completed")

In [68]:
import string

def remove_punctuation(text: str) -> str:
    # Create a translation table that maps punctuation to None
    translator = str.maketrans('', '', string.punctuation)
    return text.translate(translator)

In [69]:
def generate_headline(model, tokenizer, toks, device, generation_args):
    """TODO: Implement the headline generation and latency measurement logic."""
    t0 = time.perf_counter()
    with torch.inference_mode():
            outputs = model.generate(**toks, **generation_args)
    if device == 'cuda':
        torch.cuda.synchronize()
    t1 = time.perf_counter()
    latency = t1 - t0
    gen_len = outputs.shape[1] - toks["input_ids"].shape[1]
    peak_mem_mib = torch.cuda.max_memory_allocated(device) / 1024**2
    throughput = gen_len / latency if latency > 0 else float("nan")

    outputs_text = tokenizer.decode(outputs)
    outputs_text = remove_punctuation(outputs_text[0].split('<|start_header_id|>assistant<|end_header_id|>')[-1].split('<|eot_id|>')[0].strip())
    #print(outputs_text)
    peak_mem_mib = torch.cuda.max_memory_allocated(device) / 1024**2
    del model
    return latency, throughput, peak_mem_mib, outputs_text

In [70]:
def report_metrics(tok_ds, model, tokenizer, DEVICE, generation_args, exp, df):
    """TODO: Implement the logic for calculating and reporting all performance metrics."""
    avg_latency, avg_throughput, avg_peak_mib, rouge_score = evaluate_model(tok_ds, model, tokenizer, DEVICE, generation_args)
    new_df = pd.DataFrame({"EXP NAME": [exp], "Mean Latency (s)": [avg_latency], "Throughput (tokens/s)": [avg_throughput], "Avg Peak Mem": [avg_peak_mib], "ROUGE-1 Score": [rouge_score]}) 
    df = pd.concat([df, new_df], axis=0)
    return df

In [71]:
import random
import evaluate

In [72]:
def evaluate_model(dataset, model, tokenizer, device, generation_args, n=4):
    """TODO: Implement the model evaluation loop."""
    
    sample = random.sample(range(1000), 1)[0]
    warmup_example = dataset['train'][sample]
    toks = apply_chat_temp(warmup_example, generate_text=True)

    toks['input_ids'] = torch.tensor(toks['input_ids']).unsqueeze(0).to(device)
    toks['attention_mask'] = torch.tensor(toks['attention_mask']).unsqueeze(0).to(device)
    
    model.eval()
    cuda_warmup(model, toks['input_ids'], device)
    
    torch.cuda.reset_peak_memory_stats(device)
    samples = 100
    latencies = []
    throughputs = []
    peak_mem = []
    outputs = []
    references = []
    for i in range(n):
        for j in range(samples):
            sample = dataset['train'][j]
            references.append(sample['headline'])
            toks = apply_chat_temp(sample, generate_text=True)
            toks['input_ids'] = torch.tensor(toks['input_ids']).unsqueeze(0).to(model.device)
            toks['attention_mask'] = torch.tensor(toks['attention_mask']).unsqueeze(0).to(model.device)
            latency, throughput, peak_mem_mib, outputs_text = generate_headline(model, tokenizer, toks, device, generation_args)
            latencies.append(latency)
            throughputs.append(throughput)
            peak_mem.append(peak_mem_mib)
            outputs.append(outputs_text)
    
    rouge = evaluate.load("rouge")
    rouge_score = rouge.compute(predictions=outputs, references=references)['rouge1']
    avg_latency = sum(latencies) / len(latencies)
    avg_throughput = sum(throughputs) / len(throughputs)
    avg_peak_mib = sum(peak_mem)/len(peak_mem)
    print(avg_latency, avg_throughput, avg_peak_mib, rouge_score)
    return avg_latency, avg_throughput, avg_peak_mib, rouge_score

In [73]:
import copy
import torch.nn as nn
def prune_model_weights(model, amount=0.3):
    """TODO: Applies L1 unstructured pruning to the linear layers of a model."""
    pruned_model = copy.deepcopy(model)
    for name, module in pruned_model.named_modules():
        if isinstance(module, nn.Linear):
            prune.l1_unstructured(module, name="weight", amount=amount)
            prune.remove(module, "weight")
    print("Model pruned successfully")
    return pruned_model

In [74]:
# TODO: Establish your baseline performance.
#load the original model and establish baseline performance using functions defined above
def run_exp(exp, df, tok_ds, DEVICE, generation_args, quantization_config=None, prune=False, MODEL_NAME=MODEL_NAME ):

    tokenizer, model = load_model(MODEL_NAME, DEVICE, quantization_config=quantization_config)
    if prune:
        model = prune_model_weights(model, amount=0.3)        
    df = report_metrics(tok_ds, model, tokenizer, DEVICE, generation_args, exp, df)
    return df

In [75]:
from transformers import DataCollatorForLanguageModeling

In [32]:
from torch.utils.data import DataLoader
from transformers import DataCollatorWithPadding

tok_ds = tok_ds.map(lambda x: {'headline_ids': tokenizer(x['headline'], padding='max_length', truncation=True, max_length=40)['input_ids']})
tok_ds_train = tok_ds['train'].remove_columns(['headline', 'category', 'short_description', 'text', 'text_gen', 'attention_mask'])
tok_ds_train = tok_ds_train.select(range(400))

Map:   0%|          | 0/207431 [00:00<?, ? examples/s]

Map:   0%|          | 0/2096 [00:00<?, ? examples/s]

In [33]:
tok_ds_train

Dataset({
    features: ['input_ids', 'headline_ids'],
    num_rows: 400
})

In [34]:
data_collator_pad = DataCollatorForLanguageModeling(tokenizer, mlm=False) 
data_loader = DataLoader(
    tok_ds_train,
    batch_size=32,
    collate_fn=data_collator_pad
)
for step, batch in enumerate(data_loader):
    print(f"Batch {step}")
    print("input_ids.shape:", batch["input_ids"].shape)

    print("attention_mask.shape:", batch["attention_mask"].shape)
    print("headline_ids.shape:", batch["headline_ids"].shape)


    if step >= 3:
        break

Batch 0
input_ids.shape: torch.Size([32, 135])
attention_mask.shape: torch.Size([32, 135])
headline_ids.shape: torch.Size([32, 40])
Batch 1
input_ids.shape: torch.Size([32, 135])
attention_mask.shape: torch.Size([32, 135])
headline_ids.shape: torch.Size([32, 40])
Batch 2
input_ids.shape: torch.Size([32, 142])
attention_mask.shape: torch.Size([32, 142])
headline_ids.shape: torch.Size([32, 40])
Batch 3
input_ids.shape: torch.Size([32, 160])
attention_mask.shape: torch.Size([32, 160])
headline_ids.shape: torch.Size([32, 40])

In [35]:
batch["input_ids"]

tensor([[128009, 128009, 128009,  ...,    548,  31974, 128009],
        [128009, 128009, 128009,  ...,  38759,  76892, 128009],
        [128009, 128009, 128009,  ...,    596,  16290, 128009],
        ...,
        [128009, 128009, 128009,  ...,  32708,  47524, 128009],
        [128009, 128009, 128009,  ...,  28058,  71077, 128009],
        [128009, 128009, 128009,  ...,   7304,  63398, 128009]])

In [36]:
batch["attention_mask"]

tensor([[0, 0, 0,  ..., 1, 1, 1],
        [0, 0, 0,  ..., 1, 1, 1],
        [0, 0, 0,  ..., 1, 1, 1],
        ...,
        [0, 0, 0,  ..., 1, 1, 1],
        [0, 0, 0,  ..., 1, 1, 1],
        [0, 0, 0,  ..., 1, 1, 1]])

In [37]:
tok_ds, tok_ds_train

(DatasetDict({
     train: Dataset({
         features: ['headline', 'category', 'short_description', 'text', 'text_gen', 'input_ids', 'attention_mask', 'headline_ids'],
         num_rows: 207431
     })
     test: Dataset({
         features: ['headline', 'category', 'short_description', 'text', 'text_gen', 'input_ids', 'attention_mask', 'headline_ids'],
         num_rows: 2096
     })
 }),
 Dataset({
     features: ['input_ids', 'headline_ids'],
     num_rows: 400
 }))

In [76]:
def generate_headline_batch(model, tokenizer, device, generation_args, data_loader, exp, df):
    """TODO: Implement the headline generation and latency measurement logic."""
    for batch in data_loader:
        warmup_example = batch["input_ids"].to(device)
        model.eval()
        cuda_warmup(model, warmup_example, device)
        break
        
    torch.cuda.reset_peak_memory_stats(device)
    
    latencies_per_batch = []
    throughputs = []
    peak_mem = []
    batch_outputs = []
    references = []
    for step, batch in enumerate(data_loader):
        print(f"Batch {step}")
        #print("input_ids.shape:", batch["input_ids"].shape)
        #print("headline_ids.shape:", batch["headline_ids"].shape)       
        t0 = time.perf_counter()
        batch["input_ids"] = batch["input_ids"].to(model.device)
        batch['attention_mask'] = batch['attention_mask'].to(model.device)
        with torch.inference_mode():
            outputs = model.generate(input_ids=batch["input_ids"], attention_mask=batch['attention_mask'], **generation_args)
        if device == 'cuda':
            torch.cuda.synchronize()
        t1 = time.perf_counter()
        
        latency_per_batch = (t1 - t0)
        latencies_per_batch.append(latency_per_batch)

        peak_mem_mib = torch.cuda.max_memory_allocated(device) / 1024**2
        peak_mem.append(peak_mem_mib)
        
        inputs_decode = tokenizer.batch_decode(batch["input_ids"], skip_special_tokens=True)
        inputs_toks_len_list = [len(tokenizer.encode(inp)) for inp in inputs_decode]
        
        outputs_decode = tokenizer.batch_decode(outputs, skip_special_tokens=True)
        outputs_text = [remove_punctuation(out.split('assistant\n\n')[-1]) for out in outputs_decode]
        batch_outputs.extend(outputs_text)
        
        outputs_toks_len_list = [len(tokenizer.encode(out)) for out in outputs_decode]
        
        num_toks_gen = sum(np.array(outputs_toks_len_list) - np.array(inputs_toks_len_list))
        throughput = num_toks_gen / latency_per_batch if latency_per_batch > 0 else float("nan")
        throughputs.append(throughput)
        
        headline_decode = tokenizer.batch_decode(batch["headline_ids"], skip_special_tokens=True)
        references.extend(headline_decode)


    rouge = evaluate.load("rouge")
    rouge_score = rouge.compute(predictions=batch_outputs, references=references)['rouge1']
    
    avg_latency_per_batch = sum(latencies_per_batch) / len(latencies_per_batch)
    avg_latency_per_batch_item = sum(latencies_per_batch) / len(data_loader.dataset)
    
    avg_throughput = sum(throughputs) / len(throughputs)
    avg_peak_mib = sum(peak_mem)/len(peak_mem)
    
    print(avg_latency_per_batch, avg_latency_per_batch_item, avg_throughput, avg_peak_mib, rouge_score)
    
    new_df = pd.DataFrame({"EXP NAME": [exp], "Mean Latency (s)": [f"{round(avg_latency_per_batch, 2)}/{round(avg_latency_per_batch_item, 2)}"], "Throughput (tokens/s)": [round(avg_throughput,2)], "Avg Peak Mem": [round(avg_peak_mib, 2)], "ROUGE-1 Score": [round(rouge_score, 2)]}) 
    df = pd.concat([df, new_df], axis=0)
    
    return df

In [77]:
torch.cuda.empty_cache()
import gc
gc.collect()

6079

In [78]:
import warnings
warnings.filterwarnings("ignore", category=UserWarning)

In [41]:
df = pd.DataFrame()
exp = "Baseline (No Cache)"
df = run_exp(exp, df, tok_ds, DEVICE, generation_args, quantization_config=None, prune=False, MODEL_NAME=MODEL_NAME )

Loading tokenizer...
Tokenizer loaded successfully.

Loading model...

Loading weights:   0%|          | 0/146 [00:00<?, ?it/s]

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Model loaded successfully and moved to device.
Memory Footprint: 2357.13 MB

The attention mask is not set and cannot be inferred from input because pad token is same as eos token. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

WarmUp runs completed

Downloading builder script: 0.00B [00:00, ?B/s]

0.37946256138000395 70.71137348564321 4735.89486328125 0.09303135217696623

In [42]:
df

,EXP NAME,Mean Latency (s),Throughput (tokens/s),Avg Peak Mem,ROUGE-1 Score
0,Baseline (No Cache),0.379463,70.711373,4735.894863,0.093031

In [43]:
exp = f"Baseline (No Cache) Batch: {data_loader.batch_size}"
df = generate_headline_batch(model, tokenizer, DEVICE, generation_args, data_loader, exp, df)

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

WarmUp runs completed
Batch 0
Batch 1
Batch 2
Batch 3
Batch 4
Batch 5
Batch 6
Batch 7
Batch 8
Batch 9
Batch 10
Batch 11
Batch 12
9.069201825461558 0.2947490593275006 83.70202708490382 5165.905310997596 0.09974098237570672

In [44]:
df

,EXP NAME,Mean Latency (s),Throughput (tokens/s),Avg Peak Mem,ROUGE-1 Score
0,Baseline (No Cache),0.379463,70.711373,4735.894863,0.093031
0,Baseline (No Cache) Batch: 32,9.07/0.29,83.700000,5165.910000,0.100000

# 3. Architectural Optimization: KV Caching

**Your Task:** One of the most effective ways to speed up token generation is using a Key-Value (KV) cache. This avoids re-computing attention scores for tokens that are already part of the sequence. Enable the `use_cache` flag in the generation arguments and re-run the evaluation. Observe the impact on latency and throughput.

In [45]:
print(generation_args)
generation_args['use_cache'] = True
print(generation_args)

{'max_new_tokens': 40, 'temperature': 0.6, 'top_p': 0.5, 'top_k': 3, 'do_sample': True, 'repetition_penalty': 1.2, 'use_cache': False, 'min_new_tokens': 10, 'eos_token_id': 128009, 'pad_token_id': 128009}
{'max_new_tokens': 40, 'temperature': 0.6, 'top_p': 0.5, 'top_k': 3, 'do_sample': True, 'repetition_penalty': 1.2, 'use_cache': True, 'min_new_tokens': 10, 'eos_token_id': 128009, 'pad_token_id': 128009}

In [46]:
# TODO: Evaluate the model with KV Caching enabled.
exp = "KV Caching"
df = run_exp(exp, df, tok_ds, DEVICE, generation_args)

Loading tokenizer...
Tokenizer loaded successfully.

Loading model...

Loading weights:   0%|          | 0/146 [00:00<?, ?it/s]

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Model loaded successfully and moved to device.
Memory Footprint: 2357.13 MB

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

WarmUp runs completed
0.3801660053274935 69.92248636231434 7094.697354736328 0.09482820492615149

In [47]:
df

,EXP NAME,Mean Latency (s),Throughput (tokens/s),Avg Peak Mem,ROUGE-1 Score
0,Baseline (No Cache),0.379463,70.711373,4735.894863,0.093031
0,Baseline (No Cache) Batch: 32,9.07/0.29,83.700000,5165.910000,0.100000
0,KV Caching,0.380166,69.922486,7094.697355,0.094828

In [48]:
exp = f"KV Caching Batch: {data_loader.batch_size}"
df = generate_headline_batch(model, tokenizer, DEVICE, generation_args, data_loader, exp, df)

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

WarmUp runs completed
Batch 0
Batch 1
Batch 2
Batch 3
Batch 4
Batch 5
Batch 6
Batch 7
Batch 8
Batch 9
Batch 10
Batch 11
Batch 12
0.9408595432307545 0.030577935154999524 795.0897793328035 5197.504244290865 0.10279120658710794

In [49]:
df

,EXP NAME,Mean Latency (s),Throughput (tokens/s),Avg Peak Mem,ROUGE-1 Score
0,Baseline (No Cache),0.379463,70.711373,4735.894863,0.093031
0,Baseline (No Cache) Batch: 32,9.07/0.29,83.700000,5165.910000,0.100000
0,KV Caching,0.380166,69.922486,7094.697355,0.094828
0,KV Caching Batch: 32,0.94/0.03,795.090000,5197.500000,0.100000

# 4. Model Compression: Pruning

**Your Task:** Pruning removes redundant model weights, which can reduce model size and potentially speed up inference. Here, you will implement unstructured, magnitude-based pruning by creating a function that applies it to the model's linear layers and then evaluating the result.

In [50]:


# TODO: Evaluate the pruned model.
##Run pruned model evaluation

In [51]:
exp = "Pruning (30%)"
df = run_exp(exp, df, tok_ds, DEVICE, generation_args, quantization_config=None, prune=True )

Loading tokenizer...
Tokenizer loaded successfully.

Loading model...

Loading weights:   0%|          | 0/146 [00:00<?, ?it/s]

Model loaded successfully and moved to device.
Memory Footprint: 2357.13 MB

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Model pruned successfully

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

WarmUp runs completed
0.4764006964599969 68.21135381518994 7094.718452148438 0.0752528777881206

In [52]:
df

,EXP NAME,Mean Latency (s),Throughput (tokens/s),Avg Peak Mem,ROUGE-1 Score
0,Baseline (No Cache),0.379463,70.711373,4735.894863,0.093031
0,Baseline (No Cache) Batch: 32,9.07/0.29,83.700000,5165.910000,0.100000
0,KV Caching,0.380166,69.922486,7094.697355,0.094828
0,KV Caching Batch: 32,0.94/0.03,795.090000,5197.500000,0.100000
0,Pruning (30%),0.476401,68.211354,7094.718452,0.075253

In [53]:
pruned_model = prune_model_weights(model, amount=0.3)

Model pruned successfully

In [54]:
exp = f"Pruning (30%) Batch: {data_loader.batch_size}"
df = generate_headline_batch(pruned_model, tokenizer, DEVICE, generation_args, data_loader, exp, df)

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

WarmUp runs completed
Batch 0
Batch 1
Batch 2
Batch 3
Batch 4
Batch 5
Batch 6
Batch 7
Batch 8
Batch 9
Batch 10
Batch 11
Batch 12
0.9727589330769626 0.03161466532500128 800.7314759985153 7556.62255859375 0.12793092427958222

In [55]:
df

,EXP NAME,Mean Latency (s),Throughput (tokens/s),Avg Peak Mem,ROUGE-1 Score
0,Baseline (No Cache),0.379463,70.711373,4735.894863,0.093031
0,Baseline (No Cache) Batch: 32,9.07/0.29,83.700000,5165.910000,0.100000
0,KV Caching,0.380166,69.922486,7094.697355,0.094828
0,KV Caching Batch: 32,0.94/0.03,795.090000,5197.500000,0.100000
0,Pruning (30%),0.476401,68.211354,7094.718452,0.075253
0,Pruning (30%) Batch: 32,0.97/0.03,800.730000,7556.620000,0.130000

# 5. Model Compression: Quantization

**Your Task:** Quantization reduces the precision of model weights (e.g., from 16-bit to 4-bit), significantly cutting down memory usage and often speeding up inference. You will define a 4-bit quantization configuration and use it to load and evaluate a new model.

In [56]:
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True, 
    bnb_4bit_quant_type="nf4", 
    bnb_4bit_compute_dtype=torch.bfloat16 
    )

In [57]:
# TODO: Implement and evaluate 4-bit quantization.
exp = "Quantization (4-bit)"
df = run_exp(exp, df, tok_ds, DEVICE, generation_args, quantization_config=bnb_config)

Loading tokenizer...
Tokenizer loaded successfully.

Loading model...

/home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/torch/cuda/__init__.py:61: FutureWarning: The pynvml package is deprecated. Please install nvidia-ml-py instead. If you did not install pynvml directly, please report this to the maintainers of the package that installed pynvml for you.
  import pynvml  # type: ignore[import]

Loading weights:   0%|          | 0/146 [00:00<?, ?it/s]

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Model loaded successfully and moved to device.
Memory Footprint: 965.13 MB

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

WarmUp runs completed
0.5467937357949978 47.85095464481796 8148.832456054687 0.07985275131213757

In [58]:
df

,EXP NAME,Mean Latency (s),Throughput (tokens/s),Avg Peak Mem,ROUGE-1 Score
0,Baseline (No Cache),0.379463,70.711373,4735.894863,0.093031
0,Baseline (No Cache) Batch: 32,9.07/0.29,83.700000,5165.910000,0.100000
0,KV Caching,0.380166,69.922486,7094.697355,0.094828
0,KV Caching Batch: 32,0.94/0.03,795.090000,5197.500000,0.100000
0,Pruning (30%),0.476401,68.211354,7094.718452,0.075253
0,Pruning (30%) Batch: 32,0.97/0.03,800.730000,7556.620000,0.130000
0,Quantization (4-bit),0.546794,47.850955,8148.832456,0.079853

In [59]:
_, quant_model = load_model(MODEL_NAME, DEVICE, quantization_config=bnb_config)

Loading tokenizer...
Tokenizer loaded successfully.

Loading model...

Loading weights:   0%|          | 0/146 [00:00<?, ?it/s]

Model loaded successfully and moved to device.
Memory Footprint: 965.13 MB

In [60]:
exp = f"Quantization (4-bit) Batch: {data_loader.batch_size}"
df = generate_headline_batch(quant_model, tokenizer, DEVICE, generation_args, data_loader, exp, df)

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

WarmUp runs completed
Batch 0
Batch 1
Batch 2
Batch 3
Batch 4
Batch 5
Batch 6
Batch 7
Batch 8
Batch 9
Batch 10
Batch 11
Batch 12
1.4363998452308107 0.04668299497000135 468.50531601961416 9100.79657451923 0.09124335991548946

In [61]:
df

,EXP NAME,Mean Latency (s),Throughput (tokens/s),Avg Peak Mem,ROUGE-1 Score
0,Baseline (No Cache),0.379463,70.711373,4735.894863,0.093031
0,Baseline (No Cache) Batch: 32,9.07/0.29,83.700000,5165.910000,0.100000
0,KV Caching,0.380166,69.922486,7094.697355,0.094828
0,KV Caching Batch: 32,0.94/0.03,795.090000,5197.500000,0.100000
0,Pruning (30%),0.476401,68.211354,7094.718452,0.075253
0,Pruning (30%) Batch: 32,0.97/0.03,800.730000,7556.620000,0.130000
0,Quantization (4-bit),0.546794,47.850955,8148.832456,0.079853
0,Quantization (4-bit) Batch: 32,1.44/0.05,468.510000,9100.800000,0.090000

In [62]:
##Run quantized model experiments here

# 6. Distributed Inference (Multi-GPU)

**Your Task:** If you have multiple GPUs, you can split the model across them to reduce the memory burden on a single GPU and potentially improve latency. We will explore two common techniques: Tensor Parallelism and Pipeline Parallelism.

*Note: This section requires a multi-GPU environment.*

### Tensor Parallelism
Tensor parallelism splits individual model layers (the tensors) across multiple GPUs. Operations like matrix multiplications are executed in parallel on different GPUs, and the results are aggregated. This is highly effective for reducing the memory footprint of very large layers. The `accelerate` library can handle this automatically via `device_map="auto"`.

### Pipeline Parallelism
Pipeline parallelism assigns entire layers or blocks of layers to different GPUs, creating a sequence or "pipeline" that the data flows through. For example, layers 1-10 run on GPU 0, layers 11-20 run on GPU 1, and so on. This is useful for very deep models where even a single layer might be too large for one GPU after tensor parallelism.

In [47]:
# TODO: Check for multi-GPU environment and evaluate with Tensor Parallelism.
# The `device_map="auto"` in your `load_model` function should automatically apply this.

In [48]:
# TODO: Evaluate with Pipeline Parallelism.
# This is more advanced and may require manually defining a device_map to assign
# different layers of the model to different GPUs.

In [86]:
generation_args['use_cache'] = True
print(generation_args)

{'max_new_tokens': 40, 'temperature': 0.6, 'top_p': 0.5, 'top_k': 3, 'do_sample': True, 'repetition_penalty': 1.2, 'use_cache': True, 'min_new_tokens': 10, 'eos_token_id': 128009, 'pad_token_id': 128009}

In [87]:
df = pd.DataFrame()
exp = "Model Parallelism 4 GPU accelerate balanced"

In [88]:
MODEL_NAME, DEVICE

('meta-llama/Llama-3.2-1B-Instruct', 'cuda')

In [89]:
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    torch_dtype=torch.float16,
    device_map= "balanced",
    trust_remote_code =True
    )

Loading weights:   0%|          | 0/146 [00:00<?, ?it/s]

In [90]:
model.hf_device_map

{'model.embed_tokens': 0,
 'lm_head': 0,
 'model.layers.0': 0,
 'model.layers.1': 1,
 'model.layers.2': 1,
 'model.layers.3': 1,
 'model.layers.4': 1,
 'model.layers.5': 1,
 'model.layers.6': 1,
 'model.layers.7': 2,
 'model.layers.8': 2,
 'model.layers.9': 2,
 'model.layers.10': 2,
 'model.layers.11': 2,
 'model.layers.12': 2,
 'model.layers.13': 3,
 'model.layers.14': 3,
 'model.layers.15': 3,
 'model.norm': 3,
 'model.rotary_emb': 3}

In [91]:
df = report_metrics(tok_ds, model, tokenizer, DEVICE, generation_args, exp, df)

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

WarmUp runs completed
0.77337274920499 34.807430717753604 2492.400595703125 0.09666186287739034

In [92]:
df

,EXP NAME,Mean Latency (s),Throughput (tokens/s),Avg Peak Mem,ROUGE-1 Score
0,Model Parallelism 4 GPU accelerate balanced,0.773373,34.807431,2492.400596,0.096662

In [93]:
exp = "Model Parallelism 4 GPU accelerate balanced	Batch: {data_loader.batch_size}"
df = generate_headline_batch(model, tokenizer, DEVICE, generation_args, data_loader, exp, df)

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

WarmUp runs completed
Batch 0
Batch 1
Batch 2
Batch 3
Batch 4
Batch 5
Batch 6
Batch 7
Batch 8
Batch 9
Batch 10
Batch 11
Batch 12
1.7719759749229875 0.05758921918499709 424.4738036075453 2784.9998497596152 0.10426039497376557

In [94]:
df

,EXP NAME,Mean Latency (s),Throughput (tokens/s),Avg Peak Mem,ROUGE-1 Score
0,Model Parallelism 4 GPU accelerate balanced,0.773373,34.807431,2492.400596,0.096662
0,Model Parallelism 4 GPU accelerate balanced\tB...,1.77/0.06,424.470000,2785.000000,0.100000

In [95]:
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    torch_dtype=torch.float16,
    device_map= "auto",
    trust_remote_code =True
    )

Loading weights:   0%|          | 0/146 [00:00<?, ?it/s]

In [96]:
model.hf_device_map

{'model.embed_tokens': 0,
 'lm_head': 0,
 'model.layers.0': 0,
 'model.layers.1': 1,
 'model.layers.2': 1,
 'model.layers.3': 1,
 'model.layers.4': 1,
 'model.layers.5': 1,
 'model.layers.6': 1,
 'model.layers.7': 2,
 'model.layers.8': 2,
 'model.layers.9': 2,
 'model.layers.10': 2,
 'model.layers.11': 2,
 'model.layers.12': 2,
 'model.layers.13': 3,
 'model.layers.14': 3,
 'model.layers.15': 3,
 'model.norm': 3,
 'model.rotary_emb': 3}

In [97]:
exp = "Tensor Parallelism 4 GPU accelerate auto"
df = report_metrics(tok_ds, model, tokenizer, DEVICE, generation_args, exp, df)

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

WarmUp runs completed
0.7723638838525357 34.546899096781125 3111.2793627929686 0.09653613640377794

In [98]:
df

,EXP NAME,Mean Latency (s),Throughput (tokens/s),Avg Peak Mem,ROUGE-1 Score
0,Model Parallelism 4 GPU accelerate balanced,0.773373,34.807431,2492.400596,0.096662
0,Model Parallelism 4 GPU accelerate balanced\tB...,1.77/0.06,424.470000,2785.000000,0.100000
0,Tensor Parallelism 4 GPU accelerate auto,0.772364,34.546899,3111.279363,0.096536

In [99]:
exp = "Tensor Parallelism 4 GPU accelerate auto Batch: {data_loader.batch_size}"
df = generate_headline_batch(model, tokenizer, DEVICE, generation_args, data_loader, exp, df)

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

WarmUp runs completed
Batch 0
Batch 1
Batch 2
Batch 3
Batch 4
Batch 5
Batch 6
Batch 7
Batch 8
Batch 9
Batch 10
Batch 11
Batch 12
1.788086560999895 0.05811281323249659 418.01402246922464 3403.0079251802886 0.10323908876105858

In [100]:
df

,EXP NAME,Mean Latency (s),Throughput (tokens/s),Avg Peak Mem,ROUGE-1 Score
0,Model Parallelism 4 GPU accelerate balanced,0.773373,34.807431,2492.400596,0.096662
0,Model Parallelism 4 GPU accelerate balanced\tB...,1.77/0.06,424.470000,2785.000000,0.100000
0,Tensor Parallelism 4 GPU accelerate auto,0.772364,34.546899,3111.279363,0.096536
0,Tensor Parallelism 4 GPU accelerate auto Batch...,1.79/0.06,418.010000,3403.010000,0.100000

In [101]:
#Just trying a combination that just crossed my mind

In [102]:
from accelerate import Accelerator 
accelerator = Accelerator(device_placement=True)

In [103]:
model, data_loader = accelerator.prepare(model, data_loader)

In [107]:
exp = "Tensor Parallelism 4 GPU accelerate prepare auto EXP1 Batch: {data_loader.batch_size}"
df = generate_headline_batch(model, tokenizer, DEVICE, generation_args, data_loader, exp, df)

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

WarmUp runs completed
Batch 0
Batch 1
Batch 2
Batch 3
Batch 4
Batch 5
Batch 6
Batch 7
Batch 8
Batch 9
Batch 10
Batch 11
Batch 12
1.7753993256153011 0.057700478082497286 422.787310196702 3403.055626502404 0.10514917648015201

In [108]:
df

,EXP NAME,Mean Latency (s),Throughput (tokens/s),Avg Peak Mem,ROUGE-1 Score
0,Model Parallelism 4 GPU accelerate balanced,0.773373,34.807431,2492.400596,0.096662
0,Model Parallelism 4 GPU accelerate balanced\tB...,1.77/0.06,424.470000,2785.000000,0.100000
0,Tensor Parallelism 4 GPU accelerate auto,0.772364,34.546899,3111.279363,0.096536
0,Tensor Parallelism 4 GPU accelerate auto Batch...,1.79/0.06,418.010000,3403.010000,0.100000
0,Tensor Parallelism 4 GPU accelerate prepare au...,1.78/0.06,422.790000,3403.060000,0.110000

In [109]:
def generate_headline_batch_accelerate(model, tokenizer, device, generation_args, data_loader, exp, df):
    """TODO: Implement the headline generation and latency measurement logic."""
    for batch in data_loader:
        warmup_example = batch["input_ids"].to(device)
        model.eval()
        cuda_warmup(model, warmup_example, device)
        break
        
    torch.cuda.reset_peak_memory_stats(device)
    
    latencies_per_batch = []
    throughputs = []
    peak_mem = []
    batch_outputs = []
    references = []
    for step, batch in enumerate(data_loader):
        print(f"Batch {step}")
        #print("input_ids.shape:", batch["input_ids"].shape)
        #print("headline_ids.shape:", batch["headline_ids"].shape)       
        t0 = time.perf_counter()
        #batch["input_ids"] = batch["input_ids"].to(model.device)
        #batch['attention_mask'] = batch['attention_mask'].to(model.device)
        with torch.inference_mode():
            outputs = model.generate(input_ids=batch["input_ids"], attention_mask=batch['attention_mask'], **generation_args)
        if device == 'cuda':
            torch.cuda.synchronize()
        t1 = time.perf_counter()
        
        latency_per_batch = (t1 - t0)
        latencies_per_batch.append(latency_per_batch)

        peak_mem_mib = torch.cuda.max_memory_allocated(device) / 1024**2
        peak_mem.append(peak_mem_mib)
        
        inputs_decode = tokenizer.batch_decode(batch["input_ids"], skip_special_tokens=True)
        inputs_toks_len_list = [len(tokenizer.encode(inp)) for inp in inputs_decode]
        
        outputs_decode = tokenizer.batch_decode(outputs, skip_special_tokens=True)
        outputs_text = [remove_punctuation(out.split('assistant\n\n')[-1]) for out in outputs_decode]
        batch_outputs.extend(outputs_text)
        
        outputs_toks_len_list = [len(tokenizer.encode(out)) for out in outputs_decode]
        
        num_toks_gen = sum(np.array(outputs_toks_len_list) - np.array(inputs_toks_len_list))
        throughput = num_toks_gen / latency_per_batch if latency_per_batch > 0 else float("nan")
        throughputs.append(throughput)
        
        headline_decode = tokenizer.batch_decode(batch["headline_ids"], skip_special_tokens=True)
        references.extend(headline_decode)


    rouge = evaluate.load("rouge")
    rouge_score = rouge.compute(predictions=batch_outputs, references=references)['rouge1']
    
    avg_latency_per_batch = sum(latencies_per_batch) / len(latencies_per_batch)
    avg_latency_per_batch_item = sum(latencies_per_batch) / len(data_loader.dataset)
    
    avg_throughput = sum(throughputs) / len(throughputs)
    avg_peak_mib = sum(peak_mem)/len(peak_mem)
    
    print(avg_latency_per_batch, avg_latency_per_batch_item, avg_throughput, avg_peak_mib, rouge_score)
    
    new_df = pd.DataFrame({"EXP NAME": [exp], "Mean Latency (s)": [f"{round(avg_latency_per_batch, 2)}/{round(avg_latency_per_batch_item, 2)}"], "Throughput (tokens/s)": [round(avg_throughput,2)], "Avg Peak Mem": [round(avg_peak_mib, 2)], "ROUGE-1 Score": [round(rouge_score, 2)]}) 
    df = pd.concat([df, new_df], axis=0)
    
    return df

In [110]:
exp = "Tensor Parallelism 4 GPU accelerate prepare auto EXP2 Batch: {data_loader.batch_size}"
df = generate_headline_batch_accelerate(model, tokenizer, DEVICE, generation_args, data_loader, exp, df)

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

WarmUp runs completed
Batch 0
Batch 1
Batch 2
Batch 3
Batch 4
Batch 5
Batch 6
Batch 7
Batch 8
Batch 9
Batch 10
Batch 11
Batch 12
1.7619297156153642 0.05726271575749933 421.8756953514963 3403.0555889423076 0.10097794630521731

In [111]:
df

,EXP NAME,Mean Latency (s),Throughput (tokens/s),Avg Peak Mem,ROUGE-1 Score
0,Model Parallelism 4 GPU accelerate balanced,0.773373,34.807431,2492.400596,0.096662
0,Model Parallelism 4 GPU accelerate balanced\tB...,1.77/0.06,424.470000,2785.000000,0.100000
0,Tensor Parallelism 4 GPU accelerate auto,0.772364,34.546899,3111.279363,0.096536
0,Tensor Parallelism 4 GPU accelerate auto Batch...,1.79/0.06,418.010000,3403.010000,0.100000
0,Tensor Parallelism 4 GPU accelerate prepare au...,1.78/0.06,422.790000,3403.060000,0.110000
0,Tensor Parallelism 4 GPU accelerate prepare au...,1.76/0.06,421.880000,3403.060000,0.100000

In [113]:
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    torch_dtype=torch.float16,
    device_map= "balanced",
    trust_remote_code =True
    )
model, data_loader = accelerator.prepare(model, data_loader)

Loading weights:   0%|          | 0/146 [00:00<?, ?it/s]

In [114]:
exp = "Model Parallelism 4 GPU accelerate balanced prepare EXP2	Batch: {data_loader.batch_size}"
df = generate_headline_batch_accelerate(model, tokenizer, DEVICE, generation_args, data_loader, exp, df)

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

WarmUp runs completed
Batch 0
Batch 1
Batch 2
Batch 3
Batch 4
Batch 5
Batch 6
Batch 7
Batch 8
Batch 9
Batch 10
Batch 11
Batch 12
1.7832057707692002 0.05795418754999901 416.362450536405 4638.052020733173 0.10676473141672746

In [115]:
df

,EXP NAME,Mean Latency (s),Throughput (tokens/s),Avg Peak Mem,ROUGE-1 Score
0,Model Parallelism 4 GPU accelerate balanced,0.773373,34.807431,2492.400596,0.096662
0,Model Parallelism 4 GPU accelerate balanced\tB...,1.77/0.06,424.470000,2785.000000,0.100000
0,Tensor Parallelism 4 GPU accelerate auto,0.772364,34.546899,3111.279363,0.096536
0,Tensor Parallelism 4 GPU accelerate auto Batch...,1.79/0.06,418.010000,3403.010000,0.100000
0,Tensor Parallelism 4 GPU accelerate prepare au...,1.78/0.06,422.790000,3403.060000,0.110000
0,Tensor Parallelism 4 GPU accelerate prepare au...,1.76/0.06,421.880000,3403.060000,0.100000
0,Model Parallelism 4 GPU accelerate balanced pr...,1.78/0.06,416.360000,4638.050000,0.110000

In [116]:
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    #torch_dtype=torch.float16,
    #device_map= "balanced",
    trust_remote_code =True
    )
model, data_loader = accelerator.prepare(model, data_loader)

Loading weights:   0%|          | 0/146 [00:00<?, ?it/s]

In [117]:
exp = "Model Parallelism 4 GPU accelerate balanced prepare EXP3	Batch: {data_loader.batch_size}"
df = generate_headline_batch_accelerate(model, tokenizer, DEVICE, generation_args, data_loader, exp, df)

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

WarmUp runs completed
Batch 0
Batch 1
Batch 2
Batch 3
Batch 4
Batch 5
Batch 6
Batch 7
Batch 8
Batch 9
Batch 10
Batch 11
Batch 12
7.543203985384585 0.24515412952499901 100.10871126764692 7340.900540865385 0.10687817172434586

In [118]:
df

,EXP NAME,Mean Latency (s),Throughput (tokens/s),Avg Peak Mem,ROUGE-1 Score
0,Model Parallelism 4 GPU accelerate balanced,0.773373,34.807431,2492.400596,0.096662
0,Model Parallelism 4 GPU accelerate balanced\tB...,1.77/0.06,424.470000,2785.000000,0.100000
0,Tensor Parallelism 4 GPU accelerate auto,0.772364,34.546899,3111.279363,0.096536
0,Tensor Parallelism 4 GPU accelerate auto Batch...,1.79/0.06,418.010000,3403.010000,0.100000
0,Tensor Parallelism 4 GPU accelerate prepare au...,1.78/0.06,422.790000,3403.060000,0.110000
0,Tensor Parallelism 4 GPU accelerate prepare au...,1.76/0.06,421.880000,3403.060000,0.100000
0,Model Parallelism 4 GPU accelerate balanced pr...,1.78/0.06,416.360000,4638.050000,0.110000
0,Model Parallelism 4 GPU accelerate balanced pr...,7.54/0.25,100.110000,7340.900000,0.110000

In [119]:
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    torch_dtype=torch.float16,
    #device_map= "balanced",
    trust_remote_code =True
    )
model, data_loader = accelerator.prepare(model, data_loader)

Loading weights:   0%|          | 0/146 [00:00<?, ?it/s]

In [120]:
exp = "Model Parallelism 4 GPU accelerate balanced prepare EXP4	Batch: {data_loader.batch_size}"
df = generate_headline_batch_accelerate(model, tokenizer, DEVICE, generation_args, data_loader, exp, df)

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

WarmUp runs completed
Batch 0
Batch 1
Batch 2
Batch 3
Batch 4
Batch 5
Batch 6
Batch 7
Batch 8
Batch 9
Batch 10
Batch 11
Batch 12
1.7702531956153438 0.05753322885749867 423.69737460402183 9523.74560546875 0.09942826897692973

In [121]:
df

,EXP NAME,Mean Latency (s),Throughput (tokens/s),Avg Peak Mem,ROUGE-1 Score
0,Model Parallelism 4 GPU accelerate balanced,0.773373,34.807431,2492.400596,0.096662
0,Model Parallelism 4 GPU accelerate balanced\tB...,1.77/0.06,424.470000,2785.000000,0.100000
0,Tensor Parallelism 4 GPU accelerate auto,0.772364,34.546899,3111.279363,0.096536
0,Tensor Parallelism 4 GPU accelerate auto Batch...,1.79/0.06,418.010000,3403.010000,0.100000
0,Tensor Parallelism 4 GPU accelerate prepare au...,1.78/0.06,422.790000,3403.060000,0.110000
0,Tensor Parallelism 4 GPU accelerate prepare au...,1.76/0.06,421.880000,3403.060000,0.100000
0,Model Parallelism 4 GPU accelerate balanced pr...,1.78/0.06,416.360000,4638.050000,0.110000
0,Model Parallelism 4 GPU accelerate balanced pr...,7.54/0.25,100.110000,7340.900000,0.110000
0,Model Parallelism 4 GPU accelerate balanced pr...,1.77/0.06,423.700000,9523.750000,0.100000

In [122]:
df.to_csv("model_tensor_parallel_exp.csv")

### DeepSpeed Pipeline Parallelism

In [124]:
!pip install deepspeed==0.17.2

Collecting deepspeed==0.17.2
  Downloading deepspeed-0.17.2.tar.gz (1.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 83.1 MB/s  0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting einops (from deepspeed==0.17.2)
  Downloading einops-0.8.2-py3-none-any.whl.metadata (13 kB)
Collecting hjson (from deepspeed==0.17.2)
  Downloading hjson-3.1.0-py3-none-any.whl.metadata (2.6 kB)
Collecting msgpack (from deepspeed==0.17.2)
  Downloading msgpack-1.1.2-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (8.1 kB)
Collecting ninja (from deepspeed==0.17.2)
  Downloading ninja-1.13.0-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (5.1 kB)
Requirement already satisfied: numpy in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from deepspeed==0.17.2) (1.26.4)
Requirement already satisfied: packaging>=20.0 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from deepspeed==0.17.2) (24.2)
Requirement already satisfied: psutil in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from deepspeed==0.17.2) (7.2.2)
Collecting py-cpuinfo (from deepspeed==0.17.2)
  Downloading py_cpuinfo-9.0.0-py3-none-any.whl.metadata (794 bytes)
Requirement already satisfied: pydantic>=2.0.0 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from deepspeed==0.17.2) (2.9.2)
Requirement already satisfied: torch in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from deepspeed==0.17.2) (2.6.0+cu124)
Requirement already satisfied: tqdm in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from deepspeed==0.17.2) (4.67.3)
Requirement already satisfied: annotated-types>=0.6.0 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from pydantic>=2.0.0->deepspeed==0.17.2) (0.7.0)
Requirement already satisfied: pydantic-core==2.23.4 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from pydantic>=2.0.0->deepspeed==0.17.2) (2.23.4)
Requirement already satisfied: typing-extensions>=4.6.1 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from pydantic>=2.0.0->deepspeed==0.17.2) (4.15.0)
Requirement already satisfied: filelock in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from torch->deepspeed==0.17.2) (3.25.2)
Requirement already satisfied: networkx in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from torch->deepspeed==0.17.2) (3.4.2)
Requirement already satisfied: jinja2 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from torch->deepspeed==0.17.2) (3.1.6)
Requirement already satisfied: fsspec in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from torch->deepspeed==0.17.2) (2024.12.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.4.127 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from torch->deepspeed==0.17.2) (12.4.127)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.4.127 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from torch->deepspeed==0.17.2) (12.4.127)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.4.127 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from torch->deepspeed==0.17.2) (12.4.127)
Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from torch->deepspeed==0.17.2) (9.1.0.70)
Requirement already satisfied: nvidia-cublas-cu12==12.4.5.8 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from torch->deepspeed==0.17.2) (12.4.5.8)
Requirement already satisfied: nvidia-cufft-cu12==11.2.1.3 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from torch->deepspeed==0.17.2) (11.2.1.3)
Requirement already satisfied: nvidia-curand-cu12==10.3.5.147 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from torch->deepspeed==0.17.2) (10.3.5.147)
Requirement already satisfied: nvidia-cusolver-cu12==11.6.1.9 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from torch->deepspeed==0.17.2) (11.6.1.9)
Requirement already satisfied: nvidia-cusparse-cu12==12.3.1.170 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from torch->deepspeed==0.17.2) (12.3.1.170)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.2 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from torch->deepspeed==0.17.2) (0.6.2)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from torch->deepspeed==0.17.2) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from torch->deepspeed==0.17.2) (12.4.127)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.4.127 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from torch->deepspeed==0.17.2) (12.4.127)
Requirement already satisfied: triton==3.2.0 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from torch->deepspeed==0.17.2) (3.2.0)
Requirement already satisfied: sympy==1.13.1 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from torch->deepspeed==0.17.2) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from sympy==1.13.1->torch->deepspeed==0.17.2) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages (from jinja2->torch->deepspeed==0.17.2) (3.0.3)
Downloading einops-0.8.2-py3-none-any.whl (65 kB)
Downloading hjson-3.1.0-py3-none-any.whl (54 kB)
Downloading msgpack-1.1.2-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (406 kB)
Downloading ninja-1.13.0-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (180 kB)
Downloading py_cpuinfo-9.0.0-py3-none-any.whl (22 kB)
Building wheels for collected packages: deepspeed
  Building wheel for deepspeed (pyproject.toml) ... done
  Created wheel for deepspeed: filename=deepspeed-0.17.2-py3-none-any.whl size=1699839 sha256=70c1bd3160fb9c7d100307cce3340c684583e1998639caa9a0caa95995453c20
  Stored in directory: /home/ec2-user/.cache/pip/wheels/aa/90/50/536155ec6a2eb601f3052cfe5cab26cbb88f4a012c99566400
Successfully built deepspeed
Installing collected packages: py-cpuinfo, hjson, ninja, msgpack, einops, deepspeed
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6/6 [deepspeed]/6 [deepspeed]
Successfully installed deepspeed-0.17.2 einops-0.8.2 hjson-3.1.0 msgpack-1.1.2 ninja-1.13.0 py-cpuinfo-9.0.0

In [1]:
import deepspeed

/home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/torch/cuda/__init__.py:61: FutureWarning: The pynvml package is deprecated. Please install nvidia-ml-py instead. If you did not install pynvml directly, please report this to the maintainers of the package that installed pynvml for you.
  import pynvml  # type: ignore[import]

[2026-04-07 03:20:21,375] [INFO] [real_accelerator.py:254:get_accelerator] Setting ds_accelerator to cuda (auto detect)

/home/ec2-user/anaconda3/envs/pytorch_p310/compiler_compat/ld: cannot find -laio: No such file or directory
collect2: error: ld returned 1 exit status
/home/ec2-user/anaconda3/envs/pytorch_p310/compiler_compat/ld: cannot find -laio: No such file or directory
collect2: error: ld returned 1 exit status
/home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/pydantic/_internal/_fields.py:132: UserWarning: Field "model_name" in PromptModelConfig has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(

[2026-04-07 03:20:29,803] [INFO] [logging.py:107:log_dist] [Rank -1] [TorchCheckpointEngine] Initialized with serialization = False

/home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/torch/cuda/__init__.py:61: FutureWarning: The pynvml package is deprecated. Please install nvidia-ml-py instead. If you did not install pynvml directly, please report this to the maintainers of the package that installed pynvml for you.
  import pynvml  # type: ignore[import]

In [2]:
deepspeed.__version__

'0.17.2'

In [1]:
%%writefile parallel_pipeline_script.py

import os
import torch
import pandas as pd
import numpy as np
from datasets import load_dataset, Dataset
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig
from evaluate import load as load_metric
import time
from pprint import pprint
import torch.nn.utils.prune as prune
from transformers import pipeline
import torch.nn as nn
import deepspeed
import argparse
import accelerate
from huggingface_hub import login

##Load dataset
def load_news_dataset():
    """TODO: Implement the data loading and preprocessing logic here."""
    import kagglehub
    # Download latest version
    path = kagglehub.dataset_download("rmisra/news-category-dataset")
    print("Path to dataset files:", path)
    import pandas as pd
    df = pd.read_json(path+'/News_Category_Dataset_v3.json', lines = True)
    print(f'Number of news items in each category\n####################################\n{df["category"].value_counts()}')
    print(f'###########################################################')
    print(f'Total number of news categories in dataset: {len(pd.DataFrame(df["category"].value_counts()))}')
    print(f'###########################################################')
    df_1 = df[['headline', 'category', 'short_description']].copy()
    news_ds = Dataset.from_pandas(df_1)
    #print(news_ds)
    return news_ds
    
##news_ds = load_news_dataset()

#from huggingface_hub import login
#login("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")

def get_model_memory_footprint(model):
    """Calculates and returns the model's memory footprint in MB."""
    mem_params = sum(param.nelement() * param.element_size() for param in model.parameters())
    mem_bufs = sum(buf.nelement() * buf.element_size() for buf in model.buffers())
    total_mem_bytes = mem_params + mem_bufs
    return total_mem_bytes / (1024 ** 2) # Convert bytes to MB

def load_model(MODEL_NAME, DEVICE, quantization_config=None):
    """TODO: Implement the logic for loading a tokenizer and model."""
    print("Loading tokenizer...")
    tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME,
                                              padding_side="left", 
                                              trust_remote_code= True
                                             )
    print("Tokenizer loaded successfully.")
    print("\nLoading model...")
    if quantization_config is None:
        model = AutoModelForCausalLM.from_pretrained(
            MODEL_NAME,
            torch_dtype=torch.float16,
            #device_map= "balanced",
            trust_remote_code =True
            ) #.to(DEVICE)
    else:
        model = AutoModelForCausalLM.from_pretrained(
            MODEL_NAME,
            quantization_config=quantization_config,
            device_map= "auto",
            trust_remote_code =True
            ).to(DEVICE)
    print("Model loaded successfully and moved to device.")
    memory_mb = get_model_memory_footprint(model)
    print(f"Memory Footprint: {memory_mb:.2f} MB")
  
    model.config.eos_token_id = tokenizer.eos_token_id
    tokenizer.pad_token = tokenizer.eos_token
    tokenizer.pad_token_id = tokenizer.eos_token_id
    model.config.pad_token_id = model.config.eos_token_id
    print("Model loaded successfully and moved to device.")
    model.eval()
    return tokenizer, model

#DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'
#MODEL_NAME = "meta-llama/Llama-3.2-1B-Instruct"
#Use DEVICE = balanced or auto
#tokenizer, model = load_model(MODEL_NAME, DEVICE, quantization_config=None)
#del model

def convert_chat_form_tokenize(tokenizer, ds):

    def base_format(sample):
        system_message = f'You are a news headline generator who generates catchy news headline from given news summary.\nGenerate a headline for following news summary of type: {sample["category"]}'
        messages = [
            {"role": 'system','content': system_message},
            {"role": 'user','content': sample["short_description"]},
            ]
        if generate_text:
            text_dict = {'text_gen': messages}
        else:
            messages.append({"role": 'assistant','content': sample["headline"]})
            text_dict = {'text': messages}
        return text_dict

    def apply_chat_temp(example):
        if generate_text:
            toks = tokenizer.apply_chat_template(example['text_gen'],tokenize=True, add_generation_prompt=True)
        else:
            toks = tokenizer.apply_chat_template(example['text'],tokenize=True)
        return toks

    generate_text = False
    ds = ds.map(base_format)
    #print(ds[0])

    generate_text = True
    ds = ds.map(base_format)
    #print(ds[0])

    tok_ds = ds.train_test_split(test_size=0.01, seed=42)
    
    generate_text = False
    tok_ds['train'] = tok_ds['train'].map(apply_chat_temp)
    #print(ds[0])

    #tok_ds = ds.train_test_split(test_size=0.01, seed=42)

    generate_text = True
    tok_ds['test'] = tok_ds['test'].map(apply_chat_temp)
    #print(tok_ds['test'][0])
    #print(tok_ds['train'][0], tok_ds['test'][0])
    return tok_ds

#tok_ds = convert_chat_form_tokenize(tokenizer, news_ds)
#print(tok_ds)

#MAX_NEW_TOKENS = 40

def generate_headline_batch(model, tokenizer, device, generation_args, data_loader, exp, df):
    """TODO: Implement the headline generation and latency measurement logic."""
    for batch in data_loader:
        warmup_example = batch["input_ids"].to(model.device)
        model.eval()
        cuda_warmup(model, warmup_example, model.device)
        break
        
    torch.cuda.reset_peak_memory_stats(model.device)
    
    latencies_per_batch = []
    throughputs = []
    peak_mem = []
    batch_outputs = []
    references = []
    for step, batch in enumerate(data_loader):
        print(f"Batch {step}")
        #print("input_ids.shape:", batch["input_ids"].shape)
        #print("headline_ids.shape:", batch["headline_ids"].shape)       
        t0 = time.perf_counter()
        batch["input_ids"] = batch["input_ids"].to(model.device)
        with torch.inference_mode():
            outputs = model.generate(input_ids=batch["input_ids"], **generation_args)
        torch.cuda.synchronize()
        t1 = time.perf_counter()
        
        latency_per_batch = (t1 - t0)
        latencies_per_batch.append(latency_per_batch)

        peak_mem_mib = torch.cuda.max_memory_allocated(model.device) / 1024**2
        peak_mem.append(peak_mem_mib)
        
        inputs_decode = tokenizer.batch_decode(batch["input_ids"], skip_special_tokens=True)
        inputs_toks_len_list = [len(tokenizer.encode(inp)) for inp in inputs_decode]
        
        outputs_decode = tokenizer.batch_decode(outputs, skip_special_tokens=True)
        outputs_text = [remove_punctuation(out.split('assistant\n\n')[-1]) for out in outputs_decode]
        batch_outputs.extend(outputs_text)
        
        outputs_toks_len_list = [len(tokenizer.encode(out)) for out in outputs_decode]
        
        num_toks_gen = sum(np.array(outputs_toks_len_list) - np.array(inputs_toks_len_list))
        throughput = num_toks_gen / latency_per_batch if latency_per_batch > 0 else float("nan")
        throughputs.append(throughput)
        
        headline_decode = tokenizer.batch_decode(batch["headline_ids"], skip_special_tokens=True)
        references.extend(headline_decode)


    rouge = evaluate.load("rouge")
    rouge_score = rouge.compute(predictions=batch_outputs, references=references)['rouge1']
    
    avg_latency_per_batch = sum(latencies_per_batch) / len(latencies_per_batch)
    avg_latency_per_batch_item = sum(latencies_per_batch) / len(data_loader.dataset)
    
    avg_throughput = sum(throughputs) / len(throughputs)
    avg_peak_mib = sum(peak_mem)/len(peak_mem)
    
    print(avg_latency_per_batch, avg_latency_per_batch_item, avg_throughput, avg_peak_mib, rouge_score)
    
    new_df = pd.DataFrame({"EXP NAME": [exp], "Mean Latency (s)": [f"{round(avg_latency_per_batch, 2)}/{round(avg_latency_per_batch_item, 2)}"], "Throughput (tokens/s)": [round(avg_throughput,2)], "Avg Peak Mem": [round(avg_peak_mib, 2)], "ROUGE-1 Score": [round(rouge_score, 2)]}) 
    df = pd.concat([df, new_df], axis=0)
    
    return df

def generate_config(MAX_NEW_TOKENS, tokenizer, temperature=0.6, top_p=0.5, top_k=3, do_sample=True, use_cache=True):
    generation_config = {
        "max_new_tokens": MAX_NEW_TOKENS,
        "temperature": temperature,           # Controls randomness (lower = more deterministic)
        "top_p": top_p,                 # Nucleus sampling for diversity
        "top_k": top_k,                  # Limits candidates per step
        "do_sample": do_sample,            # Enables stochastic sampling
        # Repetition control
        "repetition_penalty": 1.2,    # Penalizes repeated tokens
        # Efficiency / inference tuning
        "use_cache": use_cache,            # Cache KV states for faster decoding
        # Optional advanced knobs
        "min_new_tokens": 10,         # Guarantees some output
        "eos_token_id": tokenizer.eos_token_id,
        "pad_token_id": tokenizer.pad_token_id,

        }
    return generation_config

#generation_args = generate_config(MAX_NEW_TOKENS)
#print(generation_args)

def base_format(sample):
    system_message = f'You are a news headline generator who generates catchy news headline from given news summary.\nGenerate a headline for following news summary of type: {sample["category"]}'
    messages = [
        {"role": 'system','content': system_message},
        {"role": 'user','content': sample["short_description"]},
        ]
    if generate_text:
        text_dict = {'text_gen': messages}
    else:
        messages.append({"role": 'assistant','content': sample["headline"]})
        text_dict = {'text': messages}
    return text_dict

def apply_chat_temp(tokenizer, example, generate_text=False):
    if generate_text:
        toks = tokenizer.apply_chat_template(example['text_gen'],tokenize=True, add_generation_prompt=True)
    else:
        toks = tokenizer.apply_chat_template(example['text'],tokenize=True)
    return toks

def cuda_warmup(model, toks, device, num_runs=5):
    for runs in range(num_runs):
        with torch.inference_mode():
            _ = model.generate(toks, max_new_tokens=15)
        torch.cuda.synchronize()
    print("WarmUp runs completed")

import string

def remove_punctuation(text: str) -> str:
    # Create a translation table that maps punctuation to None
    translator = str.maketrans('', '', string.punctuation)
    return text.translate(translator)

def generate_headline(model, tokenizer, toks, device, generation_args):
    """TODO: Implement the headline generation and latency measurement logic."""
    t0 = time.perf_counter()
    with torch.inference_mode():
            outputs = model.generate(**toks, **generation_args)
    torch.cuda.synchronize()
    t1 = time.perf_counter()
    latency = t1 - t0
    gen_len = outputs.shape[1] - toks["input_ids"].shape[1]
    peak_mem_mib = torch.cuda.max_memory_allocated(model.device) / 1024**2
    throughput = gen_len / latency if latency > 0 else float("nan")

    outputs_text = tokenizer.decode(outputs)
    outputs_text = remove_punctuation(outputs_text[0].split('<|start_header_id|>assistant<|end_header_id|>')[-1].split('<|eot_id|>')[0].strip())
    #print(outputs_text)
    del model
    return latency, throughput, peak_mem_mib, outputs_text

def report_metrics(tok_ds, model, tokenizer, DEVICE, generation_args, exp, df):
    """TODO: Implement the logic for calculating and reporting all performance metrics."""
    avg_latency, avg_throughput, avg_peak_mib, rouge_score = evaluate_model(tok_ds, model, tokenizer, DEVICE, generation_args)
    new_df = pd.DataFrame({"EXP NAME": [exp], "Mean Latency (s)": [avg_latency], "Throughput (tokens/s)": [avg_throughput], "Avg Peak Mem": [avg_peak_mib], "ROUGE-1 Score": [rouge_score]}) 
    df = pd.concat([df, new_df], axis=0)
    return df

import random
import evaluate

def evaluate_model(dataset, model, tokenizer, device, generation_args, n=4):
    """TODO: Implement the model evaluation loop."""
    
    sample = random.sample(range(1000), 1)[0]
    warmup_example = dataset['train'][sample]
    toks = apply_chat_temp(tokenizer, warmup_example, generate_text=True)

    toks['input_ids'] = torch.tensor(toks['input_ids']).unsqueeze(0).to(model.device)
    toks['attention_mask'] = torch.tensor(toks['attention_mask']).unsqueeze(0).to(model.device)
    
    model.eval()
    cuda_warmup(model, toks['input_ids'], device)
    
    torch.cuda.reset_peak_memory_stats(model.device)
    samples = 100
    latencies = []
    throughputs = []
    peak_mem = []
    outputs = []
    references = []
    for i in range(n):
        for j in range(samples):
            sample = dataset['train'][j]
            references.append(sample['headline'])
            toks = apply_chat_temp(tokenizer, sample, generate_text=True)
            toks['input_ids'] = torch.tensor(toks['input_ids']).unsqueeze(0).to(model.device)
            toks['attention_mask'] = torch.tensor(toks['attention_mask']).unsqueeze(0).to(model.device)
            latency, throughput, peak_mem_mib, outputs_text = generate_headline(model, tokenizer, toks, device, generation_args)
            latencies.append(latency)
            throughputs.append(throughput)
            peak_mem.append(peak_mem_mib)
            outputs.append(outputs_text)
    
    rouge = evaluate.load("rouge")
    rouge_score = rouge.compute(predictions=outputs, references=references)['rouge1']
    avg_latency = sum(latencies) / len(latencies)
    avg_throughput = sum(throughputs) / len(throughputs)
    avg_peak_mib = sum(peak_mem)/len(peak_mem)
    print(avg_latency, avg_throughput, avg_peak_mib, rouge_score)
    return avg_latency, avg_throughput, avg_peak_mib, rouge_score

import copy
import torch.nn as nn
def prune_model_weights(model, amount=0.3):
    """TODO: Applies L1 unstructured pruning to the linear layers of a model."""
    pruned_model = copy.deepcopy(model)
    for name, module in pruned_model.named_modules():
        if isinstance(module, nn.Linear):
            prune.l1_unstructured(module, name="weight", amount=amount)
            prune.remove(module, "weight")
    print("Model pruned successfully")
    return pruned_model

# TODO: Establish your baseline performance.
#load the original model and establish baseline performance using functions defined above
def run_exp(exp, df, tok_ds, MODEL_NAME, DEVICE, generation_args, quantization_config=None, prune=False ):

    print("Running experiment now....", exp, "#######")

    tokenizer, model = load_model(MODEL_NAME, DEVICE, quantization_config=quantization_config)
    model = model.to(DEVICE)
    if prune:
        model = prune_model_weights(model, amount=0.3)        
    df = report_metrics(tok_ds, model, tokenizer, DEVICE, generation_args, exp, df)
    return df

# --- Main Execution Logic ---
def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--local_rank", type=int, default=-1)
    parser = deepspeed.add_config_arguments(parser)
    args = parser.parse_args()

    DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'
    MODEL_NAME = "meta-llama/Llama-3.2-1B-Instruct"
#########################################################
    print("#################################################################")
    print("Calling from main script")
    print("#################################################################")
    news_ds = load_news_dataset()
    
    login("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")
    tokenizer, model = load_model(MODEL_NAME, DEVICE, quantization_config=None)
    tok_ds = convert_chat_form_tokenize(tokenizer, news_ds)
    print(tok_ds)
    MAX_NEW_TOKENS = 40
    generation_args = generate_config(MAX_NEW_TOKENS, tokenizer)
    generation_args['use_cache']=True
    print(generation_args)

    #from torch.utils.data import DataLoader
    #from transformers import DataCollatorWithPadding

    #tok_ds = tok_ds.map(lambda x: {'headline_ids': tokenizer(x['headline'], padding='max_length', truncation=True, max_length=40)['input_ids']})
    #tok_ds_train = tok_ds['train'].remove_columns(['headline', 'category', 'short_description', 'text', 'text_gen', 'attention_mask'])
    #tok_ds_train = tok_ds_train.select(range(400))
    #data_collator_pad = DataCollatorWithPadding(tokenizer) 
    #data_loader = DataLoader(
    #tok_ds_train,
    #batch_size=128,
    #collate_fn=data_collator_pad
    #)
    #for step, batch in enumerate(data_loader):
    #    print(f"Batch {step}")
    #    print("input_ids.shape:", batch["input_ids"].shape)
    #
     #   print("attention_mask.shape:", batch["attention_mask"].shape)
     #   print("headline_ids.shape:", batch["headline_ids"].shape)
     #   if step >= 3:
     #       break

    ################################################################


    # --- Setup ---
    global_batch_size = 64
    #iterations = 20
    is_rank_0 = args.local_rank <= 0 # Rank -1 for non-distributed, 0 for distributed

    # --- Baseline Measurement (Single GPU) ---
    #if is_rank_0:
    #    print("\n--- Measuring Baseline Performance (Single GPU) ---", flush=True)
    #    try:
    #        DEVICE = 'cuda:0'
    #        df = pd.DataFrame()
    #        exp = "Pipeline Parallelism Single GPU"
    #        df = run_exp(exp, df, tok_ds, MODEL_NAME, DEVICE, generation_args) 
    #        df.to_csv("pp_1.csv")
    #        print(df)
    #    except Exception as e:
    #        print(f"Could not run baseline on single GPU, likely out of memory: {e}", flush=True)
    #    print("--------------------------------------------------\n", flush=True)

    if torch.distributed.is_initialized():
        torch.distributed.barrier()

    # --- DeepSpeed Pipeline Parallelism ---
    print(f"\n--- Rank {args.local_rank}: Setting up DeepSpeed Pipeline ---", flush=True)

    #_, model = load_model(MODEL_NAME, DEVICE, quantization_config=None)
    model_engine, _, _, _ = deepspeed.initialize(args=args, model=model, model_parameters=model.parameters())

    df = pd.DataFrame()
    exp = "Pipeline Parallelism 4 GPU"
    print("Running pipeline parallelism at the end of script and main function")
    df = report_metrics(tok_ds, model_engine, tokenizer, DEVICE, generation_args, exp, df)
    #exp = f"Batch {data_loader.batch_size} Pipeline Parallelism"
    #df = generate_headline_batch(model, tokenizer, DEVICE, generation_args, data_loader, exp, df)
    print(df)
    df.to_csv("pp.csv")
    return df

    print(f"\n--- Results on Last Stage (Rank {args.local_rank}) ---", flush=True)
    #    print(f"Pipelined Throughput: {pipelined_throughput:.2f} samples/sec", flush=True)
    #    print("------------------------------------------\n", flush=True)

if __name__ == "__main__":
    main()

Overwriting parallel_pipeline_script.py

In [2]:
import json

ds_config_pipeline_parallel = {
    "train_batch_size": 64, # Global batch size
    # A dummy optimizer is required by the DeepSpeed initializer
    "optimizer": { "type": "SGD", "params": { "lr": 0.001 } },
    # Pipeline Parallelism Configuration
    "pipeline": {
        "stages": 4,              # We will split the model into 2 stages for our 2 GPUs
        "partition_method": "uniform", # Tells DeepSpeed to split layers evenly. Perfect for nn.Sequential.
        "micro_batch_size": 16     # We split our global batch size into smaller micro-batches
      },
    "fp16": { "enabled": True },
    "comms_logger": {
        "enabled": False,
        "verbose": False,
        "debug": False
      }
}

In [3]:
# Write the configuration to a file
config_filename_demo = 'ds_config_parallel_pipeline.json'
with open(config_filename_demo, 'w') as f:
    json.dump(ds_config_pipeline_parallel, f, indent=2)

print(f"DeepSpeed configuration file '{config_filename_demo}' created.")
print("\n--- Demo Config Contents ---")
print(json.dumps(ds_config_pipeline_parallel, indent=2))
print("----------------------------")

DeepSpeed configuration file 'ds_config_parallel_pipeline.json' created.

--- Demo Config Contents ---
{
  "train_batch_size": 64,
  "optimizer": {
    "type": "SGD",
    "params": {
      "lr": 0.001
    }
  },
  "pipeline": {
    "stages": 4,
    "partition_method": "uniform",
    "micro_batch_size": 16
  },
  "fp16": {
    "enabled": true
  },
  "comms_logger": {
    "enabled": false,
    "verbose": false,
    "debug": false
  }
}
----------------------------

In [6]:
print("🚀 Launching DeepSpeed Pipeline Parallelism Demo...")
!DS_LOG_LEVEL=ERROR PYTHONWARNINGS=ignore deepspeed --num_gpus 1 parallel_pipeline_script.py --deepspeed_config ds_config_parallel_pipeline.json

🚀 Launching DeepSpeed Pipeline Parallelism Demo...
[2026-04-06 06:26:05,635] [INFO] [real_accelerator.py:254:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2026-04-06 06:26:09,364] [INFO] [logging.py:107:log_dist] [Rank -1] [TorchCheckpointEngine] Initialized with serialization = False
[2026-04-06 06:26:10,596] [WARNING] [runner.py:220:fetch_hostfile] Unable to find hostfile, will proceed with training with local resources only.
[2026-04-06 06:26:10,597] [INFO] [runner.py:610:main] cmd = /home/ec2-user/anaconda3/envs/pytorch_p310/bin/python3.10 -u -m deepspeed.launcher.launch --world_info=eyJsb2NhbGhvc3QiOiBbMF19 --master_addr=127.0.0.1 --master_port=29500 --enable_each_rank_log=None parallel_pipeline_script.py --deepspeed_config ds_config_parallel_pipeline.json
[2026-04-06 06:26:12,108] [INFO] [real_accelerator.py:254:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2026-04-06 06:26:15,835] [INFO] [logging.py:107:log_dist] [Rank -1] [TorchCheckpointEngine] Initialized with serialization = False
[2026-04-06 06:26:17,060] [INFO] [launch.py:146:main] WORLD INFO DICT: {'localhost': [0]}
[2026-04-06 06:26:17,061] [INFO] [launch.py:152:main] nnodes=1, num_local_procs=1, node_rank=0
[2026-04-06 06:26:17,061] [INFO] [launch.py:163:main] global_rank_mapping=defaultdict(<class 'list'>, {'localhost': [0]})
[2026-04-06 06:26:17,061] [INFO] [launch.py:164:main] dist_world_size=1
[2026-04-06 06:26:17,061] [INFO] [launch.py:168:main] Setting CUDA_VISIBLE_DEVICES=0
[2026-04-06 06:26:17,061] [INFO] [launch.py:256:main] process 7956 spawned with command: ['/home/ec2-user/anaconda3/envs/pytorch_p310/bin/python3.10', '-u', 'parallel_pipeline_script.py', '--local_rank=0', '--deepspeed_config', 'ds_config_parallel_pipeline.json']
[2026-04-06 06:26:21,643] [INFO] [real_accelerator.py:254:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2026-04-06 06:26:23,615] [INFO] [logging.py:107:log_dist] [Rank -1] [TorchCheckpointEngine] Initialized with serialization = False
#################################################################
Calling from main script
#################################################################
Path to dataset files: /home/ec2-user/.cache/kagglehub/datasets/rmisra/news-category-dataset/versions/3
Number of news items in each category
####################################
category
POLITICS          35602
WELLNESS          17945
ENTERTAINMENT     17362
TRAVEL             9900
STYLE & BEAUTY     9814
PARENTING          8791
HEALTHY LIVING     6694
QUEER VOICES       6347
FOOD & DRINK       6340
BUSINESS           5992
COMEDY             5400
SPORTS             5077
BLACK VOICES       4583
HOME & LIVING      4320
PARENTS            3955
THE WORLDPOST      3664
WEDDINGS           3653
WOMEN              3572
CRIME              3562
IMPACT             3484
DIVORCE            3426
WORLD NEWS         3299
MEDIA              2944
WEIRD NEWS         2777
GREEN              2622
WORLDPOST          2579
RELIGION           2577
STYLE              2254
SCIENCE            2206
TECH               2104
TASTE              2096
MONEY              1756
ARTS               1509
ENVIRONMENT        1444
FIFTY              1401
GOOD NEWS          1398
U.S. NEWS          1377
ARTS & CULTURE     1339
COLLEGE            1144
LATINO VOICES      1130
CULTURE & ARTS     1074
EDUCATION          1014
Name: count, dtype: int64
###########################################################
Total number of news categories in dataset: 42
###########################################################
Loading tokenizer...
Tokenizer loaded successfully.

Loading model...
`torch_dtype` is deprecated! Use `dtype` instead!
Loading weights: 100%|███████████████████████| 146/146 [00:00<00:00, 247.04it/s]
Model loaded successfully and moved to device.
Memory Footprint: 2357.13 MB
Model loaded successfully and moved to device.
Map: 100%|████████████████████| 209527/209527 [00:12<00:00, 16949.92 examples/s]
Map: 100%|████████████████████| 209527/209527 [00:13<00:00, 15459.60 examples/s]
Map: 100%|█████████████████████| 207431/207431 [01:48<00:00, 1920.55 examples/s]
Map: 100%|█████████████████████████| 2096/2096 [00:00<00:00, 2146.13 examples/s]
DatasetDict({
    train: Dataset({
        features: ['headline', 'category', 'short_description', 'text', 'text_gen', 'input_ids', 'attention_mask'],
        num_rows: 207431
    })
    test: Dataset({
        features: ['headline', 'category', 'short_description', 'text', 'text_gen', 'input_ids', 'attention_mask'],
        num_rows: 2096
    })
})
{'max_new_tokens': 40, 'temperature': 0.6, 'top_p': 0.5, 'top_k': 3, 'do_sample': True, 'repetition_penalty': 1.2, 'use_cache': True, 'min_new_tokens': 10, 'eos_token_id': 128009, 'pad_token_id': 128009}

--- Measuring Baseline Performance (Single GPU) ---
Running experiment now.... Pipeline Parallelism #######
Loading tokenizer...
Tokenizer loaded successfully.

Loading model...
Loading weights: 100%|███████████████████████| 146/146 [00:00<00:00, 239.09it/s]
Model loaded successfully and moved to device.
Memory Footprint: 2357.13 MB
Model loaded successfully and moved to device.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
WarmUp runs completed
0.39377438568499656 68.42838823751414 2377.419489746094 0.09497943859463515
               EXP NAME  Mean Latency (s)  ...  Avg Peak Mem  ROUGE-1 Score
0  Pipeline Parallelism          0.393774  ...    2377.41949       0.094979

[1 rows x 5 columns]
--------------------------------------------------


--- Rank 0: Setting up DeepSpeed Pipeline ---
Loading tokenizer...
Tokenizer loaded successfully.

Loading model...
Loading weights: 100%|███████████████████████| 146/146 [00:00<00:00, 242.08it/s]
Model loaded successfully and moved to device.
Memory Footprint: 2357.13 MB
Model loaded successfully and moved to device.
[2026-04-06 06:31:29,101] [INFO] [logging.py:107:log_dist] [Rank -1] DeepSpeed info: version=0.17.2, git-hash=unknown, git-branch=unknown
[2026-04-06 06:31:29,101] [INFO] [comm.py:676:init_distributed] cdb=None
[2026-04-06 06:31:29,101] [INFO] [comm.py:707:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
[2026-04-06 06:31:29,105] [INFO] [config.py:684:__init__] Config mesh_device None world_size = 1
[2026-04-06 06:31:29,110] [INFO] [engine.py:1339:_configure_distributed_model] ********** distributed groups summary **********
	 self.dp_world_size=1
	 self.mp_world_size=1
	 self.seq_dp_world_size=1
	 self.sequence_parallel_size=1
***********************************************
[2026-04-06 06:31:30,717] [INFO] [logging.py:107:log_dist] [Rank 0] DeepSpeed Flops Profiler Enabled: False
[2026-04-06 06:31:30,717] [INFO] [logging.py:107:log_dist] [Rank 0] Using DeepSpeed Optimizer param name SGD as basic optimizer
[2026-04-06 06:31:30,717] [INFO] [logging.py:107:log_dist] [Rank 0] Removing param_group that has no 'params' in the basic Optimizer
[2026-04-06 06:31:30,721] [INFO] [logging.py:107:log_dist] [Rank 0] DeepSpeed Basic Optimizer = SGD
[2026-04-06 06:31:30,721] [INFO] [logging.py:107:log_dist] [Rank 0] Creating fp16 unfused optimizer with dynamic loss scale
[2026-04-06 06:31:30,721] [INFO] [unfused_optimizer.py:46:__init__] Fused Lamb Legacy : False
[2026-04-06 06:31:30,781] [INFO] [logging.py:107:log_dist] [Rank 0] DeepSpeed Final Optimizer = FP16_UnfusedOptimizer
[2026-04-06 06:31:30,781] [INFO] [logging.py:107:log_dist] [Rank 0] DeepSpeed using configured LR scheduler = None
[2026-04-06 06:31:30,781] [INFO] [logging.py:107:log_dist] [Rank 0] DeepSpeed LR Scheduler = None
[2026-04-06 06:31:30,781] [INFO] [logging.py:107:log_dist] [Rank 0] step=0, skipped=0, lr=[0.001], mom=[0]
[2026-04-06 06:31:30,782] [INFO] [logging.py:107:log_dist] [Rank 0] [TorchCheckpointEngine] Initialized with serialization = True
[2026-04-06 06:31:30,782] [INFO] [config.py:954:print] DeepSpeedEngine configuration:
[2026-04-06 06:31:30,782] [INFO] [config.py:958:print]   activation_checkpointing_config  {
    "partition_activations": false,
    "contiguous_memory_optimization": false,
    "cpu_checkpointing": false,
    "number_checkpoints": null,
    "synchronize_checkpoint_boundary": false,
    "profile": false
}
[2026-04-06 06:31:30,782] [INFO] [config.py:958:print]   aio_config ................... {'block_size': 1048576, 'queue_depth': 8, 'intra_op_parallelism': 1, 'single_submit': False, 'overlap_events': True, 'use_gds': False}
[2026-04-06 06:31:30,782] [INFO] [config.py:958:print]   amp_enabled .................. False
[2026-04-06 06:31:30,782] [INFO] [config.py:958:print]   amp_params ................... False
[2026-04-06 06:31:30,782] [INFO] [config.py:958:print]   autotuning_config ............ {
    "enabled": false,
    "start_step": null,
    "end_step": null,
    "metric_path": null,
    "arg_mappings": null,
    "metric": "throughput",
    "model_info": null,
    "results_dir": "autotuning_results",
    "exps_dir": "autotuning_exps",
    "overwrite": true,
    "fast": true,
    "start_profile_step": 3,
    "end_profile_step": 5,
    "tuner_type": "gridsearch",
    "tuner_early_stopping": 5,
    "tuner_num_trials": 50,
    "model_info_path": null,
    "mp_size": 1,
    "max_train_batch_size": null,
    "min_train_batch_size": 1,
    "max_train_micro_batch_size_per_gpu": 1.024000e+03,
    "min_train_micro_batch_size_per_gpu": 1,
    "num_tuning_micro_batch_sizes": 3
}
[2026-04-06 06:31:30,782] [INFO] [config.py:958:print]   bfloat16_config .............. enabled=False immediate_grad_update=False check_grad_overflow=False
[2026-04-06 06:31:30,782] [INFO] [config.py:958:print]   checkpoint_config ............ {'tag_validation': 'WARN', 'checkpoint_serialization': True, 'writer': None}
[2026-04-06 06:31:30,782] [INFO] [config.py:958:print]   checkpoint_parallel_write_pipeline  False
[2026-04-06 06:31:30,782] [INFO] [config.py:958:print]   checkpoint_tag_validation_enabled  True
[2026-04-06 06:31:30,782] [INFO] [config.py:958:print]   checkpoint_tag_validation_fail  False
[2026-04-06 06:31:30,782] [INFO] [config.py:958:print]   comms_config ................. <deepspeed.comm.config.DeepSpeedCommsConfig object at 0x7f8598fd05e0>
[2026-04-06 06:31:30,782] [INFO] [config.py:958:print]   communication_data_type ...... None
[2026-04-06 06:31:30,783] [INFO] [config.py:958:print]   compile_config ............... deepcompile=False free_activation=False offload_activation=False offload_opt_states=False double_buffer=True symmetric_memory=False debug_log=False offload_parameters=False sync_before_reduce=False sync_after_reduce=False sync_before_allgather=False sync_after_allgather=False keep_int_input_tensors=True keep_all_input_tensors=False
[2026-04-06 06:31:30,783] [INFO] [config.py:958:print]   compression_config ........... {'weight_quantization': {'shared_parameters': {'enabled': False, 'quantizer_kernel': False, 'schedule_offset': 0, 'quantize_groups': 1, 'quantize_verbose': False, 'quantization_type': 'symmetric', 'quantize_weight_in_forward': False, 'rounding': 'nearest', 'fp16_mixed_quantize': False, 'quantize_change_ratio': 0.001}, 'different_groups': {}}, 'activation_quantization': {'shared_parameters': {'enabled': False, 'quantization_type': 'symmetric', 'range_calibration': 'dynamic', 'schedule_offset': 1000}, 'different_groups': {}}, 'sparse_pruning': {'shared_parameters': {'enabled': False, 'method': 'l1', 'schedule_offset': 1000}, 'different_groups': {}}, 'row_pruning': {'shared_parameters': {'enabled': False, 'method': 'l1', 'schedule_offset': 1000}, 'different_groups': {}}, 'head_pruning': {'shared_parameters': {'enabled': False, 'method': 'topk', 'schedule_offset': 1000}, 'different_groups': {}}, 'channel_pruning': {'shared_parameters': {'enabled': False, 'method': 'l1', 'schedule_offset': 1000}, 'different_groups': {}}, 'layer_reduction': {'enabled': False}}
[2026-04-06 06:31:30,783] [INFO] [config.py:958:print]   curriculum_enabled_legacy .... False
[2026-04-06 06:31:30,783] [INFO] [config.py:958:print]   curriculum_params_legacy ..... False
[2026-04-06 06:31:30,783] [INFO] [config.py:958:print]   data_efficiency_config ....... {'enabled': False, 'seed': 1234, 'data_sampling': {'enabled': False, 'num_epochs': 1000, 'num_workers': 0, 'pin_memory': False, 'curriculum_learning': {'enabled': False}, 'dynamic_batching': {'enabled': False, 'lr_scaling_method': 'linear', 'min_batch_size': 1, 'max_batch_size': None, 'sequence_picking_order': 'dataloader', 'verbose': False}}, 'data_routing': {'enabled': False, 'random_ltd': {'enabled': False, 'layer_token_lr_schedule': {'enabled': False}}}}
[2026-04-06 06:31:30,783] [INFO] [config.py:958:print]   data_efficiency_enabled ...... False
[2026-04-06 06:31:30,783] [INFO] [config.py:958:print]   dataloader_drop_last ......... False
[2026-04-06 06:31:30,783] [INFO] [config.py:958:print]   disable_allgather ............ False
[2026-04-06 06:31:30,783] [INFO] [config.py:958:print]   dump_state ................... False
[2026-04-06 06:31:30,783] [INFO] [config.py:958:print]   eigenvalue_enabled ........... False
[2026-04-06 06:31:30,783] [INFO] [config.py:958:print]   eigenvalue_gas_boundary_resolution  1
[2026-04-06 06:31:30,783] [INFO] [config.py:958:print]   eigenvalue_layer_name ........ bert.encoder.layer
[2026-04-06 06:31:30,783] [INFO] [config.py:958:print]   eigenvalue_layer_num ......... 0
[2026-04-06 06:31:30,783] [INFO] [config.py:958:print]   eigenvalue_max_iter .......... 100
[2026-04-06 06:31:30,783] [INFO] [config.py:958:print]   eigenvalue_stability ......... 1e-06
[2026-04-06 06:31:30,783] [INFO] [config.py:958:print]   eigenvalue_tol ............... 0.01
[2026-04-06 06:31:30,783] [INFO] [config.py:958:print]   eigenvalue_verbose ........... False
[2026-04-06 06:31:30,783] [INFO] [config.py:958:print]   elasticity_enabled ........... False
[2026-04-06 06:31:30,783] [INFO] [config.py:958:print]   float16_config ............... enabled=True auto_cast=False loss_scale=0.0 initial_scale_power=16 loss_scale_window=1000 hysteresis=2 consecutive_hysteresis=False min_loss_scale=1 fp16_master_weights_and_grads=False
[2026-04-06 06:31:30,783] [INFO] [config.py:958:print]   flops_profiler_config ........ {
    "enabled": false,
    "recompute_fwd_factor": 0.0,
    "profile_step": 1,
    "module_depth": -1,
    "top_modules": 1,
    "detailed": true,
    "output_file": null
}
[2026-04-06 06:31:30,783] [INFO] [config.py:958:print]   global_rank .................. 0
[2026-04-06 06:31:30,783] [INFO] [config.py:958:print]   grad_accum_dtype ............. None
[2026-04-06 06:31:30,783] [INFO] [config.py:958:print]   gradient_accumulation_steps .. 1
[2026-04-06 06:31:30,784] [INFO] [config.py:958:print]   gradient_clipping ............ 0.0
[2026-04-06 06:31:30,784] [INFO] [config.py:958:print]   gradient_predivide_factor .... 1.0
[2026-04-06 06:31:30,784] [INFO] [config.py:958:print]   graph_harvesting ............. False
[2026-04-06 06:31:30,784] [INFO] [config.py:958:print]   hybrid_engine ................ enabled=False max_out_tokens=512 inference_tp_size=1 release_inference_cache=False pin_parameters=True tp_gather_partition_size=8
[2026-04-06 06:31:30,784] [INFO] [config.py:958:print]   load_universal_checkpoint .... False
[2026-04-06 06:31:30,784] [INFO] [config.py:958:print]   memory_breakdown ............. False
[2026-04-06 06:31:30,784] [INFO] [config.py:958:print]   mics_hierarchial_params_gather  False
[2026-04-06 06:31:30,784] [INFO] [config.py:958:print]   mics_shard_size .............. -1
[2026-04-06 06:31:30,784] [INFO] [config.py:958:print]   monitor_config ............... tensorboard=TensorBoardConfig(enabled=False, output_path='', job_name='DeepSpeedJobName') comet=CometConfig(enabled=False, samples_log_interval=100, project=None, workspace=None, api_key=None, experiment_name=None, experiment_key=None, online=None, mode=None) wandb=WandbConfig(enabled=False, group=None, team=None, project='deepspeed') csv_monitor=CSVConfig(enabled=False, output_path='', job_name='DeepSpeedJobName')
[2026-04-06 06:31:30,784] [INFO] [config.py:958:print]   nebula_config ................ {
    "enabled": false,
    "persistent_storage_path": null,
    "persistent_time_interval": 100,
    "num_of_version_in_retention": 2,
    "enable_nebula_load": true,
    "load_path": null
}
[2026-04-06 06:31:30,784] [INFO] [config.py:958:print]   optimizer_legacy_fusion ...... False
[2026-04-06 06:31:30,784] [INFO] [config.py:958:print]   optimizer_name ............... SGD
[2026-04-06 06:31:30,784] [INFO] [config.py:958:print]   optimizer_params ............. {'lr': 0.001}
[2026-04-06 06:31:30,784] [INFO] [config.py:958:print]   pipeline ..................... {'stages': 2, 'partition': 'best', 'seed_layers': False, 'activation_checkpoint_interval': 0, 'pipe_partitioned': True, 'grad_partitioned': True, 'partition_method': 'uniform', 'micro_batch_size': 16}
[2026-04-06 06:31:30,784] [INFO] [config.py:958:print]   pld_enabled .................. False
[2026-04-06 06:31:30,784] [INFO] [config.py:958:print]   pld_params ................... False
[2026-04-06 06:31:30,784] [INFO] [config.py:958:print]   prescale_gradients ........... False
[2026-04-06 06:31:30,784] [INFO] [config.py:958:print]   scheduler_name ............... None
[2026-04-06 06:31:30,784] [INFO] [config.py:958:print]   scheduler_params ............. None
[2026-04-06 06:31:30,784] [INFO] [config.py:958:print]   seq_parallel_communication_data_type  torch.float32
[2026-04-06 06:31:30,784] [INFO] [config.py:958:print]   sparse_attention ............. None
[2026-04-06 06:31:30,785] [INFO] [config.py:958:print]   sparse_gradients_enabled ..... False
[2026-04-06 06:31:30,785] [INFO] [config.py:958:print]   steps_per_print .............. None
[2026-04-06 06:31:30,785] [INFO] [config.py:958:print]   tensor_parallel_config ....... dtype=torch.float16 autotp_size=0 tp_overlap_comm=False tensor_parallel=TPConfig(tp_size=1, tp_grain_size=1, mpu=None, tp_group=None) injection_policy_tuple=None keep_module_on_host=False replace_with_kernel_inject=False
[2026-04-06 06:31:30,785] [INFO] [config.py:958:print]   timers_config ................ enabled=True synchronized=True
[2026-04-06 06:31:30,785] [INFO] [config.py:958:print]   torch_autocast_dtype ......... None
[2026-04-06 06:31:30,785] [INFO] [config.py:958:print]   torch_autocast_enabled ....... False
[2026-04-06 06:31:30,785] [INFO] [config.py:958:print]   torch_autocast_lower_precision_safe_modules  None
[2026-04-06 06:31:30,785] [INFO] [config.py:958:print]   train_batch_size ............. 64
[2026-04-06 06:31:30,785] [INFO] [config.py:958:print]   train_micro_batch_size_per_gpu  64
[2026-04-06 06:31:30,785] [INFO] [config.py:958:print]   use_data_before_expert_parallel_  False
[2026-04-06 06:31:30,785] [INFO] [config.py:958:print]   use_node_local_storage ....... False
[2026-04-06 06:31:30,785] [INFO] [config.py:958:print]   wall_clock_breakdown ......... False
[2026-04-06 06:31:30,785] [INFO] [config.py:958:print]   weight_quantization_config ... None
[2026-04-06 06:31:30,785] [INFO] [config.py:958:print]   world_size ................... 1
[2026-04-06 06:31:30,785] [INFO] [config.py:958:print]   zero_allow_untested_optimizer  False

In [4]:
print("🚀 Launching DeepSpeed Pipeline Parallelism 4 GPUs...")
!DS_LOG_LEVEL=ERROR PYTHONWARNINGS=ignore deepspeed --num_gpus 4 parallel_pipeline_script.py --deepspeed_config ds_config_parallel_pipeline.json

🚀 Launching DeepSpeed Pipeline Parallelism 4 GPUs...
[2026-04-07 04:15:15,363] [INFO] [real_accelerator.py:254:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2026-04-07 04:15:19,512] [INFO] [logging.py:107:log_dist] [Rank -1] [TorchCheckpointEngine] Initialized with serialization = False
[2026-04-07 04:15:20,926] [WARNING] [runner.py:220:fetch_hostfile] Unable to find hostfile, will proceed with training with local resources only.
[2026-04-07 04:15:20,926] [INFO] [runner.py:610:main] cmd = /home/ec2-user/anaconda3/envs/pytorch_p310/bin/python3.10 -u -m deepspeed.launcher.launch --world_info=eyJsb2NhbGhvc3QiOiBbMCwgMSwgMiwgM119 --master_addr=127.0.0.1 --master_port=29500 --enable_each_rank_log=None parallel_pipeline_script.py --deepspeed_config ds_config_parallel_pipeline.json
[2026-04-07 04:15:22,732] [INFO] [real_accelerator.py:254:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2026-04-07 04:15:26,892] [INFO] [logging.py:107:log_dist] [Rank -1] [TorchCheckpointEngine] Initialized with serialization = False
[2026-04-07 04:15:28,303] [INFO] [launch.py:146:main] WORLD INFO DICT: {'localhost': [0, 1, 2, 3]}
[2026-04-07 04:15:28,303] [INFO] [launch.py:152:main] nnodes=1, num_local_procs=4, node_rank=0
[2026-04-07 04:15:28,303] [INFO] [launch.py:163:main] global_rank_mapping=defaultdict(<class 'list'>, {'localhost': [0, 1, 2, 3]})
[2026-04-07 04:15:28,303] [INFO] [launch.py:164:main] dist_world_size=4
[2026-04-07 04:15:28,304] [INFO] [launch.py:168:main] Setting CUDA_VISIBLE_DEVICES=0,1,2,3
[2026-04-07 04:15:28,304] [INFO] [launch.py:256:main] process 44257 spawned with command: ['/home/ec2-user/anaconda3/envs/pytorch_p310/bin/python3.10', '-u', 'parallel_pipeline_script.py', '--local_rank=0', '--deepspeed_config', 'ds_config_parallel_pipeline.json']
[2026-04-07 04:15:28,304] [INFO] [launch.py:256:main] process 44258 spawned with command: ['/home/ec2-user/anaconda3/envs/pytorch_p310/bin/python3.10', '-u', 'parallel_pipeline_script.py', '--local_rank=1', '--deepspeed_config', 'ds_config_parallel_pipeline.json']
[2026-04-07 04:15:28,305] [INFO] [launch.py:256:main] process 44259 spawned with command: ['/home/ec2-user/anaconda3/envs/pytorch_p310/bin/python3.10', '-u', 'parallel_pipeline_script.py', '--local_rank=2', '--deepspeed_config', 'ds_config_parallel_pipeline.json']
[2026-04-07 04:15:28,305] [INFO] [launch.py:256:main] process 44260 spawned with command: ['/home/ec2-user/anaconda3/envs/pytorch_p310/bin/python3.10', '-u', 'parallel_pipeline_script.py', '--local_rank=3', '--deepspeed_config', 'ds_config_parallel_pipeline.json']
[2026-04-07 04:15:34,133] [INFO] [real_accelerator.py:254:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2026-04-07 04:15:34,164] [INFO] [real_accelerator.py:254:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2026-04-07 04:15:34,168] [INFO] [real_accelerator.py:254:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2026-04-07 04:15:34,172] [INFO] [real_accelerator.py:254:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2026-04-07 04:15:36,354] [INFO] [logging.py:107:log_dist] [Rank -1] [TorchCheckpointEngine] Initialized with serialization = False
[2026-04-07 04:15:36,369] [INFO] [logging.py:107:log_dist] [Rank -1] [TorchCheckpointEngine] Initialized with serialization = False
#################################################################
Calling from main script
#################################################################
[2026-04-07 04:15:36,377] [INFO] [logging.py:107:log_dist] [Rank -1] [TorchCheckpointEngine] Initialized with serialization = False
[2026-04-07 04:15:36,383] [INFO] [logging.py:107:log_dist] [Rank -1] [TorchCheckpointEngine] Initialized with serialization = False
#################################################################
Calling from main script
#################################################################
#################################################################
Calling from main script
#################################################################
#################################################################
Calling from main script
#################################################################
Path to dataset files: /home/ec2-user/.cache/kagglehub/datasets/rmisra/news-category-dataset/versions/3
Path to dataset files: /home/ec2-user/.cache/kagglehub/datasets/rmisra/news-category-dataset/versions/3
Path to dataset files: /home/ec2-user/.cache/kagglehub/datasets/rmisra/news-category-dataset/versions/3
Path to dataset files: /home/ec2-user/.cache/kagglehub/datasets/rmisra/news-category-dataset/versions/3
Number of news items in each category
####################################
category
POLITICS          35602
WELLNESS          17945
ENTERTAINMENT     17362
TRAVEL             9900
STYLE & BEAUTY     9814
PARENTING          8791
HEALTHY LIVING     6694
QUEER VOICES       6347
FOOD & DRINK       6340
BUSINESS           5992
COMEDY             5400
SPORTS             5077
BLACK VOICES       4583
HOME & LIVING      4320
PARENTS            3955
THE WORLDPOST      3664
WEDDINGS           3653
WOMEN              3572
CRIME              3562
IMPACT             3484
DIVORCE            3426
WORLD NEWS         3299
MEDIA              2944
WEIRD NEWS         2777
GREEN              2622
WORLDPOST          2579
RELIGION           2577
STYLE              2254
SCIENCE            2206
TECH               2104
TASTE              2096
MONEY              1756
ARTS               1509
ENVIRONMENT        1444
FIFTY              1401
GOOD NEWS          1398
U.S. NEWS          1377
ARTS & CULTURE     1339
COLLEGE            1144
LATINO VOICES      1130
CULTURE & ARTS     1074
EDUCATION          1014
Name: count, dtype: int64
###########################################################
Total number of news categories in dataset: 42
###########################################################
Number of news items in each category
####################################
category
POLITICS          35602
WELLNESS          17945
ENTERTAINMENT     17362
TRAVEL             9900
STYLE & BEAUTY     9814
PARENTING          8791
HEALTHY LIVING     6694
QUEER VOICES       6347
FOOD & DRINK       6340
BUSINESS           5992
COMEDY             5400
SPORTS             5077
BLACK VOICES       4583
HOME & LIVING      4320
PARENTS            3955
THE WORLDPOST      3664
WEDDINGS           3653
WOMEN              3572
CRIME              3562
IMPACT             3484
DIVORCE            3426
WORLD NEWS         3299
MEDIA              2944
WEIRD NEWS         2777
GREEN              2622
WORLDPOST          2579
RELIGION           2577
STYLE              2254
SCIENCE            2206
TECH               2104
TASTE              2096
MONEY              1756
ARTS               1509
ENVIRONMENT        1444
FIFTY              1401
GOOD NEWS          1398
U.S. NEWS          1377
ARTS & CULTURE     1339
COLLEGE            1144
LATINO VOICES      1130
CULTURE & ARTS     1074
EDUCATION          1014
Name: count, dtype: int64
###########################################################
Number of news items in each category
####################################
category
POLITICS          35602
WELLNESS          17945
ENTERTAINMENT     17362
TRAVEL             9900
STYLE & BEAUTY     9814
PARENTING          8791
HEALTHY LIVING     6694
QUEER VOICES       6347
FOOD & DRINK       6340
BUSINESS           5992
COMEDY             5400
SPORTS             5077
BLACK VOICES       4583
HOME & LIVING      4320
PARENTS            3955
THE WORLDPOST      3664
WEDDINGS           3653
WOMEN              3572
CRIME              3562
IMPACT             3484
DIVORCE            3426
WORLD NEWS         3299
MEDIA              2944
WEIRD NEWS         2777
GREEN              2622
WORLDPOST          2579
RELIGION           2577
STYLE              2254
SCIENCE            2206
TECH               2104
TASTE              2096
MONEY              1756
ARTS               1509
ENVIRONMENT        1444
FIFTY              1401
GOOD NEWS          1398
U.S. NEWS          1377
ARTS & CULTURE     1339
COLLEGE            1144
LATINO VOICES      1130
CULTURE & ARTS     1074
EDUCATION          1014
Name: count, dtype: int64
###########################################################
Total number of news categories in dataset: 42
###########################################################
Total number of news categories in dataset: 42
###########################################################
Number of news items in each category
####################################
category
POLITICS          35602
WELLNESS          17945
ENTERTAINMENT     17362
TRAVEL             9900
STYLE & BEAUTY     9814
PARENTING          8791
HEALTHY LIVING     6694
QUEER VOICES       6347
FOOD & DRINK       6340
BUSINESS           5992
COMEDY             5400
SPORTS             5077
BLACK VOICES       4583
HOME & LIVING      4320
PARENTS            3955
THE WORLDPOST      3664
WEDDINGS           3653
WOMEN              3572
CRIME              3562
IMPACT             3484
DIVORCE            3426
WORLD NEWS         3299
MEDIA              2944
WEIRD NEWS         2777
GREEN              2622
WORLDPOST          2579
RELIGION           2577
STYLE              2254
SCIENCE            2206
TECH               2104
TASTE              2096
MONEY              1756
ARTS               1509
ENVIRONMENT        1444
FIFTY              1401
GOOD NEWS          1398
U.S. NEWS          1377
ARTS & CULTURE     1339
COLLEGE            1144
LATINO VOICES      1130
CULTURE & ARTS     1074
EDUCATION          1014
Name: count, dtype: int64
###########################################################
Total number of news categories in dataset: 42
###########################################################
Loading tokenizer...
Loading tokenizer...
Loading tokenizer...
Loading tokenizer...
Tokenizer loaded successfully.

Loading model...
Tokenizer loaded successfully.

Loading model...
Tokenizer loaded successfully.

Loading model...
`torch_dtype` is deprecated! Use `dtype` instead!
`torch_dtype` is deprecated! Use `dtype` instead!
Tokenizer loaded successfully.

Loading model...
`torch_dtype` is deprecated! Use `dtype` instead!
Loading weights:   0%|                                  | 0/146 [00:00<?, ?it/s]`torch_dtype` is deprecated! Use `dtype` instead!
Loading weights: 100%|███████████████████████| 146/146 [00:00<00:00, 621.73it/s]
Loading weights: 100%|███████████████████████| 146/146 [00:00<00:00, 518.71it/s]
Loading weights: 100%|███████████████████████| 146/146 [00:00<00:00, 554.06it/s]
Loading weights: 100%|███████████████████████| 146/146 [00:00<00:00, 546.90it/s]
Model loaded successfully and moved to device.
Memory Footprint: 2357.13 MB
Model loaded successfully and moved to device.
Map:   0%|                                    | 0/209527 [00:00<?, ? examples/s]Model loaded successfully and moved to device.
Memory Footprint: 2357.13 MB
Model loaded successfully and moved to device.
Map:   1%|▏                     | 1586/209527 [00:00<00:13, 15762.68 examples/s]Model loaded successfully and moved to device.
Memory Footprint: 2357.13 MB
Model loaded successfully and moved to device.
Map:   0%|                                    | 0/209527 [00:00<?, ? examples/s]Model loaded successfully and moved to device.
Memory Footprint: 2357.13 MB
Model loaded successfully and moved to device.
Map: 100%|████████████████████| 209527/209527 [00:12<00:00, 16341.33 examples/s]
Map: 100%|████████████████████| 209527/209527 [00:13<00:00, 15597.01 examples/s]
Map: 100%|████████████████████| 209527/209527 [00:13<00:00, 15450.19 examples/s]
Map: 100%|████████████████████| 209527/209527 [00:13<00:00, 15173.37 examples/s]
Map: 100%|████████████████████| 209527/209527 [00:14<00:00, 14136.50 examples/s]
Map: 100%|████████████████████| 209527/209527 [00:15<00:00, 13799.99 examples/s]
Map: 100%|████████████████████| 209527/209527 [00:15<00:00, 13595.58 examples/s]
Map: 100%|████████████████████| 209527/209527 [00:15<00:00, 13684.65 examples/s]
Map: 100%|█████████████████████| 207431/207431 [02:20<00:00, 1475.35 examples/s]
Map: 100%|█████████████████████████| 2096/2096 [00:01<00:00, 1350.14 examples/s]
DatasetDict({
    train: Dataset({
        features: ['headline', 'category', 'short_description', 'text', 'text_gen', 'input_ids', 'attention_mask'],
        num_rows: 207431
    })
    test: Dataset({
        features: ['headline', 'category', 'short_description', 'text', 'text_gen', 'input_ids', 'attention_mask'],
        num_rows: 2096
    })
})
{'max_new_tokens': 40, 'temperature': 0.6, 'top_p': 0.5, 'top_k': 3, 'do_sample': True, 'repetition_penalty': 1.2, 'use_cache': True, 'min_new_tokens': 10, 'eos_token_id': 128009, 'pad_token_id': 128009}

--- Rank 0: Setting up DeepSpeed Pipeline ---
[2026-04-07 04:18:31,848] [INFO] [logging.py:107:log_dist] [Rank -1] DeepSpeed info: version=0.17.2, git-hash=unknown, git-branch=unknown
[2026-04-07 04:18:31,848] [INFO] [comm.py:676:init_distributed] cdb=None
[2026-04-07 04:18:31,848] [INFO] [comm.py:707:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
Map: 100%|█████████████████████| 207431/207431 [02:21<00:00, 1469.85 examples/s]
Map: 100%|█████████████████████| 207431/207431 [02:22<00:00, 1459.61 examples/s]
Map: 100%|█████████████████████████| 2096/2096 [00:01<00:00, 1357.70 examples/s]
DatasetDict({
    train: Dataset({
        features: ['headline', 'category', 'short_description', 'text', 'text_gen', 'input_ids', 'attention_mask'],
        num_rows: 207431
    })
    test: Dataset({
        features: ['headline', 'category', 'short_description', 'text', 'text_gen', 'input_ids', 'attention_mask'],
        num_rows: 2096
    })
})
{'max_new_tokens': 40, 'temperature': 0.6, 'top_p': 0.5, 'top_k': 3, 'do_sample': True, 'repetition_penalty': 1.2, 'use_cache': True, 'min_new_tokens': 10, 'eos_token_id': 128009, 'pad_token_id': 128009}

--- Rank 2: Setting up DeepSpeed Pipeline ---
[2026-04-07 04:18:33,572] [INFO] [logging.py:107:log_dist] [Rank -1] DeepSpeed info: version=0.17.2, git-hash=unknown, git-branch=unknown
[2026-04-07 04:18:33,572] [INFO] [comm.py:676:init_distributed] cdb=None
[2026-04-07 04:18:33,573] [INFO] [config.py:684:__init__] Config mesh_device None world_size = 4
Map: 100%|█████████████████████████| 2096/2096 [00:01<00:00, 1343.07 examples/s]
DatasetDict({
    train: Dataset({
        features: ['headline', 'category', 'short_description', 'text', 'text_gen', 'input_ids', 'attention_mask'],
        num_rows: 207431
    })
    test: Dataset({
        features: ['headline', 'category', 'short_description', 'text', 'text_gen', 'input_ids', 'attention_mask'],
        num_rows: 2096
    })
})
{'max_new_tokens': 40, 'temperature': 0.6, 'top_p': 0.5, 'top_k': 3, 'do_sample': True, 'repetition_penalty': 1.2, 'use_cache': True, 'min_new_tokens': 10, 'eos_token_id': 128009, 'pad_token_id': 128009}

--- Rank 3: Setting up DeepSpeed Pipeline ---
[2026-04-07 04:18:34,888] [INFO] [logging.py:107:log_dist] [Rank -1] DeepSpeed info: version=0.17.2, git-hash=unknown, git-branch=unknown
[2026-04-07 04:18:34,888] [INFO] [comm.py:676:init_distributed] cdb=None
[2026-04-07 04:18:34,890] [INFO] [config.py:684:__init__] Config mesh_device None world_size = 4
Map: 100%|█████████████████████| 207431/207431 [02:24<00:00, 1438.28 examples/s]
Map: 100%|█████████████████████████| 2096/2096 [00:01<00:00, 1363.70 examples/s]
DatasetDict({
    train: Dataset({
        features: ['headline', 'category', 'short_description', 'text', 'text_gen', 'input_ids', 'attention_mask'],
        num_rows: 207431
    })
    test: Dataset({
        features: ['headline', 'category', 'short_description', 'text', 'text_gen', 'input_ids', 'attention_mask'],
        num_rows: 2096
    })
})
{'max_new_tokens': 40, 'temperature': 0.6, 'top_p': 0.5, 'top_k': 3, 'do_sample': True, 'repetition_penalty': 1.2, 'use_cache': True, 'min_new_tokens': 10, 'eos_token_id': 128009, 'pad_token_id': 128009}

--- Rank 1: Setting up DeepSpeed Pipeline ---
[2026-04-07 04:18:36,944] [INFO] [logging.py:107:log_dist] [Rank -1] DeepSpeed info: version=0.17.2, git-hash=unknown, git-branch=unknown
[2026-04-07 04:18:36,945] [INFO] [comm.py:676:init_distributed] cdb=None
[2026-04-07 04:18:36,946] [INFO] [config.py:684:__init__] Config mesh_device None world_size = 4
[2026-04-07 04:18:36,956] [INFO] [config.py:684:__init__] Config mesh_device None world_size = 4
[2026-04-07 04:18:37,818] [INFO] [engine.py:1339:_configure_distributed_model] ********** distributed groups summary **********
	 self.dp_world_size=4
	 self.mp_world_size=1
	 self.seq_dp_world_size=4
	 self.sequence_parallel_size=1
***********************************************
[2026-04-07 04:18:38,593] [INFO] [logging.py:107:log_dist] [Rank 0] DeepSpeed Flops Profiler Enabled: False
[2026-04-07 04:18:38,594] [INFO] [logging.py:107:log_dist] [Rank 0] Using DeepSpeed Optimizer param name SGD as basic optimizer
[2026-04-07 04:18:38,594] [INFO] [logging.py:107:log_dist] [Rank 0] Removing param_group that has no 'params' in the basic Optimizer
[2026-04-07 04:18:38,599] [INFO] [logging.py:107:log_dist] [Rank 0] DeepSpeed Basic Optimizer = SGD
[2026-04-07 04:18:38,599] [INFO] [logging.py:107:log_dist] [Rank 0] Creating fp16 unfused optimizer with dynamic loss scale
[2026-04-07 04:18:38,599] [INFO] [unfused_optimizer.py:46:__init__] Fused Lamb Legacy : False
[2026-04-07 04:18:38,709] [INFO] [logging.py:107:log_dist] [Rank 0] DeepSpeed Final Optimizer = FP16_UnfusedOptimizer
[2026-04-07 04:18:38,709] [INFO] [logging.py:107:log_dist] [Rank 0] DeepSpeed using configured LR scheduler = None
[2026-04-07 04:18:38,709] [INFO] [logging.py:107:log_dist] [Rank 0] DeepSpeed LR Scheduler = None
[2026-04-07 04:18:38,709] [INFO] [logging.py:107:log_dist] [Rank 0] step=0, skipped=0, lr=[0.001], mom=[0]
[2026-04-07 04:18:38,710] [INFO] [logging.py:107:log_dist] [Rank 0] [TorchCheckpointEngine] Initialized with serialization = True
[2026-04-07 04:18:38,710] [INFO] [config.py:954:print] DeepSpeedEngine configuration:
[2026-04-07 04:18:38,710] [INFO] [config.py:958:print]   activation_checkpointing_config  {
    "partition_activations": false,
    "contiguous_memory_optimization": false,
    "cpu_checkpointing": false,
    "number_checkpoints": null,
    "synchronize_checkpoint_boundary": false,
    "profile": false
}
[2026-04-07 04:18:38,710] [INFO] [config.py:958:print]   aio_config ................... {'block_size': 1048576, 'queue_depth': 8, 'intra_op_parallelism': 1, 'single_submit': False, 'overlap_events': True, 'use_gds': False}
[2026-04-07 04:18:38,710] [INFO] [config.py:958:print]   amp_enabled .................. False
[2026-04-07 04:18:38,710] [INFO] [config.py:958:print]   amp_params ................... False
[2026-04-07 04:18:38,711] [INFO] [config.py:958:print]   autotuning_config ............ {
    "enabled": false,
    "start_step": null,
    "end_step": null,
    "metric_path": null,
    "arg_mappings": null,
    "metric": "throughput",
    "model_info": null,
    "results_dir": "autotuning_results",
    "exps_dir": "autotuning_exps",
    "overwrite": true,
    "fast": true,
    "start_profile_step": 3,
    "end_profile_step": 5,
    "tuner_type": "gridsearch",
    "tuner_early_stopping": 5,
    "tuner_num_trials": 50,
    "model_info_path": null,
    "mp_size": 1,
    "max_train_batch_size": null,
    "min_train_batch_size": 1,
    "max_train_micro_batch_size_per_gpu": 1.024000e+03,
    "min_train_micro_batch_size_per_gpu": 1,
    "num_tuning_micro_batch_sizes": 3
}
[2026-04-07 04:18:38,711] [INFO] [config.py:958:print]   bfloat16_config .............. enabled=False immediate_grad_update=False check_grad_overflow=False
[2026-04-07 04:18:38,711] [INFO] [config.py:958:print]   checkpoint_config ............ {'tag_validation': 'WARN', 'checkpoint_serialization': True, 'writer': None}

#### Tensor Parallelism

In [1]:
%%writefile lambda_tp_inference.py

import os
import torch
import torch.distributed as dist
import pandas as pd
from datasets import load_dataset, Dataset
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig
from evaluate import load as load_metric
import time
from pprint import pprint
import torch.nn.utils.prune as prune
from transformers import pipeline
import torch.nn as nn
import argparse

##Load dataset
def load_news_dataset():
    """TODO: Implement the data loading and preprocessing logic here."""
    import kagglehub
    # Download latest version
    path = kagglehub.dataset_download("rmisra/news-category-dataset")
    print("Path to dataset files:", path)
    import pandas as pd
    df = pd.read_json(path+'/News_Category_Dataset_v3.json', lines = True)
    print(f'Number of news items in each category\n####################################\n{df["category"].value_counts()}')
    print(f'###########################################################')
    print(f'Total number of news categories in dataset: {len(pd.DataFrame(df["category"].value_counts()))}')
    print(f'###########################################################')
    df_1 = df[['headline', 'category', 'short_description']].copy()
    news_ds = Dataset.from_pandas(df_1)
    #print(news_ds)
    return news_ds
    
##news_ds = load_news_dataset()

#from huggingface_hub import login
#login("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")

def get_model_memory_footprint(model):
    """Calculates and returns the model's memory footprint in MB."""
    mem_params = sum(param.nelement() * param.element_size() for param in model.parameters())
    mem_bufs = sum(buf.nelement() * buf.element_size() for buf in model.buffers())
    total_mem_bytes = mem_params + mem_bufs
    return total_mem_bytes / (1024 ** 2) # Convert bytes to MB

def load_model(MODEL_NAME, DEVICE, quantization_config=None):
    """TODO: Implement the logic for loading a tokenizer and model."""
    print("Loading tokenizer...")
    tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME,
                                              padding_side="left", 
                                              trust_remote_code= True
                                             )
    print("Tokenizer loaded successfully.")
    print("\nLoading model...")
    if quantization_config is None:
        model = AutoModelForCausalLM.from_pretrained(
            MODEL_NAME,
            torch_dtype=torch.float16,
            device_map= "auto",
            trust_remote_code =True
            ).to(DEVICE)
    else:
        model = AutoModelForCausalLM.from_pretrained(
            MODEL_NAME,
            quantization_config=quantization_config,
            device_map= "auto",
            trust_remote_code =True
            ).to(DEVICE)
    print("Model loaded successfully and moved to device.")
    memory_mb = get_model_memory_footprint(model)
    print(f"Memory Footprint: {memory_mb:.2f} MB")
  
    model.config.eos_token_id = tokenizer.eos_token_id
    tokenizer.pad_token = tokenizer.eos_token
    tokenizer.pad_token_id = tokenizer.eos_token_id
    model.config.pad_token_id = model.config.eos_token_id
    print("Model loaded successfully and moved to device.")
    model.eval()
    return tokenizer, model

#DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'
#MODEL_NAME = "meta-llama/Llama-3.2-1B-Instruct"
#Use DEVICE = balanced or auto
#tokenizer, model = load_model(MODEL_NAME, DEVICE, quantization_config=None)
#del model

def convert_chat_form_tokenize(tokenizer, ds):

    def base_format(sample):
        system_message = f'You are a news headline generator who generates catchy news headline from given news summary.\nGenerate a headline for following news summary of type: {sample["category"]}'
        messages = [
            {"role": 'system','content': system_message},
            {"role": 'user','content': sample["short_description"]},
            ]
        if generate_text:
            text_dict = {'text_gen': messages}
        else:
            messages.append({"role": 'assistant','content': sample["headline"]})
            text_dict = {'text': messages}
        return text_dict

    def apply_chat_temp(example):
        if generate_text:
            toks = tokenizer.apply_chat_template(example['text_gen'],tokenize=True, add_generation_prompt=True)
        else:
            toks = tokenizer.apply_chat_template(example['text'],tokenize=True)
        return toks

    generate_text = False
    ds = ds.map(base_format)
    #print(ds[0])

    generate_text = True
    ds = ds.map(base_format)
    #print(ds[0])

    tok_ds = ds.train_test_split(test_size=0.01, seed=42)
    
    generate_text = False
    tok_ds['train'] = tok_ds['train'].map(apply_chat_temp)
    #print(ds[0])

    #tok_ds = ds.train_test_split(test_size=0.01, seed=42)

    generate_text = True
    tok_ds['test'] = tok_ds['test'].map(apply_chat_temp)
    #print(tok_ds['test'][0])
    #print(tok_ds['train'][0], tok_ds['test'][0])
    return tok_ds

#tok_ds = convert_chat_form_tokenize(tokenizer, news_ds)
#print(tok_ds)

#MAX_NEW_TOKENS = 40

def generate_config(MAX_NEW_TOKENS, tokenizer, temperature=0.6, top_p=0.5, top_k=3, do_sample=True, use_cache=True):
    generation_config = {
        "max_new_tokens": MAX_NEW_TOKENS,
        "temperature": temperature,           # Controls randomness (lower = more deterministic)
        "top_p": top_p,                 # Nucleus sampling for diversity
        "top_k": top_k,                  # Limits candidates per step
        "do_sample": do_sample,            # Enables stochastic sampling
        # Repetition control
        "repetition_penalty": 1.2,    # Penalizes repeated tokens
        # Efficiency / inference tuning
        "use_cache": use_cache,            # Cache KV states for faster decoding
        # Optional advanced knobs
        "min_new_tokens": 10,         # Guarantees some output
        "eos_token_id": tokenizer.eos_token_id,
        "pad_token_id": tokenizer.pad_token_id,

        }
    return generation_config

#generation_args = generate_config(MAX_NEW_TOKENS)
#print(generation_args)

def base_format(sample):
    system_message = f'You are a news headline generator who generates catchy news headline from given news summary.\nGenerate a headline for following news summary of type: {sample["category"]}'
    messages = [
        {"role": 'system','content': system_message},
        {"role": 'user','content': sample["short_description"]},
        ]
    if generate_text:
        text_dict = {'text_gen': messages}
    else:
        messages.append({"role": 'assistant','content': sample["headline"]})
        text_dict = {'text': messages}
    return text_dict

def apply_chat_temp(tokenizer, example, generate_text=False):
    if generate_text:
        toks = tokenizer.apply_chat_template(example['text_gen'],tokenize=True, add_generation_prompt=True)
    else:
        toks = tokenizer.apply_chat_template(example['text'],tokenize=True)
    return toks

def cuda_warmup(model, toks, device, num_runs=1):
    for runs in range(num_runs):
        with torch.inference_mode():
            _ = model.generate(**toks, max_new_tokens=15)
        if device == "cuda":
            torch.cuda.synchronize()
    print("WarmUp runs completed")

import string

def remove_punctuation(text: str) -> str:
    # Create a translation table that maps punctuation to None
    translator = str.maketrans('', '', string.punctuation)
    return text.translate(translator)

def generate_headline(model, tokenizer, toks, device, generation_args):
    """TODO: Implement the headline generation and latency measurement logic."""
    t0 = time.perf_counter()
    with torch.inference_mode():
            outputs = model.generate(**toks, **generation_args)
    if device == 'cuda':
        torch.cuda.synchronize()
    t1 = time.perf_counter()
    latency = t1 - t0
    gen_len = outputs.shape[1] - toks["input_ids"].shape[1]
    peak_mem_mib = torch.cuda.max_memory_allocated(device) / 1024**2
    throughput = gen_len / latency if latency > 0 else float("nan")

    outputs_text = tokenizer.decode(outputs)
    outputs_text = remove_punctuation(outputs_text[0].split('<|start_header_id|>assistant<|end_header_id|>')[-1].split('<|eot_id|>')[0].strip())
    #print(outputs_text)
    peak_mem_mib = torch.cuda.max_memory_allocated(device) / 1024**2
    del model
    return latency, throughput, peak_mem_mib, outputs_text

def report_metrics(tok_ds, model, tokenizer, DEVICE, generation_args, exp, df):
    """TODO: Implement the logic for calculating and reporting all performance metrics."""
    avg_latency, avg_throughput, avg_peak_mib, rouge_score = evaluate_model(tok_ds, model, tokenizer, DEVICE, generation_args)
    new_df = pd.DataFrame({"EXP NAME": [exp], "Mean Latency (s)": [avg_latency], "Throughput (tokens/s)": [avg_throughput], "Avg Peak Mem": [avg_peak_mib], "ROUGE-1 Score": [rouge_score]}) 
    df = pd.concat([df, new_df], axis=0)
    return df

import random
import evaluate

def evaluate_model(dataset, model, tokenizer, device, generation_args, n=4):
    """TODO: Implement the model evaluation loop."""
    
    sample = random.sample(range(1000), 1)[0]
    warmup_example = dataset['train'][sample]
    toks = apply_chat_temp(tokenizer, warmup_example, generate_text=True)

    toks['input_ids'] = torch.tensor(toks['input_ids']).unsqueeze(0).to(device)
    toks['attention_mask'] = torch.tensor(toks['attention_mask']).unsqueeze(0).to(device)
    
    model.eval()
    cuda_warmup(model, toks, device)
    
    torch.cuda.reset_peak_memory_stats(device)
    samples = 100
    latencies = []
    throughputs = []
    peak_mem = []
    outputs = []
    references = []
    for i in range(n):
        for j in range(samples):
            sample = dataset['train'][j]
            references.append(sample['headline'])
            toks = apply_chat_temp(tokenizer, sample, generate_text=True)
            toks['input_ids'] = torch.tensor(toks['input_ids']).unsqueeze(0).to(device)
            toks['attention_mask'] = torch.tensor(toks['attention_mask']).unsqueeze(0).to(device)
            latency, throughput, peak_mem_mib, outputs_text = generate_headline(model, tokenizer, toks, device, generation_args)
            latencies.append(latency)
            throughputs.append(throughput)
            peak_mem.append(peak_mem_mib)
            outputs.append(outputs_text)
    
    rouge = evaluate.load("rouge")
    rouge_score = rouge.compute(predictions=outputs, references=references)['rouge1']
    avg_latency = sum(latencies) / len(latencies)
    avg_throughput = sum(throughputs) / len(throughputs)
    avg_peak_mib = sum(peak_mem)/len(peak_mem)
    print(avg_latency, avg_throughput, avg_peak_mib, rouge_score)
    return avg_latency, avg_throughput, avg_peak_mib, rouge_score

import copy
import torch.nn as nn
def prune_model_weights(model, amount=0.3):
    """TODO: Applies L1 unstructured pruning to the linear layers of a model."""
    pruned_model = copy.deepcopy(model)
    for name, module in pruned_model.named_modules():
        if isinstance(module, nn.Linear):
            prune.l1_unstructured(module, name="weight", amount=amount)
            prune.remove(module, "weight")
    print("Model pruned successfully")
    return pruned_model

# TODO: Establish your baseline performance.
#load the original model and establish baseline performance using functions defined above
def run_exp(exp, df, tok_ds, MODEL_NAME, DEVICE, generation_args, quantization_config=None, prune=False ):

    print("Running experiment now....", exp, "#######")

    tokenizer, model = load_model(MODEL_NAME, DEVICE, quantization_config=quantization_config)
    if prune:
        model = prune_model_weights(model, amount=0.3)        
    df = report_metrics(tok_ds, model, tokenizer, DEVICE, generation_args, exp, df)
    return df

# --- Main Execution Logic ---


def main():

    os.environ["RANK"] = "0"
    os.environ["WORLD_SIZE"] = "1" # Use >1 if multi-GPU

    from huggingface_hub import login
    login("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")

    # 2. Initialize the distributed backend
    if not dist.is_initialized():
        dist.init_process_group(backend="nccl") # Use "gloo" for CPU-only

        
    model_id = "meta-llama/Llama-3.2-1B-Instruct"
    DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'

    #########################################################
    print("#################################################################")
    print("Calling from main script")
    print("#################################################################")
    news_ds = load_news_dataset()
    from huggingface_hub import login
    login("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")

    rank = int(os.environ.get("RANK", 0))
    world_size = int(os.environ.get("WORLD_SIZE", 1))
    
    if rank == 0:
        print(f"Loading {model_id} with TP across {world_size} GPUs...")
        start_time = time.time()
    
    model = AutoModelForCausalLM.from_pretrained(
        model_id,
        torch_dtype=torch.float16,
        tp_plan="auto"
    )
    
    if rank == 0:
        load_time = time.time() - start_time
        print(f"Model loaded in {load_time:.2f}s")
    
    tokenizer = AutoTokenizer.from_pretrained(model_id)
    tokenizer.pad_token = tokenizer.eos_token

    #if rank == 0:
    tok_ds = convert_chat_form_tokenize(tokenizer, news_ds)
    print(tok_ds)
    MAX_NEW_TOKENS = 40
    generation_args = generate_config(MAX_NEW_TOKENS, tokenizer)
    print(generation_args)
    ################################################################

    df = pd.DataFrame()
    exp = "Tensor Parallelism 4 GPU"
    print("Running Ternsor parallelism at the end of script and main function")
    df = report_metrics(tok_ds, model, tokenizer, DEVICE, generation_args, exp, df)
    print(df)
    df.to_csv("tp.csv")
    return df 
    

if __name__ == "__main__":
    main()

Writing lambda_tp_inference.py

In [9]:
!torchrun --nproc-per-node 1 lambda_tp_inference.py

/home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/torch/cuda/__init__.py:61: FutureWarning: The pynvml package is deprecated. Please install nvidia-ml-py instead. If you did not install pynvml directly, please report this to the maintainers of the package that installed pynvml for you.
  import pynvml  # type: ignore[import]
/home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/torch/cuda/__init__.py:61: FutureWarning: The pynvml package is deprecated. Please install nvidia-ml-py instead. If you did not install pynvml directly, please report this to the maintainers of the package that installed pynvml for you.
  import pynvml  # type: ignore[import]
#################################################################
Calling from main script
#################################################################
Path to dataset files: /home/ec2-user/.cache/kagglehub/datasets/rmisra/news-category-dataset/versions/3
Number of news items in each category
####################################
category
POLITICS          35602
WELLNESS          17945
ENTERTAINMENT     17362
TRAVEL             9900
STYLE & BEAUTY     9814
PARENTING          8791
HEALTHY LIVING     6694
QUEER VOICES       6347
FOOD & DRINK       6340
BUSINESS           5992
COMEDY             5400
SPORTS             5077
BLACK VOICES       4583
HOME & LIVING      4320
PARENTS            3955
THE WORLDPOST      3664
WEDDINGS           3653
WOMEN              3572
CRIME              3562
IMPACT             3484
DIVORCE            3426
WORLD NEWS         3299
MEDIA              2944
WEIRD NEWS         2777
GREEN              2622
WORLDPOST          2579
RELIGION           2577
STYLE              2254
SCIENCE            2206
TECH               2104
TASTE              2096
MONEY              1756
ARTS               1509
ENVIRONMENT        1444
FIFTY              1401
GOOD NEWS          1398
U.S. NEWS          1377
ARTS & CULTURE     1339
COLLEGE            1144
LATINO VOICES      1130
CULTURE & ARTS     1074
EDUCATION          1014
Name: count, dtype: int64
###########################################################
Total number of news categories in dataset: 42
###########################################################
Loading meta-llama/Llama-3.2-1B-Instruct with TP across 1 GPUs...
`torch_dtype` is deprecated! Use `dtype` instead!
Loading weights: 100%|███████████████████████| 146/146 [00:00<00:00, 241.84it/s]
Model loaded in 1.17s
Map: 100%|████████████████████| 209527/209527 [00:11<00:00, 17825.33 examples/s]
Map: 100%|████████████████████| 209527/209527 [00:13<00:00, 15935.62 examples/s]
Map: 100%|█████████████████████| 207431/207431 [01:49<00:00, 1899.24 examples/s]
Map: 100%|█████████████████████████| 2096/2096 [00:00<00:00, 2127.80 examples/s]
DatasetDict({
    train: Dataset({
        features: ['headline', 'category', 'short_description', 'text', 'text_gen', 'input_ids', 'attention_mask'],
        num_rows: 207431
    })
    test: Dataset({
        features: ['headline', 'category', 'short_description', 'text', 'text_gen', 'input_ids', 'attention_mask'],
        num_rows: 2096
    })
})
{'max_new_tokens': 40, 'temperature': 0.6, 'top_p': 0.5, 'top_k': 3, 'do_sample': True, 'repetition_penalty': 1.2, 'use_cache': False, 'min_new_tokens': 10, 'eos_token_id': 128009, 'pad_token_id': 128009}
Running Ternsor parallelism at the end of script and main function
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
WarmUp runs completed
0.4938963371674947 54.46839414369398 2377.586740722656 0.09444973477188962
                   EXP NAME  Mean Latency (s)  ...  Avg Peak Mem  ROUGE-1 Score
0  Tensor Parallelism 4 GPU          0.493896  ...   2377.586741        0.09445

[1 rows x 5 columns]
[rank0]:[W406 06:41:42.656568559 ProcessGroupNCCL.cpp:1496] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

In [2]:
!torchrun --nproc-per-node 4 lambda_tp_inference.py

/home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/torch/cuda/__init__.py:61: FutureWarning: The pynvml package is deprecated. Please install nvidia-ml-py instead. If you did not install pynvml directly, please report this to the maintainers of the package that installed pynvml for you.
  import pynvml  # type: ignore[import]
W0407 04:25:03.887000 4605 site-packages/torch/distributed/run.py:792]
W0407 04:25:03.887000 4605 site-packages/torch/distributed/run.py:792] *****************************************
W0407 04:25:03.887000 4605 site-packages/torch/distributed/run.py:792] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
W0407 04:25:03.887000 4605 site-packages/torch/distributed/run.py:792] *****************************************
/home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/torch/cuda/__init__.py:61: FutureWarning: The pynvml package is deprecated. Please install nvidia-ml-py instead. If you did not install pynvml directly, please report this to the maintainers of the package that installed pynvml for you.
  import pynvml  # type: ignore[import]
/home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/torch/cuda/__init__.py:61: FutureWarning: The pynvml package is deprecated. Please install nvidia-ml-py instead. If you did not install pynvml directly, please report this to the maintainers of the package that installed pynvml for you.
  import pynvml  # type: ignore[import]
/home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/torch/cuda/__init__.py:61: FutureWarning: The pynvml package is deprecated. Please install nvidia-ml-py instead. If you did not install pynvml directly, please report this to the maintainers of the package that installed pynvml for you.
  import pynvml  # type: ignore[import]
/home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/torch/cuda/__init__.py:61: FutureWarning: The pynvml package is deprecated. Please install nvidia-ml-py instead. If you did not install pynvml directly, please report this to the maintainers of the package that installed pynvml for you.
  import pynvml  # type: ignore[import]
#################################################################
Calling from main script
#################################################################
#################################################################
Calling from main script
#################################################################
#################################################################
Calling from main script
#################################################################
#################################################################
Calling from main script
#################################################################
Path to dataset files: /home/ec2-user/.cache/kagglehub/datasets/rmisra/news-category-dataset/versions/3
Path to dataset files: /home/ec2-user/.cache/kagglehub/datasets/rmisra/news-category-dataset/versions/3
Path to dataset files: /home/ec2-user/.cache/kagglehub/datasets/rmisra/news-category-dataset/versions/3
Path to dataset files: /home/ec2-user/.cache/kagglehub/datasets/rmisra/news-category-dataset/versions/3
Number of news items in each category
####################################
category
POLITICS          35602
WELLNESS          17945
ENTERTAINMENT     17362
TRAVEL             9900
STYLE & BEAUTY     9814
PARENTING          8791
HEALTHY LIVING     6694
QUEER VOICES       6347
FOOD & DRINK       6340
BUSINESS           5992
COMEDY             5400
SPORTS             5077
BLACK VOICES       4583
HOME & LIVING      4320
PARENTS            3955
THE WORLDPOST      3664
WEDDINGS           3653
WOMEN              3572
CRIME              3562
IMPACT             3484
DIVORCE            3426
WORLD NEWS         3299
MEDIA              2944
WEIRD NEWS         2777
GREEN              2622
WORLDPOST          2579
RELIGION           2577
STYLE              2254
SCIENCE            2206
TECH               2104
TASTE              2096
MONEY              1756
ARTS               1509
ENVIRONMENT        1444
FIFTY              1401
GOOD NEWS          1398
U.S. NEWS          1377
ARTS & CULTURE     1339
COLLEGE            1144
LATINO VOICES      1130
CULTURE & ARTS     1074
EDUCATION          1014
Name: count, dtype: int64
###########################################################
Total number of news categories in dataset: 42
###########################################################
Number of news items in each category
####################################
category
POLITICS          35602
WELLNESS          17945
ENTERTAINMENT     17362
TRAVEL             9900
STYLE & BEAUTY     9814
PARENTING          8791
HEALTHY LIVING     6694
QUEER VOICES       6347
FOOD & DRINK       6340
BUSINESS           5992
COMEDY             5400
SPORTS             5077
BLACK VOICES       4583
HOME & LIVING      4320
PARENTS            3955
THE WORLDPOST      3664
WEDDINGS           3653
WOMEN              3572
CRIME              3562
IMPACT             3484
DIVORCE            3426
WORLD NEWS         3299
MEDIA              2944
WEIRD NEWS         2777
GREEN              2622
WORLDPOST          2579
RELIGION           2577
STYLE              2254
SCIENCE            2206
TECH               2104
TASTE              2096
MONEY              1756
ARTS               1509
ENVIRONMENT        1444
FIFTY              1401
GOOD NEWS          1398
U.S. NEWS          1377
ARTS & CULTURE     1339
COLLEGE            1144
LATINO VOICES      1130
CULTURE & ARTS     1074
EDUCATION          1014
Name: count, dtype: int64
###########################################################
Total number of news categories in dataset: 42
###########################################################
Number of news items in each category
####################################
category
POLITICS          35602
WELLNESS          17945
ENTERTAINMENT     17362
TRAVEL             9900
STYLE & BEAUTY     9814
PARENTING          8791
HEALTHY LIVING     6694
QUEER VOICES       6347
FOOD & DRINK       6340
BUSINESS           5992
COMEDY             5400
SPORTS             5077
BLACK VOICES       4583
HOME & LIVING      4320
PARENTS            3955
THE WORLDPOST      3664
WEDDINGS           3653
WOMEN              3572
CRIME              3562
IMPACT             3484
DIVORCE            3426
WORLD NEWS         3299
MEDIA              2944
WEIRD NEWS         2777
GREEN              2622
WORLDPOST          2579
RELIGION           2577
STYLE              2254
SCIENCE            2206
TECH               2104
TASTE              2096
MONEY              1756
ARTS               1509
ENVIRONMENT        1444
FIFTY              1401
GOOD NEWS          1398
U.S. NEWS          1377
ARTS & CULTURE     1339
COLLEGE            1144
LATINO VOICES      1130
CULTURE & ARTS     1074
EDUCATION          1014
Name: count, dtype: int64
###########################################################
Number of news items in each category
####################################
category
POLITICS          35602
WELLNESS          17945
ENTERTAINMENT     17362
TRAVEL             9900
STYLE & BEAUTY     9814
PARENTING          8791
HEALTHY LIVING     6694
QUEER VOICES       6347
FOOD & DRINK       6340
BUSINESS           5992
COMEDY             5400
SPORTS             5077
BLACK VOICES       4583
HOME & LIVING      4320
PARENTS            3955
THE WORLDPOST      3664
WEDDINGS           3653
WOMEN              3572
CRIME              3562
IMPACT             3484
DIVORCE            3426
WORLD NEWS         3299
MEDIA              2944
WEIRD NEWS         2777
GREEN              2622
WORLDPOST          2579
RELIGION           2577
STYLE              2254
SCIENCE            2206
TECH               2104
TASTE              2096
MONEY              1756
ARTS               1509
ENVIRONMENT        1444
FIFTY              1401
GOOD NEWS          1398
U.S. NEWS          1377
ARTS & CULTURE     1339
COLLEGE            1144
LATINO VOICES      1130
CULTURE & ARTS     1074
EDUCATION          1014
Name: count, dtype: int64
###########################################################
Total number of news categories in dataset: 42
###########################################################
Total number of news categories in dataset: 42
###########################################################
Loading meta-llama/Llama-3.2-1B-Instruct with TP across 1 GPUs...
Loading meta-llama/Llama-3.2-1B-Instruct with TP across 1 GPUs...
Loading meta-llama/Llama-3.2-1B-Instruct with TP across 1 GPUs...
Loading meta-llama/Llama-3.2-1B-Instruct with TP across 1 GPUs...
`torch_dtype` is deprecated! Use `dtype` instead!
`torch_dtype` is deprecated! Use `dtype` instead!
`torch_dtype` is deprecated! Use `dtype` instead!
`torch_dtype` is deprecated! Use `dtype` instead!
Loading weights: 100%|███████████████████████| 146/146 [00:01<00:00, 143.96it/s]
Loading weights: 100%|███████████████████████| 146/146 [00:00<00:00, 146.66it/s]
Loading weights: 100%|███████████████████████| 146/146 [00:01<00:00, 144.77it/s]
Model loaded in 1.86s
Loading weights: 100%|███████████████████████| 146/146 [00:01<00:00, 144.14it/s]
Model loaded in 1.89s
Model loaded in 1.91s
Model loaded in 1.96s
Map: 100%|████████████████████| 209527/209527 [00:12<00:00, 16119.71 examples/s]
Map: 100%|████████████████████| 209527/209527 [00:13<00:00, 16083.48 examples/s]
Map: 100%|████████████████████| 209527/209527 [00:13<00:00, 15883.40 examples/s]
Map: 100%|████████████████████| 209527/209527 [00:16<00:00, 13016.60 examples/s]
Map: 100%|████████████████████| 209527/209527 [00:15<00:00, 13809.35 examples/s]
Map: 100%|████████████████████| 209527/209527 [00:15<00:00, 13808.60 examples/s]
Map: 100%|████████████████████| 209527/209527 [00:15<00:00, 13776.54 examples/s]
Map: 100%|████████████████████| 209527/209527 [00:17<00:00, 11874.98 examples/s]
Map: 100%|█████████████████████| 207431/207431 [02:21<00:00, 1465.06 examples/s]
Map: 100%|█████████████████████████| 2096/2096 [00:01<00:00, 1619.76 examples/s]
Map: 100%|█████████████████████| 207431/207431 [02:23<00:00, 1448.92 examples/s]
DatasetDict({
    train: Dataset({
        features: ['headline', 'category', 'short_description', 'text', 'text_gen', 'input_ids', 'attention_mask'],
        num_rows: 207431
    })
    test: Dataset({
        features: ['headline', 'category', 'short_description', 'text', 'text_gen', 'input_ids', 'attention_mask'],
        num_rows: 2096
    })
})
{'max_new_tokens': 40, 'temperature': 0.6, 'top_p': 0.5, 'top_k': 3, 'do_sample': True, 'repetition_penalty': 1.2, 'use_cache': False, 'min_new_tokens': 10, 'eos_token_id': 128009, 'pad_token_id': 128009}
Running Ternsor parallelism at the end of script and main function
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Map: 100%|████████████████████▉| 207158/207431 [02:23<00:00, 1349.37 examples/s]WarmUp runs completed
Map: 100%|█████████████████████| 207431/207431 [02:24<00:00, 1439.65 examples/s]
Map: 100%|█████████████████████████| 2096/2096 [00:01<00:00, 1608.28 examples/s]
DatasetDict({
    train: Dataset({
        features: ['headline', 'category', 'short_description', 'text', 'text_gen', 'input_ids', 'attention_mask'],
        num_rows: 207431
    })
    test: Dataset({
        features: ['headline', 'category', 'short_description', 'text', 'text_gen', 'input_ids', 'attention_mask'],
        num_rows: 2096
    })
})
{'max_new_tokens': 40, 'temperature': 0.6, 'top_p': 0.5, 'top_k': 3, 'do_sample': True, 'repetition_penalty': 1.2, 'use_cache': False, 'min_new_tokens': 10, 'eos_token_id': 128009, 'pad_token_id': 128009}
Running Ternsor parallelism at the end of script and main function
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Map:  93%|███████████████████▌ | 192765/207431 [02:19<00:10, 1341.51 examples/s]WarmUp runs completed
Map: 100%|█████████████████████████| 2096/2096 [00:01<00:00, 1581.92 examples/s]
DatasetDict({
    train: Dataset({
        features: ['headline', 'category', 'short_description', 'text', 'text_gen', 'input_ids', 'attention_mask'],
        num_rows: 207431
    })
    test: Dataset({
        features: ['headline', 'category', 'short_description', 'text', 'text_gen', 'input_ids', 'attention_mask'],
        num_rows: 2096
    })
})
{'max_new_tokens': 40, 'temperature': 0.6, 'top_p': 0.5, 'top_k': 3, 'do_sample': True, 'repetition_penalty': 1.2, 'use_cache': False, 'min_new_tokens': 10, 'eos_token_id': 128009, 'pad_token_id': 128009}
Running Ternsor parallelism at the end of script and main function
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Map:  94%|███████████████████▋ | 193992/207431 [02:20<00:09, 1485.27 examples/s]WarmUp runs completed
Map: 100%|█████████████████████| 207431/207431 [02:30<00:00, 1379.13 examples/s]
Map: 100%|█████████████████████████| 2096/2096 [00:01<00:00, 1545.99 examples/s]
DatasetDict({
    train: Dataset({
        features: ['headline', 'category', 'short_description', 'text', 'text_gen', 'input_ids', 'attention_mask'],
        num_rows: 207431
    })
    test: Dataset({
        features: ['headline', 'category', 'short_description', 'text', 'text_gen', 'input_ids', 'attention_mask'],
        num_rows: 2096
    })
})
{'max_new_tokens': 40, 'temperature': 0.6, 'top_p': 0.5, 'top_k': 3, 'do_sample': True, 'repetition_penalty': 1.2, 'use_cache': False, 'min_new_tokens': 10, 'eos_token_id': 128009, 'pad_token_id': 128009}
Running Ternsor parallelism at the end of script and main function
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
WarmUp runs completed
0.7154424853399951 37.64053832355934 2382.9565637207033 0.09127465882629959
                   EXP NAME  Mean Latency (s)  ...  Avg Peak Mem  ROUGE-1 Score
0  Tensor Parallelism 4 GPU          0.715442  ...   2382.956564       0.091275

[1 rows x 5 columns]
[rank0]:[W407 04:32:56.014625343 ProcessGroupNCCL.cpp:1496] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())
0.7185768176200145 37.28388292582347 2383.252028808594 0.09794980047234508
                   EXP NAME  Mean Latency (s)  ...  Avg Peak Mem  ROUGE-1 Score
0  Tensor Parallelism 4 GPU          0.718577  ...   2383.252029        0.09795

[1 rows x 5 columns]
[rank0]:[W407 04:32:58.760143286 ProcessGroupNCCL.cpp:1496] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())
0.7203809590575065 37.10292274987659 2383.39431640625 0.09363504535566702
                   EXP NAME  Mean Latency (s)  ...  Avg Peak Mem  ROUGE-1 Score
0  Tensor Parallelism 4 GPU          0.720381  ...   2383.394316       0.093635

[1 rows x 5 columns]
[rank0]:[W407 04:33:00.467417382 ProcessGroupNCCL.cpp:1496] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())
0.8739954969274959 30.658989606902974 2383.1371069335937 0.0956257767694808
                   EXP NAME  Mean Latency (s)  ...  Avg Peak Mem  ROUGE-1 Score
0  Tensor Parallelism 4 GPU          0.873995  ...   2383.137107       0.095626

[1 rows x 5 columns]
[rank0]:[W407 04:34:14.960178581 ProcessGroupNCCL.cpp:1496] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

In [1]:
%%writefile deepspeed_pipeline_script.py

import os
import torch
import pandas as pd
import numpy as np
from datasets import load_dataset, Dataset
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig
from evaluate import load as load_metric
import time
from pprint import pprint
import torch.nn.utils.prune as prune
from transformers import pipeline
import torch.nn as nn
import deepspeed
import argparse
import accelerate
from huggingface_hub import login
import copy

##Load dataset
def load_news_dataset():
    """TODO: Implement the data loading and preprocessing logic here."""
    import kagglehub
    # Download latest version
    path = kagglehub.dataset_download("rmisra/news-category-dataset")
    print("Path to dataset files:", path)
    import pandas as pd
    df = pd.read_json(path+'/News_Category_Dataset_v3.json', lines = True)
    print(f'Number of news items in each category\n####################################\n{df["category"].value_counts()}')
    print(f'###########################################################')
    print(f'Total number of news categories in dataset: {len(pd.DataFrame(df["category"].value_counts()))}')
    print(f'###########################################################')
    df_1 = df[['headline', 'category', 'short_description']].copy()
    news_ds = Dataset.from_pandas(df_1)
    #print(news_ds)
    return news_ds
    
def convert_chat_form_tokenize(tokenizer, ds):

    def base_format(sample):
        system_message = f'You are a news headline generator who generates catchy news headline from given news summary.\nGenerate a headline for following news summary of type: {sample["category"]}'
        messages = [
            {"role": 'system','content': system_message},
            {"role": 'user','content': sample["short_description"]},
            ]
        if generate_text:
            text_dict = {'text_gen': messages}
        else:
            messages.append({"role": 'assistant','content': sample["headline"]})
            text_dict = {'text': messages}
        return text_dict

    def apply_chat_temp(example):
        if generate_text:
            toks = tokenizer.apply_chat_template(example['text_gen'],tokenize=True, add_generation_prompt=True)
        else:
            toks = tokenizer.apply_chat_template(example['text'],tokenize=True)
        return toks

    generate_text = False
    ds = ds.map(base_format)
    #print(ds[0])

    generate_text = True
    ds = ds.map(base_format)
    #print(ds[0])

    tok_ds = ds.train_test_split(test_size=0.01, seed=42)
    
    generate_text = False
    tok_ds['train'] = tok_ds['train'].map(apply_chat_temp)
    #print(ds[0])

    #tok_ds = ds.train_test_split(test_size=0.01, seed=42)

    generate_text = True
    tok_ds['test'] = tok_ds['test'].map(apply_chat_temp)
    #print(tok_ds['test'][0])
    #print(tok_ds['train'][0], tok_ds['test'][0])
    return tok_ds

def generate_config(MAX_NEW_TOKENS, tokenizer, temperature=0.6, top_p=0.5, top_k=3, do_sample=True, use_cache=True):
    generation_config = {
        "max_new_tokens": MAX_NEW_TOKENS,
        "temperature": temperature,           # Controls randomness (lower = more deterministic)
        "top_p": top_p,                 # Nucleus sampling for diversity
        "top_k": top_k,                  # Limits candidates per step
        "do_sample": do_sample,            # Enables stochastic sampling
        # Repetition control
        "repetition_penalty": 1.2,    # Penalizes repeated tokens
        # Efficiency / inference tuning
        "use_cache": use_cache,            # Cache KV states for faster decoding
        # Optional advanced knobs
        "min_new_tokens": 10,         # Guarantees some output
        "eos_token_id": tokenizer.eos_token_id,
        "pad_token_id": tokenizer.pad_token_id,

        }
    return generation_config

#generation_args = generate_config(MAX_NEW_TOKENS)
#print(generation_args)

def base_format(sample):
    system_message = f'You are a news headline generator who generates catchy news headline from given news summary.\nGenerate a headline for following news summary of type: {sample["category"]}'
    messages = [
        {"role": 'system','content': system_message},
        {"role": 'user','content': sample["short_description"]},
        ]
    if generate_text:
        text_dict = {'text_gen': messages}
    else:
        messages.append({"role": 'assistant','content': sample["headline"]})
        text_dict = {'text': messages}
    return text_dict

def apply_chat_temp(tokenizer, example, generate_text=False):
    if generate_text:
        toks = tokenizer.apply_chat_template(example['text_gen'], tokenize=False, add_generation_prompt=True)
    else:
        toks = tokenizer.apply_chat_template(example['text'])
    return toks

import string

def remove_punctuation(text: str) -> str:
    # Create a translation table that maps punctuation to None
    translator = str.maketrans('', '', string.punctuation)
    return text.translate(translator)

def generate_headline(generator, tokenizer, toks, device, generation_args):
    """TODO: Implement the headline generation and latency measurement logic."""
    t0 = time.perf_counter()
    with torch.inference_mode():
        outputs = generator(toks, **generation_args)[0]['generated_text']
    torch.cuda.synchronize()
    t1 = time.perf_counter()
    latency = t1 - t0
    
    toks_inputids = len(tokenizer(toks)["input_ids"])
    outputs_input_ids = len(tokenizer(outputs)["input_ids"])
    gen_len = outputs_input_ids - toks_inputids
    peak_mem_mib = torch.cuda.max_memory_allocated(generator.device) / 1024**2
    throughput = gen_len / latency if latency > 0 else float("nan")

    outputs_text = remove_punctuation(outputs.split('<|start_header_id|>assistant<|end_header_id|>')[-1]).strip()
    #print(outputs_text)
    return latency, throughput, peak_mem_mib, outputs_text

def report_metrics(tok_ds, model, tokenizer, DEVICE, generation_args, exp, df):
    """TODO: Implement the logic for calculating and reporting all performance metrics."""
    avg_latency, avg_throughput, avg_peak_mib, rouge_score = evaluate_model(tok_ds, model, tokenizer, DEVICE, generation_args)
    new_df = pd.DataFrame({"EXP NAME": [exp], "Mean Latency (s)": [avg_latency], "Throughput (tokens/s)": [avg_throughput], "Avg Peak Mem": [avg_peak_mib], "ROUGE-1 Score": [rouge_score]}) 
    df = pd.concat([df, new_df], axis=0)
    return df

import random
import evaluate

def evaluate_model(dataset, model, tokenizer, device, generation_args, n=4):
    """TODO: Implement the model evaluation loop."""
    
    torch.cuda.reset_peak_memory_stats(model.device)
    samples = 100
    latencies = []
    throughputs = []
    peak_mem = []
    outputs = []
    references = []
    for i in range(n):
        for j in range(samples):
            sample = dataset['train'][j]
            references.append(sample['headline'])
            toks = apply_chat_temp(tokenizer, sample, generate_text=True)
            latency, throughput, peak_mem_mib, outputs_text = generate_headline(model, tokenizer, toks, device, generation_args)
            latencies.append(latency)
            throughputs.append(throughput)
            peak_mem.append(peak_mem_mib)
            outputs.append(outputs_text)
    
    rouge = evaluate.load("rouge")
    rouge_score = rouge.compute(predictions=outputs, references=references)['rouge1']
    avg_latency = sum(latencies) / len(latencies)
    avg_throughput = sum(throughputs) / len(throughputs)
    avg_peak_mib = sum(peak_mem)/len(peak_mem)
    print(avg_latency, avg_throughput, avg_peak_mib, rouge_score)
    return avg_latency, avg_throughput, avg_peak_mib, rouge_score



def main():
    
    model_name = "meta-llama/Llama-3.2-1B-Instruct"
    tokenizer = AutoTokenizer.from_pretrained(model_name)
    tokenizer.pad_token = tokenizer.eos_token
    DEVICE = 'cuda'
    #########################################################
    print("#################################################################")
    print("Calling from main script")
    print("#################################################################")
    news_ds = load_news_dataset()
    tok_ds = convert_chat_form_tokenize(tokenizer, news_ds)
    print(tok_ds)
    MAX_NEW_TOKENS = 40
    generation_args = generate_config(MAX_NEW_TOKENS, tokenizer)
    print(generation_args)
    ###########################################################
    
    local_rank = int(os.getenv('LOCAL_RANK', '0'))
    world_size = int(os.getenv('WORLD_SIZE', '1'))
    generator = pipeline('text-generation', model=model_name, device=local_rank)
    generator.model = deepspeed.init_inference(generator.model,
                                               tensor_parallel={"tp_size": world_size},
                                               dtype=torch.float16,
                                               replace_with_kernel_inject=False)
    
    df = pd.DataFrame()
    exp = "DeepSpeed Parallelism 4 GPU"
    print("Running DeepSpeed parallelism at the end of script and main function")
    df = report_metrics(tok_ds, generator, tokenizer, DEVICE, generation_args, exp, df)
    
    if not torch.distributed.is_initialized() or torch.distributed.get_rank() == 0:
        print(df)
        df.to_csv("tp_deepspeed.csv")
        print("stats written to tp_deepspeed.csv")
  
if __name__ == "__main__":
    main()

Overwriting deepspeed_pipeline_script.py

In [2]:
print("🚀 Launching DeepSpeed Pipeline Parallelism Experiment...")
!DS_LOG_LEVEL=ERROR PYTHONWARNINGS=ignore deepspeed --num_gpus 4 deepspeed_pipeline_script.py

🚀 Launching DeepSpeed Pipeline Parallelism Experiment...
[2026-04-07 06:05:11,103] [INFO] [real_accelerator.py:254:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2026-04-07 06:05:15,257] [INFO] [logging.py:107:log_dist] [Rank -1] [TorchCheckpointEngine] Initialized with serialization = False
[2026-04-07 06:05:16,654] [WARNING] [runner.py:220:fetch_hostfile] Unable to find hostfile, will proceed with training with local resources only.
[2026-04-07 06:05:16,654] [INFO] [runner.py:610:main] cmd = /home/ec2-user/anaconda3/envs/pytorch_p310/bin/python3.10 -u -m deepspeed.launcher.launch --world_info=eyJsb2NhbGhvc3QiOiBbMCwgMSwgMiwgM119 --master_addr=127.0.0.1 --master_port=29500 --enable_each_rank_log=None deepspeed_pipeline_script.py
[2026-04-07 06:05:18,451] [INFO] [real_accelerator.py:254:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2026-04-07 06:05:22,598] [INFO] [logging.py:107:log_dist] [Rank -1] [TorchCheckpointEngine] Initialized with serialization = False
[2026-04-07 06:05:23,978] [INFO] [launch.py:146:main] WORLD INFO DICT: {'localhost': [0, 1, 2, 3]}
[2026-04-07 06:05:23,978] [INFO] [launch.py:152:main] nnodes=1, num_local_procs=4, node_rank=0
[2026-04-07 06:05:23,979] [INFO] [launch.py:163:main] global_rank_mapping=defaultdict(<class 'list'>, {'localhost': [0, 1, 2, 3]})
[2026-04-07 06:05:23,979] [INFO] [launch.py:164:main] dist_world_size=4
[2026-04-07 06:05:23,979] [INFO] [launch.py:168:main] Setting CUDA_VISIBLE_DEVICES=0,1,2,3
[2026-04-07 06:05:23,979] [INFO] [launch.py:256:main] process 1526 spawned with command: ['/home/ec2-user/anaconda3/envs/pytorch_p310/bin/python3.10', '-u', 'deepspeed_pipeline_script.py', '--local_rank=0']
[2026-04-07 06:05:23,979] [INFO] [launch.py:256:main] process 1527 spawned with command: ['/home/ec2-user/anaconda3/envs/pytorch_p310/bin/python3.10', '-u', 'deepspeed_pipeline_script.py', '--local_rank=1']
[2026-04-07 06:05:23,980] [INFO] [launch.py:256:main] process 1528 spawned with command: ['/home/ec2-user/anaconda3/envs/pytorch_p310/bin/python3.10', '-u', 'deepspeed_pipeline_script.py', '--local_rank=2']
[2026-04-07 06:05:23,980] [INFO] [launch.py:256:main] process 1529 spawned with command: ['/home/ec2-user/anaconda3/envs/pytorch_p310/bin/python3.10', '-u', 'deepspeed_pipeline_script.py', '--local_rank=3']
[2026-04-07 06:05:29,821] [INFO] [real_accelerator.py:254:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2026-04-07 06:05:29,852] [INFO] [real_accelerator.py:254:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2026-04-07 06:05:29,854] [INFO] [real_accelerator.py:254:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2026-04-07 06:05:29,866] [INFO] [real_accelerator.py:254:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2026-04-07 06:05:32,043] [INFO] [logging.py:107:log_dist] [Rank -1] [TorchCheckpointEngine] Initialized with serialization = False
[2026-04-07 06:05:32,056] [INFO] [logging.py:107:log_dist] [Rank -1] [TorchCheckpointEngine] Initialized with serialization = False
[2026-04-07 06:05:32,066] [INFO] [logging.py:107:log_dist] [Rank -1] [TorchCheckpointEngine] Initialized with serialization = False
[2026-04-07 06:05:32,070] [INFO] [logging.py:107:log_dist] [Rank -1] [TorchCheckpointEngine] Initialized with serialization = False
#################################################################
Calling from main script
#################################################################
#################################################################
Calling from main script
#################################################################
#################################################################
Calling from main script
#################################################################
#################################################################
Calling from main script
#################################################################
Path to dataset files: /home/ec2-user/.cache/kagglehub/datasets/rmisra/news-category-dataset/versions/3
Path to dataset files: /home/ec2-user/.cache/kagglehub/datasets/rmisra/news-category-dataset/versions/3
Path to dataset files: /home/ec2-user/.cache/kagglehub/datasets/rmisra/news-category-dataset/versions/3
Path to dataset files: /home/ec2-user/.cache/kagglehub/datasets/rmisra/news-category-dataset/versions/3
Number of news items in each category
####################################
category
POLITICS          35602
WELLNESS          17945
ENTERTAINMENT     17362
TRAVEL             9900
STYLE & BEAUTY     9814
PARENTING          8791
HEALTHY LIVING     6694
QUEER VOICES       6347
FOOD & DRINK       6340
BUSINESS           5992
COMEDY             5400
SPORTS             5077
BLACK VOICES       4583
HOME & LIVING      4320
PARENTS            3955
THE WORLDPOST      3664
WEDDINGS           3653
WOMEN              3572
CRIME              3562
IMPACT             3484
DIVORCE            3426
WORLD NEWS         3299
MEDIA              2944
WEIRD NEWS         2777
GREEN              2622
WORLDPOST          2579
RELIGION           2577
STYLE              2254
SCIENCE            2206
TECH               2104
TASTE              2096
MONEY              1756
ARTS               1509
ENVIRONMENT        1444
FIFTY              1401
GOOD NEWS          1398
U.S. NEWS          1377
ARTS & CULTURE     1339
COLLEGE            1144
LATINO VOICES      1130
CULTURE & ARTS     1074
EDUCATION          1014
Name: count, dtype: int64
###########################################################
Number of news items in each category
####################################
category
POLITICS          35602
WELLNESS          17945
ENTERTAINMENT     17362
TRAVEL             9900
STYLE & BEAUTY     9814
PARENTING          8791
HEALTHY LIVING     6694
QUEER VOICES       6347
FOOD & DRINK       6340
BUSINESS           5992
COMEDY             5400
SPORTS             5077
BLACK VOICES       4583
HOME & LIVING      4320
PARENTS            3955
THE WORLDPOST      3664
WEDDINGS           3653
WOMEN              3572
CRIME              3562
IMPACT             3484
DIVORCE            3426
WORLD NEWS         3299
MEDIA              2944
WEIRD NEWS         2777
GREEN              2622
WORLDPOST          2579
RELIGION           2577
STYLE              2254
SCIENCE            2206
TECH               2104
TASTE              2096
MONEY              1756
ARTS               1509
ENVIRONMENT        1444
FIFTY              1401
GOOD NEWS          1398
U.S. NEWS          1377
ARTS & CULTURE     1339
COLLEGE            1144
LATINO VOICES      1130
CULTURE & ARTS     1074
EDUCATION          1014
Name: count, dtype: int64
###########################################################
Total number of news categories in dataset: 42
###########################################################
Number of news items in each category
####################################
category
POLITICS          35602
WELLNESS          17945
ENTERTAINMENT     17362
TRAVEL             9900
STYLE & BEAUTY     9814
PARENTING          8791
HEALTHY LIVING     6694
QUEER VOICES       6347
FOOD & DRINK       6340
BUSINESS           5992
COMEDY             5400
SPORTS             5077
BLACK VOICES       4583
HOME & LIVING      4320
PARENTS            3955
THE WORLDPOST      3664
WEDDINGS           3653
WOMEN              3572
CRIME              3562
IMPACT             3484
DIVORCE            3426
WORLD NEWS         3299
MEDIA              2944
WEIRD NEWS         2777
GREEN              2622
WORLDPOST          2579
RELIGION           2577
STYLE              2254
SCIENCE            2206
TECH               2104
TASTE              2096
MONEY              1756
ARTS               1509
ENVIRONMENT        1444
FIFTY              1401
GOOD NEWS          1398
U.S. NEWS          1377
ARTS & CULTURE     1339
COLLEGE            1144
LATINO VOICES      1130
CULTURE & ARTS     1074
EDUCATION          1014
Name: count, dtype: int64
###########################################################
Number of news items in each category
####################################
category
POLITICS          35602
WELLNESS          17945
ENTERTAINMENT     17362
TRAVEL             9900
STYLE & BEAUTY     9814
PARENTING          8791
HEALTHY LIVING     6694
QUEER VOICES       6347
FOOD & DRINK       6340
BUSINESS           5992
COMEDY             5400
SPORTS             5077
BLACK VOICES       4583
HOME & LIVING      4320
PARENTS            3955
THE WORLDPOST      3664
WEDDINGS           3653
WOMEN              3572
CRIME              3562
IMPACT             3484
DIVORCE            3426
WORLD NEWS         3299
MEDIA              2944
WEIRD NEWS         2777
GREEN              2622
WORLDPOST          2579
RELIGION           2577
STYLE              2254
SCIENCE            2206
TECH               2104
TASTE              2096
MONEY              1756
ARTS               1509
ENVIRONMENT        1444
FIFTY              1401
GOOD NEWS          1398
U.S. NEWS          1377
ARTS & CULTURE     1339
COLLEGE            1144
LATINO VOICES      1130
CULTURE & ARTS     1074
EDUCATION          1014
Name: count, dtype: int64
###########################################################
Total number of news categories in dataset: 42
###########################################################
Total number of news categories in dataset: 42
###########################################################
Total number of news categories in dataset: 42
###########################################################
Map: 100%|████████████████████| 209527/209527 [00:12<00:00, 16539.01 examples/s]
Map: 100%|████████████████████| 209527/209527 [00:12<00:00, 16546.38 examples/s]
Map: 100%|████████████████████| 209527/209527 [00:12<00:00, 16503.15 examples/s]
Map: 100%|████████████████████| 209527/209527 [00:13<00:00, 15490.77 examples/s]
Map: 100%|████████████████████| 209527/209527 [00:15<00:00, 13890.44 examples/s]
Map: 100%|████████████████████| 209527/209527 [00:15<00:00, 13910.16 examples/s]
Map: 100%|████████████████████| 209527/209527 [00:15<00:00, 13831.26 examples/s]
Map: 100%|████████████████████| 209527/209527 [00:15<00:00, 13189.00 examples/s]
Map: 100%|█████████████████████| 207431/207431 [02:19<00:00, 1485.77 examples/s]
Map: 100%|█████████████████████| 207431/207431 [02:21<00:00, 1470.71 examples/s]
Map: 100%|█████████████████████████| 2096/2096 [00:01<00:00, 1634.79 examples/s]
DatasetDict({
    train: Dataset({
        features: ['headline', 'category', 'short_description', 'text', 'text_gen', 'input_ids', 'attention_mask'],
        num_rows: 207431
    })
    test: Dataset({
        features: ['headline', 'category', 'short_description', 'text', 'text_gen', 'input_ids', 'attention_mask'],
        num_rows: 2096
    })
})
{'max_new_tokens': 40, 'temperature': 0.6, 'top_p': 0.5, 'top_k': 3, 'do_sample': True, 'repetition_penalty': 1.2, 'use_cache': True, 'min_new_tokens': 10, 'eos_token_id': 128009, 'pad_token_id': 128009}
Loading weights: 100%|██████████████████████| 146/146 [00:00<00:00, 9341.58it/s]
Map: 100%|█████████████████████████| 2096/2096 [00:01<00:00, 1602.03 examples/s]
DatasetDict({
    train: Dataset({
        features: ['headline', 'category', 'short_description', 'text', 'text_gen', 'input_ids', 'attention_mask'],
        num_rows: 207431
    })
    test: Dataset({
        features: ['headline', 'category', 'short_description', 'text', 'text_gen', 'input_ids', 'attention_mask'],
        num_rows: 2096
    })
})
{'max_new_tokens': 40, 'temperature': 0.6, 'top_p': 0.5, 'top_k': 3, 'do_sample': True, 'repetition_penalty': 1.2, 'use_cache': True, 'min_new_tokens': 10, 'eos_token_id': 128009, 'pad_token_id': 128009}
Loading weights: 100%|██████████████████████| 146/146 [00:00<00:00, 7889.41it/s]
Map: 100%|█████████████████████| 207431/207431 [02:23<00:00, 1447.71 examples/s]
Map:  99%|████████████████████▊| 205794/207431 [02:22<00:01, 1508.30 examples/s][2026-04-07 06:08:28,216] [INFO] [logging.py:107:log_dist] [Rank -1] DeepSpeed info: version=0.17.2, git-hash=unknown, git-branch=unknown
Map:  99%|████████████████████▊| 205952/207431 [02:22<00:00, 1524.63 examples/s][2026-04-07 06:08:28,362] [INFO] [logging.py:107:log_dist] [Rank -1] [TorchCheckpointEngine] Initialized with serialization = False
[2026-04-07 06:08:28,363] [INFO] [logging.py:107:log_dist] [Rank -1] quantize_bits = 8 mlp_extra_grouping = False, quantize_groups = 1
[2026-04-07 06:08:28,373] [INFO] [comm.py:676:init_distributed] cdb=None
Map: 100%|█████████████████████| 207431/207431 [02:23<00:00, 1448.41 examples/s]
Map: 100%|█████████████████████████| 2096/2096 [00:01<00:00, 1577.56 examples/s]
DatasetDict({
    train: Dataset({
        features: ['headline', 'category', 'short_description', 'text', 'text_gen', 'input_ids', 'attention_mask'],
        num_rows: 207431
    })
    test: Dataset({
        features: ['headline', 'category', 'short_description', 'text', 'text_gen', 'input_ids', 'attention_mask'],
        num_rows: 2096
    })
})
{'max_new_tokens': 40, 'temperature': 0.6, 'top_p': 0.5, 'top_k': 3, 'do_sample': True, 'repetition_penalty': 1.2, 'use_cache': True, 'min_new_tokens': 10, 'eos_token_id': 128009, 'pad_token_id': 128009}
Loading weights:   0%|                                  | 0/146 [00:00<?, ?it/s][2026-04-07 06:08:29,659] [INFO] [logging.py:107:log_dist] [Rank -1] DeepSpeed info: version=0.17.2, git-hash=unknown, git-branch=unknown
Loading weights: 100%|██████████████████████| 146/146 [00:00<00:00, 8055.68it/s]
Map:  17%|████▎                     | 349/2096 [00:00<00:01, 1734.62 examples/s][2026-04-07 06:08:29,794] [INFO] [logging.py:107:log_dist] [Rank -1] [TorchCheckpointEngine] Initialized with serialization = False
[2026-04-07 06:08:29,794] [INFO] [logging.py:107:log_dist] [Rank -1] quantize_bits = 8 mlp_extra_grouping = False, quantize_groups = 1
[2026-04-07 06:08:29,804] [INFO] [comm.py:676:init_distributed] cdb=None
Map: 100%|█████████████████████████| 2096/2096 [00:01<00:00, 1580.15 examples/s]
DatasetDict({
    train: Dataset({
        features: ['headline', 'category', 'short_description', 'text', 'text_gen', 'input_ids', 'attention_mask'],
        num_rows: 207431
    })
    test: Dataset({
        features: ['headline', 'category', 'short_description', 'text', 'text_gen', 'input_ids', 'attention_mask'],
        num_rows: 2096
    })
})
{'max_new_tokens': 40, 'temperature': 0.6, 'top_p': 0.5, 'top_k': 3, 'do_sample': True, 'repetition_penalty': 1.2, 'use_cache': True, 'min_new_tokens': 10, 'eos_token_id': 128009, 'pad_token_id': 128009}
Loading weights: 100%|██████████████████████| 146/146 [00:00<00:00, 9541.27it/s]
[2026-04-07 06:08:31,999] [INFO] [logging.py:107:log_dist] [Rank -1] DeepSpeed info: version=0.17.2, git-hash=unknown, git-branch=unknown
[2026-04-07 06:08:31,999] [INFO] [logging.py:107:log_dist] [Rank -1] [TorchCheckpointEngine] Initialized with serialization = False
[2026-04-07 06:08:32,000] [INFO] [logging.py:107:log_dist] [Rank -1] quantize_bits = 8 mlp_extra_grouping = False, quantize_groups = 1
[2026-04-07 06:08:32,010] [INFO] [comm.py:676:init_distributed] cdb=None
[2026-04-07 06:08:32,010] [INFO] [comm.py:707:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
AutoTP:  [(<class 'transformers.models.llama.modeling_llama.LlamaDecoderLayer'>, ['mlp.down_proj', 'self_attn.o_proj'])]
AutoTP:  [(<class 'transformers.models.llama.modeling_llama.LlamaDecoderLayer'>, ['self_attn.o_proj', 'mlp.down_proj'])]
[2026-04-07 06:08:33,540] [INFO] [logging.py:107:log_dist] [Rank -1] DeepSpeed info: version=0.17.2, git-hash=unknown, git-branch=unknown
[2026-04-07 06:08:33,697] [INFO] [logging.py:107:log_dist] [Rank -1] [TorchCheckpointEngine] Initialized with serialization = False
[2026-04-07 06:08:33,697] [INFO] [logging.py:107:log_dist] [Rank -1] quantize_bits = 8 mlp_extra_grouping = False, quantize_groups = 1
[2026-04-07 06:08:33,707] [INFO] [comm.py:676:init_distributed] cdb=None
AutoTP:  [(<class 'transformers.models.llama.modeling_llama.LlamaDecoderLayer'>, ['self_attn.o_proj', 'mlp.down_proj'])]
AutoTP:  [(<class 'transformers.models.llama.modeling_llama.LlamaDecoderLayer'>, ['mlp.down_proj', 'self_attn.o_proj'])]
Running DeepSpeed parallelism at the end of script and main functionRunning DeepSpeed parallelism at the end of script and main function

Running DeepSpeed parallelism at the end of script and main function
Running DeepSpeed parallelism at the end of script and main function
Passing `generation_config` together with generation-related arguments=({'eos_token_id', 'temperature', 'repetition_penalty', 'top_k', 'min_new_tokens', 'do_sample', 'top_p', 'use_cache', 'max_new_tokens', 'pad_token_id'}) is deprecated and will be removed in future versions. Please pass either a `generation_config` object OR all generation parameters explicitly, but not both.
Passing `generation_config` together with generation-related arguments=({'pad_token_id', 'min_new_tokens', 'top_p', 'repetition_penalty', 'top_k', 'use_cache', 'eos_token_id', 'do_sample', 'max_new_tokens', 'temperature'}) is deprecated and will be removed in future versions. Please pass either a `generation_config` object OR all generation parameters explicitly, but not both.
Passing `generation_config` together with generation-related arguments=({'temperature', 'use_cache', 'do_sample', 'top_k', 'repetition_penalty', 'min_new_tokens', 'eos_token_id', 'max_new_tokens', 'top_p', 'pad_token_id'}) is deprecated and will be removed in future versions. Please pass either a `generation_config` object OR all generation parameters explicitly, but not both.
Passing `generation_config` together with generation-related arguments=({'eos_token_id', 'repetition_penalty', 'max_new_tokens', 'min_new_tokens', 'do_sample', 'top_k', 'top_p', 'temperature', 'pad_token_id', 'use_cache'}) is deprecated and will be removed in future versions. Please pass either a `generation_config` object OR all generation parameters explicitly, but not both.
Both `max_new_tokens` (=40) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `min_new_tokens` (=10) and `min_length`(=0) seem to have been set. `min_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=40) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `min_new_tokens` (=10) and `min_length`(=0) seem to have been set. `min_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=40) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `min_new_tokens` (=10) and `min_length`(=0) seem to have been set. `min_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=40) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `min_new_tokens` (=10) and `min_length`(=0) seem to have been set. `min_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

In [3]:
import pandas as pd
#Let us document and gather all our model/pipeline/tensor/deepspeed experiment

In [7]:
df_mp_tp = pd.read_csv("model_tensor_parallel_exp.csv")
df_mp_tp

,Unnamed: 0,EXP NAME,Mean Latency (s),Throughput (tokens/s),Avg Peak Mem,ROUGE-1 Score
0,0,Model Parallelism 4 GPU accelerate balanced,0.77337274920499,34.807431,2492.400596,0.096662
1,0,Model Parallelism 4 GPU accelerate balanced\tB...,1.77/0.06,424.470000,2785.000000,0.100000
2,0,Tensor Parallelism 4 GPU accelerate auto,0.7723638838525357,34.546899,3111.279363,0.096536
3,0,Tensor Parallelism 4 GPU accelerate auto Batch...,1.79/0.06,418.010000,3403.010000,0.100000
4,0,Tensor Parallelism 4 GPU accelerate prepare au...,1.78/0.06,422.790000,3403.060000,0.110000
5,0,Tensor Parallelism 4 GPU accelerate prepare au...,1.76/0.06,421.880000,3403.060000,0.100000
6,0,Model Parallelism 4 GPU accelerate balanced pr...,1.78/0.06,416.360000,4638.050000,0.110000
7,0,Model Parallelism 4 GPU accelerate balanced pr...,7.54/0.25,100.110000,7340.900000,0.110000
8,0,Model Parallelism 4 GPU accelerate balanced pr...,1.77/0.06,423.700000,9523.750000,0.100000

In [12]:
print(df_mp_tp['EXP NAME'].values)

['Model Parallelism 4 GPU accelerate balanced'
 'Model Parallelism 4 GPU accelerate balanced\tBatch: {data_loader.batch_size}'
 'Tensor Parallelism 4 GPU accelerate auto'
 'Tensor Parallelism 4 GPU accelerate auto Batch: {data_loader.batch_size}'
 'Tensor Parallelism 4 GPU accelerate prepare auto EXP1 Batch: {data_loader.batch_size}'
 'Tensor Parallelism 4 GPU accelerate prepare auto EXP2 Batch: {data_loader.batch_size}'
 'Model Parallelism 4 GPU accelerate balanced prepare EXP2\tBatch: {data_loader.batch_size}'
 'Model Parallelism 4 GPU accelerate balanced prepare EXP3\tBatch: {data_loader.batch_size}'
 'Model Parallelism 4 GPU accelerate balanced prepare EXP4\tBatch: {data_loader.batch_size}']

In [13]:
df_deep_pipe_paral_1 = pd.read_csv("pp_1.csv")
df_deep_pipe_paral_2 = pd.read_csv("pp.csv")
df_torch_tens_paral_1 = pd.read_csv("tp.csv")
df_tp_deep = pd.read_csv("tp_deepspeed.csv")

In [14]:
df_deep_pipe_paral_1

,Unnamed: 0,EXP NAME,Mean Latency (s),Throughput (tokens/s),Avg Peak Mem,ROUGE-1 Score
0,0,Pipeline Parallelism Single GPU,0.541154,49.645132,2381.930295,0.09454

In [15]:
df_deep_pipe_paral_2

,Unnamed: 0,EXP NAME,Mean Latency (s),Throughput (tokens/s),Avg Peak Mem,ROUGE-1 Score
0,0,Pipeline Parallelism 4 GPU,0.55252,49.12064,7098.751903,0.094213

In [16]:
df_torch_tens_paral_1

,Unnamed: 0,EXP NAME,Mean Latency (s),Throughput (tokens/s),Avg Peak Mem,ROUGE-1 Score
0,0,Tensor Parallelism 4 GPU,0.873995,30.65899,2383.137107,0.095626

In [17]:
df_tp_deep

,Unnamed: 0,EXP NAME,Mean Latency (s),Throughput (tokens/s),Avg Peak Mem,ROUGE-1 Score
0,0,DeepSpeed Parallelism 4 GPU,0.761017,35.530714,1107.439087,0.088607

In [18]:
df_tp_mp_deep_torch_consol = pd.concat([df_mp_tp, df_deep_pipe_paral_1, df_deep_pipe_paral_2,
                                        df_torch_tens_paral_1, df_tp_deep], axis=0)
df_tp_mp_deep_torch_consol

,Unnamed: 0,EXP NAME,Mean Latency (s),Throughput (tokens/s),Avg Peak Mem,ROUGE-1 Score
0,0,Model Parallelism 4 GPU accelerate balanced,0.77337274920499,34.807431,2492.400596,0.096662
1,0,Model Parallelism 4 GPU accelerate balanced\tB...,1.77/0.06,424.470000,2785.000000,0.100000
2,0,Tensor Parallelism 4 GPU accelerate auto,0.7723638838525357,34.546899,3111.279363,0.096536
3,0,Tensor Parallelism 4 GPU accelerate auto Batch...,1.79/0.06,418.010000,3403.010000,0.100000
4,0,Tensor Parallelism 4 GPU accelerate prepare au...,1.78/0.06,422.790000,3403.060000,0.110000
5,0,Tensor Parallelism 4 GPU accelerate prepare au...,1.76/0.06,421.880000,3403.060000,0.100000
6,0,Model Parallelism 4 GPU accelerate balanced pr...,1.78/0.06,416.360000,4638.050000,0.110000
7,0,Model Parallelism 4 GPU accelerate balanced pr...,7.54/0.25,100.110000,7340.900000,0.110000
8,0,Model Parallelism 4 GPU accelerate balanced pr...,1.77/0.06,423.700000,9523.750000,0.100000
0,0,Pipeline Parallelism Single GPU,0.541154,49.645132,2381.930295,0.094540
0,0,Pipeline Parallelism 4 GPU,0.55252,49.120640,7098.751903,0.094213
0,0,Tensor Parallelism 4 GPU,0.873995,30.658990,2383.137107,0.095626
0,0,DeepSpeed Parallelism 4 GPU,0.761017,35.530714,1107.439087,0.088607

In [19]:
df_tp_mp_deep_torch_consol = df_tp_mp_deep_torch_consol.drop(columns=['Unnamed: 0'])
df_tp_mp_deep_torch_consol

,EXP NAME,Mean Latency (s),Throughput (tokens/s),Avg Peak Mem,ROUGE-1 Score
0,Model Parallelism 4 GPU accelerate balanced,0.77337274920499,34.807431,2492.400596,0.096662
1,Model Parallelism 4 GPU accelerate balanced\tB...,1.77/0.06,424.470000,2785.000000,0.100000
2,Tensor Parallelism 4 GPU accelerate auto,0.7723638838525357,34.546899,3111.279363,0.096536
3,Tensor Parallelism 4 GPU accelerate auto Batch...,1.79/0.06,418.010000,3403.010000,0.100000
4,Tensor Parallelism 4 GPU accelerate prepare au...,1.78/0.06,422.790000,3403.060000,0.110000
5,Tensor Parallelism 4 GPU accelerate prepare au...,1.76/0.06,421.880000,3403.060000,0.100000
6,Model Parallelism 4 GPU accelerate balanced pr...,1.78/0.06,416.360000,4638.050000,0.110000
7,Model Parallelism 4 GPU accelerate balanced pr...,7.54/0.25,100.110000,7340.900000,0.110000
8,Model Parallelism 4 GPU accelerate balanced pr...,1.77/0.06,423.700000,9523.750000,0.100000
0,Pipeline Parallelism Single GPU,0.541154,49.645132,2381.930295,0.094540
0,Pipeline Parallelism 4 GPU,0.55252,49.120640,7098.751903,0.094213
0,Tensor Parallelism 4 GPU,0.873995,30.658990,2383.137107,0.095626
0,DeepSpeed Parallelism 4 GPU,0.761017,35.530714,1107.439087,0.088607

In [20]:
df_tp_mp_deep_torch_consol.reset_index(inplace=True, drop=True)

In [21]:
df_tp_mp_deep_torch_consol

,EXP NAME,Mean Latency (s),Throughput (tokens/s),Avg Peak Mem,ROUGE-1 Score
0,Model Parallelism 4 GPU accelerate balanced,0.77337274920499,34.807431,2492.400596,0.096662
1,Model Parallelism 4 GPU accelerate balanced\tB...,1.77/0.06,424.470000,2785.000000,0.100000
2,Tensor Parallelism 4 GPU accelerate auto,0.7723638838525357,34.546899,3111.279363,0.096536
3,Tensor Parallelism 4 GPU accelerate auto Batch...,1.79/0.06,418.010000,3403.010000,0.100000
4,Tensor Parallelism 4 GPU accelerate prepare au...,1.78/0.06,422.790000,3403.060000,0.110000
5,Tensor Parallelism 4 GPU accelerate prepare au...,1.76/0.06,421.880000,3403.060000,0.100000
6,Model Parallelism 4 GPU accelerate balanced pr...,1.78/0.06,416.360000,4638.050000,0.110000
7,Model Parallelism 4 GPU accelerate balanced pr...,7.54/0.25,100.110000,7340.900000,0.110000
8,Model Parallelism 4 GPU accelerate balanced pr...,1.77/0.06,423.700000,9523.750000,0.100000
9,Pipeline Parallelism Single GPU,0.541154,49.645132,2381.930295,0.094540
10,Pipeline Parallelism 4 GPU,0.55252,49.120640,7098.751903,0.094213
11,Tensor Parallelism 4 GPU,0.873995,30.658990,2383.137107,0.095626
12,DeepSpeed Parallelism 4 GPU,0.761017,35.530714,1107.439087,0.088607

In [22]:
df_tp_mp_deep_torch_consol.to_csv("tp_mp_deep_torch_consol_exp.csv")

# 7. Advanced Decoding: Speculative Decoding

**Your Task:** Speculative decoding uses a smaller, faster "draft" model to generate several candidate tokens. A larger, more accurate "target" model then verifies these tokens in a single forward pass. This can significantly speed up generation if the draft model is a good predictor. You will load a larger target model and a smaller draft model, benchmark the target model alone, and then benchmark it with assistance from the draft model.

In [63]:
generation_args['use_cache'] = True
generation_args

{'max_new_tokens': 40,
 'temperature': 0.6,
 'top_p': 0.5,
 'top_k': 3,
 'do_sample': True,
 'repetition_penalty': 1.2,
 'use_cache': True,
 'min_new_tokens': 10,
 'eos_token_id': 128009,
 'pad_token_id': 128009}

In [64]:
# TODO: Implement and evaluate speculative decoding.
exp = "Spec_Decod targ_mod baseline"
df = run_exp(exp, df, tok_ds, DEVICE, generation_args, quantization_config=None, prune=False, MODEL_NAME=BIG_MODEL_ID)

Loading tokenizer...

config.json:   0%|          | 0.00/878 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/296 [00:00<?, ?B/s]

Tokenizer loaded successfully.

Loading model...

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/254 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/189 [00:00<?, ?B/s]

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Model loaded successfully and moved to device.
Memory Footprint: 6127.83 MB

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

WarmUp runs completed
0.6226110306300018 40.714634254987956 14780.478115234375 0.10834754276964564

In [65]:
df

,EXP NAME,Mean Latency (s),Throughput (tokens/s),Avg Peak Mem,ROUGE-1 Score
0,Baseline (No Cache),0.379463,70.711373,4735.894863,0.093031
0,Baseline (No Cache) Batch: 32,9.07/0.29,83.700000,5165.910000,0.100000
0,KV Caching,0.380166,69.922486,7094.697355,0.094828
0,KV Caching Batch: 32,0.94/0.03,795.090000,5197.500000,0.100000
0,Pruning (30%),0.476401,68.211354,7094.718452,0.075253
0,Pruning (30%) Batch: 32,0.97/0.03,800.730000,7556.620000,0.130000
0,Quantization (4-bit),0.546794,47.850955,8148.832456,0.079853
0,Quantization (4-bit) Batch: 32,1.44/0.05,468.510000,9100.800000,0.090000
0,Spec_Decod targ_mod baseline,0.622611,40.714634,14780.478115,0.108348

In [66]:
_, target_model = load_model(BIG_MODEL_ID, DEVICE, quantization_config=None)

Loading tokenizer...
Tokenizer loaded successfully.

Loading model...

Loading weights:   0%|          | 0/254 [00:00<?, ?it/s]

Model loaded successfully and moved to device.
Memory Footprint: 6127.83 MB

In [67]:
exp = f"Spec_Decod targ_mod baseline Batch: {data_loader.batch_size}"
df = generate_headline_batch(target_model, tokenizer, DEVICE, generation_args, data_loader, exp, df)

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

WarmUp runs completed
Batch 0
Batch 1
Batch 2
Batch 3
Batch 4
Batch 5
Batch 6
Batch 7
Batch 8
Batch 9
Batch 10
Batch 11
Batch 12
2.0022785753075927 0.06507405369749676 400.41460507492775 15683.796612079326 0.08109203974867299

In [68]:
df

,EXP NAME,Mean Latency (s),Throughput (tokens/s),Avg Peak Mem,ROUGE-1 Score
0,Baseline (No Cache),0.379463,70.711373,4735.894863,0.093031
0,Baseline (No Cache) Batch: 32,9.07/0.29,83.700000,5165.910000,0.100000
0,KV Caching,0.380166,69.922486,7094.697355,0.094828
0,KV Caching Batch: 32,0.94/0.03,795.090000,5197.500000,0.100000
0,Pruning (30%),0.476401,68.211354,7094.718452,0.075253
0,Pruning (30%) Batch: 32,0.97/0.03,800.730000,7556.620000,0.130000
0,Quantization (4-bit),0.546794,47.850955,8148.832456,0.079853
0,Quantization (4-bit) Batch: 32,1.44/0.05,468.510000,9100.800000,0.090000
0,Spec_Decod targ_mod baseline,0.622611,40.714634,14780.478115,0.108348
0,Spec_Decod targ_mod baseline Batch: 32,2.0/0.07,400.410000,15683.800000,0.080000

In [69]:
_, draft_model = load_model(MODEL_NAME, DEVICE, quantization_config=None)

Loading tokenizer...
Tokenizer loaded successfully.

Loading model...

Loading weights:   0%|          | 0/146 [00:00<?, ?it/s]

Model loaded successfully and moved to device.
Memory Footprint: 2357.13 MB

In [70]:
generation_args['max_new_tokens'] = 40
generation_args

{'max_new_tokens': 40,
 'temperature': 0.6,
 'top_p': 0.5,
 'top_k': 3,
 'do_sample': True,
 'repetition_penalty': 1.2,
 'use_cache': True,
 'min_new_tokens': 10,
 'eos_token_id': 128009,
 'pad_token_id': 128009}

In [71]:
generation_args_target = generation_args.copy()
generation_args_target['max_new_tokens'] = 1
generation_args_target

{'max_new_tokens': 1,
 'temperature': 0.6,
 'top_p': 0.5,
 'top_k': 3,
 'do_sample': True,
 'repetition_penalty': 1.2,
 'use_cache': True,
 'min_new_tokens': 10,
 'eos_token_id': 128009,
 'pad_token_id': 128009}

In [72]:
generation_args_draft = generation_args.copy()
generation_args_draft['max_new_tokens'] = 10
generation_args_draft

{'max_new_tokens': 10,
 'temperature': 0.6,
 'top_p': 0.5,
 'top_k': 3,
 'do_sample': True,
 'repetition_penalty': 1.2,
 'use_cache': True,
 'min_new_tokens': 10,
 'eos_token_id': 128009,
 'pad_token_id': 128009}

In [73]:
generation_args

{'max_new_tokens': 40,
 'temperature': 0.6,
 'top_p': 0.5,
 'top_k': 3,
 'do_sample': True,
 'repetition_penalty': 1.2,
 'use_cache': True,
 'min_new_tokens': 10,
 'eos_token_id': 128009,
 'pad_token_id': 128009}

In [74]:
draft_model = draft_model.eval()
target_model = target_model.eval()

In [75]:
def speculate(new_inp, draft_model, target_model, device, generation_args_draft, generation_args_target):
    
    orig_toks_len = new_inp.shape[1]
    #print(f'Sepculate: {orig_toks_len}')
    with torch.inference_mode():
        out_draft = draft_model.generate(input_ids=new_inp, **generation_args_draft)
    if device == 'cuda':
        torch.cuda.synchronize()
    out_draft_len = out_draft.shape[1]
    delta_toks  = out_draft_len - orig_toks_len
            
    new_toks = new_inp[0].tolist() + out_draft[0][-delta_toks:].tolist()
    delta_draft_toks = new_toks[-delta_toks:]
    new_toks = torch.tensor(new_toks).unsqueeze(0).to(device)
    with torch.inference_mode():
        out_target = target_model.generate(input_ids=new_toks,  **generation_args_target)
    if device == 'cuda':
        torch.cuda.synchronize()
    delta_target_toks = out_target[0].tolist()[-(delta_toks+1):-1]
    return delta_draft_toks, delta_target_toks

In [76]:
def match(delta_draft_toks, delta_target_toks, delta_agreed_toks):
    for i, d in enumerate(delta_draft_toks):
        if d == delta_target_toks[i]:
            delta_agreed_toks.append(d)
        else:
            break
    return delta_agreed_toks

In [77]:
def generate_spec_headline(draft_model, target_model, tokenizer, toks, device, generation_args, generation_args_draft, generation_args_target, delta_agreed_toks):
    """TODO: Implement the headline generation and latency measurement logic."""

    t0 = time.perf_counter()
    delta_draft_toks, delta_target_toks =  speculate(toks, draft_model, target_model, device, generation_args_draft, generation_args_target)
    delta_agreed_toks = match(delta_draft_toks, delta_target_toks, delta_agreed_toks)
    
    while delta_agreed_toks[-1] != tokenizer.eos_token_id:
        if (len(delta_agreed_toks) < generation_args['max_new_tokens']):
            new_inp = torch.tensor(toks[0].tolist() + delta_agreed_toks).unsqueeze(0).to(device)
            delta_draft_toks, delta_target_toks = speculate(new_inp, draft_model, target_model, device, generation_args_draft, generation_args_target)
            delta_agreed_toks = match(delta_draft_toks, delta_target_toks, delta_agreed_toks)
            #print(f'delta agreed toks {delta_agreed_toks}')
        else:
            break
    ################################################################
    t1 = time.perf_counter()
    #print(tokenizer.decode(toks[0].tolist()))
    #print(tokenizer.decode(delta_agreed_toks))
    final_output = toks[0].tolist() + delta_agreed_toks
    #print(tokenizer.decode(final_output))
    latency = t1 - t0
    gen_len = len(delta_agreed_toks)
    peak_mem_mib = torch.cuda.max_memory_allocated(device) / 1024**2
    throughput = gen_len / latency if latency > 0 else float("nan")
    outputs_text = tokenizer.decode(final_output)
    #print(outputs_text)
    #print("#################################################################")
    outputs_text = remove_punctuation(outputs_text.split('<|start_header_id|>assistant<|end_header_id|>')[-1].split('<|eot_id|>')[0].strip())
    #print(outputs_text)
    return latency, throughput, peak_mem_mib, outputs_text

In [78]:
def eval_spec(dataset, draft_model, target_model, tokenizer, device, generation_args, generation_args_draft, generation_args_target, n=2):
    sample = random.sample(range(1000), 1)[0]
    warmup_example = dataset['train'][sample]
    toks = apply_chat_temp(warmup_example, generate_text=True)
    toks['input_ids'] = torch.tensor(toks['input_ids']).unsqueeze(0).to(device)
    toks['attention_mask'] = torch.tensor(toks['attention_mask']).unsqueeze(0).to(device)
    cuda_warmup(draft_model, toks['input_ids'], device)
    cuda_warmup(target_model, toks['input_ids'], device)

    torch.cuda.reset_peak_memory_stats(device)
    samples = 100
    latencies = []
    throughputs = []
    peak_mem = []
    outputs = []
    references = []
    delta_agreed_toks = []

    for i in range(n):
        for j in range(samples):
            delta_agreed_toks = []
            sample = dataset['train'][j]
            references.append(sample['headline'])
            toks = apply_chat_temp(sample, generate_text=True)
            toks['input_ids'] = torch.tensor(toks['input_ids']).unsqueeze(0).to(device)
            orig_toks_len = toks['input_ids'].shape[1]
            latency, throughput, peak_mem_mib, outputs_text = generate_spec_headline(draft_model, target_model, tokenizer, toks['input_ids'], device, generation_args, generation_args_draft, generation_args_target, delta_agreed_toks)
            latencies.append(latency)
            throughputs.append(throughput)
            peak_mem.append(peak_mem_mib)
            outputs.append(outputs_text)
    rouge = evaluate.load("rouge")
    rouge_score = rouge.compute(predictions=outputs, references=references)['rouge1']
    avg_latency = sum(latencies) / len(latencies)
    avg_throughput = sum(throughputs) / len(throughputs)
    avg_peak_mib = sum(peak_mem)/len(peak_mem)
    print(avg_latency, avg_throughput, avg_peak_mib, rouge_score)
    #print(outputs)
    #print("####################################")
    #print(references)
    return avg_latency, avg_throughput, avg_peak_mib, rouge_score

In [79]:
def report_spec_metrics(tok_ds,  draft_model, target_model, tokenizer, device, generation_args, generation_args_draft, generation_args_target, exp, df):
    """TODO: Implement the logic for calculating and reporting all performance metrics."""
    avg_latency, avg_throughput, avg_peak_mib, rouge_score = eval_spec(tok_ds, draft_model, target_model, tokenizer, device, generation_args, generation_args_draft, generation_args_target, n=4)
    new_df = pd.DataFrame({"EXP NAME": [exp], "Mean Latency (s)": [avg_latency], "Throughput (tokens/s)": [avg_throughput], "Avg Peak Mem": [avg_peak_mib], "ROUGE-1 Score": [rouge_score]}) 
    df = pd.concat([df, new_df], axis=0)
    return df

In [80]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [81]:
tok_ds

DatasetDict({
    train: Dataset({
        features: ['headline', 'category', 'short_description', 'text', 'text_gen', 'input_ids', 'attention_mask', 'headline_ids'],
        num_rows: 207431
    })
    test: Dataset({
        features: ['headline', 'category', 'short_description', 'text', 'text_gen', 'input_ids', 'attention_mask', 'headline_ids'],
        num_rows: 2096
    })
})

In [82]:
exp = "Speculative Decoding 10 tokens lookahead"
df = report_spec_metrics(tok_ds, draft_model, target_model, tokenizer, device, generation_args, generation_args_draft, generation_args_target, exp, df)

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

WarmUp runs completed

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

WarmUp runs completed
0.7021917708050079 56.976719606217365 17147.517631835937 0.08650317847947452

In [83]:
df

,EXP NAME,Mean Latency (s),Throughput (tokens/s),Avg Peak Mem,ROUGE-1 Score
0,Baseline (No Cache),0.379463,70.711373,4735.894863,0.093031
0,Baseline (No Cache) Batch: 32,9.07/0.29,83.700000,5165.910000,0.100000
0,KV Caching,0.380166,69.922486,7094.697355,0.094828
0,KV Caching Batch: 32,0.94/0.03,795.090000,5197.500000,0.100000
0,Pruning (30%),0.476401,68.211354,7094.718452,0.075253
0,Pruning (30%) Batch: 32,0.97/0.03,800.730000,7556.620000,0.130000
0,Quantization (4-bit),0.546794,47.850955,8148.832456,0.079853
0,Quantization (4-bit) Batch: 32,1.44/0.05,468.510000,9100.800000,0.090000
0,Spec_Decod targ_mod baseline,0.622611,40.714634,14780.478115,0.108348
0,Spec_Decod targ_mod baseline Batch: 32,2.0/0.07,400.410000,15683.800000,0.080000
0,Speculative Decoding 10 tokens lookahead,0.702192,56.976720,17147.517632,0.086503

In [84]:
df.to_csv("llminference.csv")

In [1]:
#Consolidating all runs
import pandas as pd

In [2]:
df = pd.read_csv("llminference.csv")
df

,Unnamed: 0,EXP NAME,Mean Latency (s),Throughput (tokens/s),Avg Peak Mem,ROUGE-1 Score
0,0,Baseline (No Cache),0.37946256138000395,70.711373,4735.894863,0.093031
1,0,Baseline (No Cache) Batch: 32,9.07/0.29,83.700000,5165.910000,0.100000
2,0,KV Caching,0.3801660053274935,69.922486,7094.697355,0.094828
3,0,KV Caching Batch: 32,0.94/0.03,795.090000,5197.500000,0.100000
4,0,Pruning (30%),0.4764006964599969,68.211354,7094.718452,0.075253
5,0,Pruning (30%) Batch: 32,0.97/0.03,800.730000,7556.620000,0.130000
6,0,Quantization (4-bit),0.5467937357949978,47.850955,8148.832456,0.079853
7,0,Quantization (4-bit) Batch: 32,1.44/0.05,468.510000,9100.800000,0.090000
8,0,Spec_Decod targ_mod baseline,0.6226110306300018,40.714634,14780.478115,0.108348
9,0,Spec_Decod targ_mod baseline Batch: 32,2.0/0.07,400.410000,15683.800000,0.080000
10,0,Speculative Decoding 10 tokens lookahead,0.7021917708050079,56.976720,17147.517632,0.086503

In [3]:
df_1 = pd.read_csv("tp_mp_deep_torch_consol_exp.csv")
df_1

,Unnamed: 0,EXP NAME,Mean Latency (s),Throughput (tokens/s),Avg Peak Mem,ROUGE-1 Score
0,0,Model Parallelism 4 GPU accelerate balanced,0.77337274920499,34.807431,2492.400596,0.096662
1,1,Model Parallelism 4 GPU accelerate balanced\tB...,1.77/0.06,424.470000,2785.000000,0.100000
2,2,Tensor Parallelism 4 GPU accelerate auto,0.7723638838525357,34.546899,3111.279363,0.096536
3,3,Tensor Parallelism 4 GPU accelerate auto Batch...,1.79/0.06,418.010000,3403.010000,0.100000
4,4,Tensor Parallelism 4 GPU accelerate prepare au...,1.78/0.06,422.790000,3403.060000,0.110000
5,5,Tensor Parallelism 4 GPU accelerate prepare au...,1.76/0.06,421.880000,3403.060000,0.100000
6,6,Model Parallelism 4 GPU accelerate balanced pr...,1.78/0.06,416.360000,4638.050000,0.110000
7,7,Model Parallelism 4 GPU accelerate balanced pr...,7.54/0.25,100.110000,7340.900000,0.110000
8,8,Model Parallelism 4 GPU accelerate balanced pr...,1.77/0.06,423.700000,9523.750000,0.100000
9,9,Pipeline Parallelism Single GPU,0.5411535008625151,49.645132,2381.930295,0.094540
10,10,Pipeline Parallelism 4 GPU,0.5525196632350753,49.120640,7098.751903,0.094213
11,11,Tensor Parallelism 4 GPU,0.8739954969274959,30.658990,2383.137107,0.095626
12,12,DeepSpeed Parallelism 4 GPU,0.7610173620650176,35.530714,1107.439087,0.088607

In [4]:
#consoliudating all dataframes

In [5]:
df_consol = pd.concat([df,df_1], axis=0)
df_consol.reset_index(inplace=True, drop=True)
df_consol.drop(columns=['Unnamed: 0'], inplace=True)

In [6]:
df_consol

,EXP NAME,Mean Latency (s),Throughput (tokens/s),Avg Peak Mem,ROUGE-1 Score
0,Baseline (No Cache),0.37946256138000395,70.711373,4735.894863,0.093031
1,Baseline (No Cache) Batch: 32,9.07/0.29,83.700000,5165.910000,0.100000
2,KV Caching,0.3801660053274935,69.922486,7094.697355,0.094828
3,KV Caching Batch: 32,0.94/0.03,795.090000,5197.500000,0.100000
4,Pruning (30%),0.4764006964599969,68.211354,7094.718452,0.075253
5,Pruning (30%) Batch: 32,0.97/0.03,800.730000,7556.620000,0.130000
6,Quantization (4-bit),0.5467937357949978,47.850955,8148.832456,0.079853
7,Quantization (4-bit) Batch: 32,1.44/0.05,468.510000,9100.800000,0.090000
8,Spec_Decod targ_mod baseline,0.6226110306300018,40.714634,14780.478115,0.108348
9,Spec_Decod targ_mod baseline Batch: 32,2.0/0.07,400.410000,15683.800000,0.080000
10,Speculative Decoding 10 tokens lookahead,0.7021917708050079,56.976720,17147.517632,0.086503
11,Model Parallelism 4 GPU accelerate balanced,0.77337274920499,34.807431,2492.400596,0.096662
12,Model Parallelism 4 GPU accelerate balanced\tB...,1.77/0.06,424.470000,2785.000000,0.100000
13,Tensor Parallelism 4 GPU accelerate auto,0.7723638838525357,34.546899,3111.279363,0.096536
14,Tensor Parallelism 4 GPU accelerate auto Batch...,1.79/0.06,418.010000,3403.010000,0.100000
15,Tensor Parallelism 4 GPU accelerate prepare au...,1.78/0.06,422.790000,3403.060000,0.110000
16,Tensor Parallelism 4 GPU accelerate prepare au...,1.76/0.06,421.880000,3403.060000,0.100000
17,Model Parallelism 4 GPU accelerate balanced pr...,1.78/0.06,416.360000,4638.050000,0.110000
18,Model Parallelism 4 GPU accelerate balanced pr...,7.54/0.25,100.110000,7340.900000,0.110000
19,Model Parallelism 4 GPU accelerate balanced pr...,1.77/0.06,423.700000,9523.750000,0.100000
20,Pipeline Parallelism Single GPU,0.5411535008625151,49.645132,2381.930295,0.094540
21,Pipeline Parallelism 4 GPU,0.5525196632350753,49.120640,7098.751903,0.094213
22,Tensor Parallelism 4 GPU,0.8739954969274959,30.658990,2383.137107,0.095626
23,DeepSpeed Parallelism 4 GPU,0.7610173620650176,35.530714,1107.439087,0.088607

In [27]:
df_consol.to_csv("course4_project_consol.csv")

In [29]:
for i in df_consol['EXP NAME'].values:
    print(i)

Baseline (No Cache)
Baseline (No Cache) Batch: 32
KV Caching
KV Caching Batch: 32
Pruning (30%)
Pruning (30%) Batch: 32
Quantization (4-bit)
Quantization (4-bit) Batch: 32
Spec_Decod targ_mod baseline
Spec_Decod targ_mod baseline Batch: 32
Speculative Decoding 10 tokens lookahead
Model Parallelism 4 GPU accelerate balanced
Model Parallelism 4 GPU accelerate balanced	Batch: {data_loader.batch_size}
Tensor Parallelism 4 GPU accelerate auto
Tensor Parallelism 4 GPU accelerate auto Batch: {data_loader.batch_size}
Tensor Parallelism 4 GPU accelerate prepare auto EXP1 Batch: {data_loader.batch_size}
Tensor Parallelism 4 GPU accelerate prepare auto EXP2 Batch: {data_loader.batch_size}
Model Parallelism 4 GPU accelerate balanced prepare EXP2	Batch: {data_loader.batch_size}
Model Parallelism 4 GPU accelerate balanced prepare EXP3	Batch: {data_loader.batch_size}
Model Parallelism 4 GPU accelerate balanced prepare EXP4	Batch: {data_loader.batch_size}
Pipeline Parallelism Single GPU
Pipeline Parallelism 4 GPU
Tensor Parallelism 4 GPU
DeepSpeed Parallelism 4 GPU

# 8. Final Report and Analysis

**Your Task:** Consolidate your findings into a summary report. 

1.  Fill in the Markdown table below with the **Latency**, **Throughput**, and **ROUGE scores** for each optimization technique you implemented. --> ***Please see the dataframe output below. For rest project report is being attached with final submission***
2. Compile the final Project Report in PDF format:
    *   Document the entire process, detailing the methodology, techniques, and libraries used.
    *   Present the final benchmark results clearly.
    *   Provide a thorough analysis of the trade-offs between performance, resources, and quality for each optimization step.
    *   Conclude with recommendations for the most effective optimization strategy for this specific headline generation task, supported by your data.

Some example questions for discussing the trade-offs:
    *   Which method gave the best performance improvement?
    *   Did any methods significantly hurt the ROUGE score (quality)?
    *   Which optimization would you recommend for deployment in a production environment at the news portal, and why? Consider factors like cost, complexity, and performance.

## Performance Comparison

In [7]:
df_consol

,EXP NAME,Mean Latency (s),Throughput (tokens/s),Avg Peak Mem,ROUGE-1 Score
0,Baseline (No Cache),0.37946256138000395,70.711373,4735.894863,0.093031
1,Baseline (No Cache) Batch: 32,9.07/0.29,83.700000,5165.910000,0.100000
2,KV Caching,0.3801660053274935,69.922486,7094.697355,0.094828
3,KV Caching Batch: 32,0.94/0.03,795.090000,5197.500000,0.100000
4,Pruning (30%),0.4764006964599969,68.211354,7094.718452,0.075253
5,Pruning (30%) Batch: 32,0.97/0.03,800.730000,7556.620000,0.130000
6,Quantization (4-bit),0.5467937357949978,47.850955,8148.832456,0.079853
7,Quantization (4-bit) Batch: 32,1.44/0.05,468.510000,9100.800000,0.090000
8,Spec_Decod targ_mod baseline,0.6226110306300018,40.714634,14780.478115,0.108348
9,Spec_Decod targ_mod baseline Batch: 32,2.0/0.07,400.410000,15683.800000,0.080000
10,Speculative Decoding 10 tokens lookahead,0.7021917708050079,56.976720,17147.517632,0.086503
11,Model Parallelism 4 GPU accelerate balanced,0.77337274920499,34.807431,2492.400596,0.096662
12,Model Parallelism 4 GPU accelerate balanced\tB...,1.77/0.06,424.470000,2785.000000,0.100000
13,Tensor Parallelism 4 GPU accelerate auto,0.7723638838525357,34.546899,3111.279363,0.096536
14,Tensor Parallelism 4 GPU accelerate auto Batch...,1.79/0.06,418.010000,3403.010000,0.100000
15,Tensor Parallelism 4 GPU accelerate prepare au...,1.78/0.06,422.790000,3403.060000,0.110000
16,Tensor Parallelism 4 GPU accelerate prepare au...,1.76/0.06,421.880000,3403.060000,0.100000
17,Model Parallelism 4 GPU accelerate balanced pr...,1.78/0.06,416.360000,4638.050000,0.110000
18,Model Parallelism 4 GPU accelerate balanced pr...,7.54/0.25,100.110000,7340.900000,0.110000
19,Model Parallelism 4 GPU accelerate balanced pr...,1.77/0.06,423.700000,9523.750000,0.100000
20,Pipeline Parallelism Single GPU,0.5411535008625151,49.645132,2381.930295,0.094540
21,Pipeline Parallelism 4 GPU,0.5525196632350753,49.120640,7098.751903,0.094213
22,Tensor Parallelism 4 GPU,0.8739954969274959,30.658990,2383.137107,0.095626
23,DeepSpeed Parallelism 4 GPU,0.7610173620650176,35.530714,1107.439087,0.088607